$(document).ready(function(){


	var art_raw = [

		"food: 3, art: 2, still life: 2, man: 2, indoors: 2, woman: 2, painting: 2, plate: 2, cup: 2, no person: 1, container: 1, people: 1, grow: 1, one: 1, jar: 1, cooking: 1, kitchenware: 1, business: 1, retro: 1, adult: 1, money: 1, bowl: 1, science: 1, brown wooden framed wall decor: 1, bread beside jar painting: 1, still life photography: 1, dishware: 1, serveware: 1, photography: 1, artwork: 1, tableware: 1, dinnerware set: 1, pottery: 1, goblet: 1, glass: 1, coffee cup: 1, furniture: 1, saucer: 1, bread: 1, alcohol: 1, beer: 1, beverage: 1, drink: 1, jug: 1, bell jar: 1, protective covering: 1, lp: 1, memory device: 1, drum: 1, percussion instrument: 1, musical instrument: 1, phonograph record: 1, recording: 1, light brown color: 1, reddish brown color: 1, a cup of coffee: 1, sitting: 1, small: 1, old: 1, table: 1, brown: 1, banana: 1, black: 1, white: 1, holding: 1, red: 1, cat: 1",
		"furniture: 4, table: 4, room: 3, chair: 3, indoors: 3, street: 2, monochrome: 2, city: 2, window: 2, desk: 2, urban: 2, office: 2, black: 2, building: 2, alley: 2, no person: 1, people: 1, seat: 1, architecture: 1, house: 1, family: 1, business: 1, art: 1, black wooden framed glass panel: 1, gray gang chair and graffiti wall art: 1, black-and-white: 1, interior design: 1, monochrome photography: 1, still life photography: 1, photography: 1, human: 1, person: 1, road: 1, town: 1, electronics: 1, wall: 1, leisure activities: 1, alleyway: 1, laundry: 1, basement: 1, support: 1, supporting structure: 1, gray color: 1, black color: 1, a chair in a room: 1, indoor: 1, living: 1, sitting: 1, photo: 1, small: 1, white: 1, bed: 1, laptop: 1, bench: 1, computer: 1, kitchen: 1, old: 1, bedroom: 1, covered: 1, woman: 1, stove: 1",
		"painting: 3, art: 3, portrait: 3, woman: 2, person: 2, clothing: 2, illustration: 1, nymph: 1, vintage: 1, artistic: 1, print: 1, people: 1, impressionism: 1, retro: 1, wear: 1, dress: 1, princess: 1, fashion: 1, canvas: 1, pastel: 1, fairy: 1, one: 1, woman in white dress painting: 1, woman in white top painting: 1, lady: 1, watercolor paint: 1, self-portrait: 1, retro style: 1, visual arts: 1, modern art: 1, human: 1, photo: 1, photography: 1, face: 1, apparel: 1, oil paint: 1, paint: 1, headdress: 1, reddish orange color: 1, luisa casati looking at the camera: 1, looking: 1, wearing: 1, front: 1, standing: 1, holding: 1, old: 1, hair: 1, glass: 1, man: 1, large: 1, young: 1, display: 1, water: 1",
		"wood: 2, wooden: 2, stick: 2, tool: 2, retro: 1, no person: 1, alphabet: 1, carpentry: 1, furniture: 1, carve: 1, writing: 1, empty: 1, design: 1, antique: 1, art: 1, old: 1, rustic: 1, disjunct: 1, dirty: 1, hardwood: 1, typeset: 1, typography: 1, brown wooden 2-door cabinet: 1, brown furniture leg: 1, cane: 1, axe: 1, ax head: 1, inclined plane: 1, machine: 1, mechanical device: 1, hatchet: 1, ax: 1, cutlery: 1, boomerang: 1, weapon: 1, tomahawk: 1, reddish brown color: 1, dark red color: 1, a wooden table: 1, dark: 1, sitting: 1, table: 1, mirror: 1, standing: 1, room: 1, man: 1",
		"painting: 4, art: 3, nature: 3, tree: 2, old: 2, landscape: 2, illustration: 1, no person: 1, religion: 1, travel: 1, visuals: 1, cave: 1, color: 1, wall: 1, image: 1, fall: 1, artistic: 1, wood: 1, deep: 1, print: 1, green and brown abstract painting: 1, painting of trees: 1, modern art: 1, visual arts: 1, watercolor paint: 1, acrylic paint: 1, artwork: 1, formation: 1, plant: 1, mural: 1, oil paint: 1, paint: 1, indoors: 1, fabric: 1, olive green color: 1, greenishness color: 1, a painting of a canyon: 1, canyon: 1, mountain: 1, grass: 1, forest: 1, field: 1, colorful: 1, grazing: 1, train: 1",
		"painting: 4, art: 3, water: 3, wave: 2, modern art: 2, animal: 2, bird: 2, canvas: 1, artistic: 1, illustration: 1, visuals: 1, graphic: 1, abstract: 1, texture: 1, watercolor: 1, color: 1, pastel: 1, design: 1, creativity: 1, impression: 1, pattern: 1, paper: 1, brush: 1, stain: 1, green and blue abstract painting: 1, trees and grass painting: 1, acrylic paint: 1, watercolor paint: 1, visual arts: 1, landscape: 1, wind wave: 1, nature: 1, outdoors: 1, oil paint: 1, paint: 1, encaustic paint: 1, ultramarine color: 1, greenish blue color: 1, a painting of a waterfall: 1, mountain: 1, riding: 1, man: 1, standing: 1, sitting: 1, brown: 1, large: 1, blue: 1, waterfall: 1, covered: 1, young: 1, horse: 1, colorful: 1, surfing: 1, group: 1, field: 1, grazing: 1, zebra: 1, white: 1, snow: 1, laying: 1, herd: 1",
		"tree: 5, nature: 3, forest: 3, plant: 3, rainforest: 2, green: 2, wood: 1, leaf: 1, landscape: 1, jungle: 1, no person: 1, mist: 1, dawn: 1, desktop: 1, color: 1, fall: 1, park: 1, branch: 1, lush: 1, guidance: 1, flora: 1, summer: 1, barbaric: 1, offensive: 1, green trees painting: 1, natural environment: 1, northern hardwood forest: 1, woodland: 1, old-growth forest: 1, vegetation: 1, tropical and subtropical coniferous forests: 1, painting: 1, art: 1, cottage: 1, house: 1, building: 1, housing: 1, outdoors: 1, alpine ash: 1, eucalyptus: 1, new zealand beech: 1, black beech: 1, loblolly pine: 1, pine tree: 1, greenishness color: 1, a tree in a forest: 1, grass: 1, field: 1, wooded: 1, area: 1, sitting: 1, grazing: 1, red: 1, black: 1, standing: 1, bench: 1, large: 1, giraffe: 1, yellow: 1, grassy: 1, white: 1, group: 1",
		"art: 3, portrait: 3, painting: 3, man: 2, photography: 2, drawing: 2, photo: 2, one: 1, no person: 1, wear: 1, people: 1, adult: 1, paper: 1, vintage: 1, retro: 1, woman: 1, print: 1, monochrome: 1, snow: 1, nude: 1, antique: 1, desktop: 1, illustration: 1, offensive: 1, helga matura grayscale photo: 1, photograph: 1, lady: 1, black-and-white: 1, stock photography: 1, chest: 1, long hair: 1, face: 1, sketch: 1, skin: 1, outdoors: 1, canvas: 1, nature: 1, person: 1, passe-partout (frame): 1, framework: 1, supporting structure: 1, silverpoint: 1, black color: 1, ash grey color: 1, a waterfall in the background: 1, white: 1, waterfall: 1, laying: 1, water: 1, cat: 1",
		"painting: 3, art: 3, person: 3, portrait: 2, man: 2, clothing: 2, people: 1, one: 1, adult: 1, wear: 1, woman: 1, print: 1, illustration: 1, coat: 1, veil: 1, outerwear: 1, vintage: 1, lid: 1, retro: 1, model: 1, girl: 1, music: 1, black and yellow long sleeve shirt: 1, woman wearing black dress holding drinking glass painting: 1, human: 1, apparel: 1, oil paint: 1, paint: 1, fish: 1, bottle green color: 1, a man standing in front of a door: 1, standing: 1, holding: 1, front: 1, black: 1, walking: 1, wearing: 1, young: 1, street: 1, door: 1, boy: 1, large: 1, suit: 1, riding: 1, water: 1, rain: 1, old: 1, umbrella: 1, board: 1, night: 1, white: 1, room: 1",
		"sculpture: 2, standing: 2, no person: 1, one: 1, wear: 1, isolated: 1, fashion: 1, man: 1, figure: 1, steel: 1, woman: 1, cutout: 1, leather: 1, adult: 1, indoors: 1, people: 1, retro: 1, military: 1, contemporary: 1, chrome: 1, glazed: 1, black handled knife with sheath: 1, man wearing coat figurine: 1, figurine: 1, outerwear: 1, formal wear: 1, gentleman: 1, toy: 1, statue: 1, neck: 1, art: 1, jar: 1, pottery: 1, vase: 1, appliance: 1, coat: 1, overcoat: 1, clothing: 1, apparel: 1, museum (indoor): 1, cruet (bottle): 1, bottle: 1, toby jug: 1, drinking vessel: 1, lamp: 1, bottle green color: 1, charcoal color: 1, indoor: 1, table: 1, sitting: 1, black: 1, pair: 1, clock: 1, white: 1, desk: 1, holding: 1",
		"child: 4, girl: 3, woman: 3, furniture: 3, sitting: 3, person: 3, people: 2, baby: 2, portrait: 2, seat: 2, indoors: 2, man: 2, painting: 2, reading: 2, art: 2, clothing: 2, family: 1, son: 1, three: 1, group: 1, offspring: 1, two: 1, adolescence: 1, play: 1, adult: 1, wear: 1, brown wooden framed painting of woman: 1, two children sitting on seat painting: 1, still life: 1, visual arts: 1, mother: 1, human: 1, wood: 1, couch: 1, sculpture: 1, apparel: 1, blonde: 1, teen: 1, kid: 1, female: 1, sleeping beauty: 1, big sister: 1, pieta (statue): 1, church bench: 1, bench: 1, alabaster color: 1, a little girl lying on a bed: 1, indoor: 1, little: 1, window: 1, bed: 1, small: 1, young: 1, laying: 1, book: 1, lying: 1, high: 1, cat: 1, holding: 1, train: 1, sleeping: 1",
		"painting: 3, tree: 3, art: 3, mountain: 2, water: 2, lake: 2, vehicle: 2, modern art: 2, landscape: 1, people: 1, one: 1, no person: 1, travel: 1, exploration: 1, two: 1, recreation: 1, calamity: 1, snow: 1, wood: 1, transportation system: 1, winter: 1, brown and black wooden frame: 1, green tree: 1, visual arts: 1, illustration: 1, watercolor paint: 1, rock: 1, drawing: 1, acrylic paint: 1, canvas: 1, cushion: 1, pillow: 1, oil paint: 1, paint: 1, sailboard: 1, boat: 1, watercraft: 1, craft: 1, beach: 1, nature: 1, golden gate bridge: 1, bridge: 1, mechanism: 1, shore: 1, reddish brown color: 1, a tree next to a body of water: 1, sitting: 1, looking: 1, body: 1, view: 1, river: 1, covered: 1, large: 1, bird: 1, table: 1, standing: 1, bed: 1, ocean: 1",
		"tree: 4, nature: 3, grass: 3, green: 3, plant: 3, art: 2, pattern: 2, outdoors: 2, forest: 2, no person: 1, desktop: 1, retro: 1, vintage: 1, texture: 1, illustration: 1, paper: 1, wood: 1, panoramic: 1, design: 1, old: 1, wallpaper: 1, background: 1, artistic: 1, blue and green abstract painting: 1, green mountain scenery: 1, leaf: 1, painting: 1, rectangle: 1, vegetation: 1, rug: 1, land: 1, bush: 1, woodland: 1, cliff: 1, lake (natural): 1, rainforest: 1, olive green color: 1, greenishness color: 1, a close up of a green field: 1, water: 1, door: 1, field: 1, boat: 1, standing: 1, man: 1",
		"building: 5, room: 4, art: 2, old: 2, window: 2, indoors: 2, abandoned: 1, no person: 1, decay: 1, tunnel: 1, light: 1, architecture: 1, creepy: 1, wood: 1, vintage: 1, house: 1, ghost: 1, derelict: 1, dark: 1, broken: 1, painting: 1, black and brown wooden cabinet: 1, moss train interior: 1, tree: 1, forest: 1, water: 1, waterfront: 1, dock: 1, pier: 1, port: 1, outdoors: 1, nature: 1, bunker: 1, photo with bars: 1, institution: 1, vivarium (for plants): 1, enclosure: 1, partition: 1, sea green color: 1, olive green color: 1, a glass door: 1, indoor: 1, green: 1, door: 1, sitting: 1, small: 1, area: 1, view: 1, open: 1, dirty: 1, public: 1, bus: 1, train: 1, glass: 1, bench: 1, street: 1, field: 1, covered: 1, white: 1, dirt: 1, rain: 1",
		"art: 3, sculpture: 3, statue: 3, man: 3, marble: 2, person: 2, religion: 1, god: 1, old: 1, church: 1, people: 1, priest: 1, portrait: 1, sacred: 1, spirituality: 1, cross: 1, culture: 1, holy: 1, classic: 1, ancient: 1, worship: 1, white ceramic woman holding sword figurine: 1, pope john paul head bust: 1, classical sculpture: 1, forehead: 1, nonbuilding structure: 1, stone carving: 1, human: 1, ivory: 1, socle: 1, support: 1, supporting structure: 1, religion related: 1, patriarch: 1, museum (indoor): 1, clothing: 1, alabaster color: 1, a statue of a person: 1, sitting: 1, standing: 1, looking: 1, white: 1, holding: 1, front: 1, black: 1, large: 1, table: 1, shirt: 1, yellow: 1, room: 1, clock: 1, phone: 1",
		"painting: 3, art: 3, people: 2, woman: 2, man: 2, picture frame: 2, window: 2, mary: 1, religion: 1, wear: 1, two: 1, aura: 1, veil: 1, baby: 1, church: 1, adult: 1, gown (clothing): 1, renaissance: 1, book series: 1, saint: 1, man in black suit painting: 1, religious painting: 1, visual arts: 1, still life: 1, artwork: 1, modern art: 1, tourist attraction: 1, person: 1, human: 1, art gallery: 1, indoors: 1, museum (indoor): 1, olive green color: 1, a group of people sitting in front of a door: 1, room: 1, sitting: 1, cat: 1, photo: 1, small: 1, door: 1, front: 1, girl: 1, box: 1, standing: 1, wooden: 1, sign: 1, holding: 1, stuffed: 1, store: 1, walking: 1, mirror: 1, bench: 1, train: 1, display: 1, bear: 1, clock: 1, white: 1, street: 1, group: 1, graffiti: 1",
		"mask: 4, art: 3, sculpture: 2, helmet: 2, metal: 2, veil: 1, one: 1, no person: 1, people: 1, metalwork: 1, wear: 1, man: 1, portrait: 1, still life: 1, face disguise: 1, adult: 1, armor: 1, jewelry: 1, ancient: 1, handmade: 1, mammal: 1, brown and black leather cowboy boots: 1, brown mask wall decor: 1, headgear: 1, bronze: 1, artifact: 1, bronze sculpture: 1, apparel: 1, clothing: 1, painting: 1, 'catchers mask': 1, face mask: 1, protective covering: 1, plate: 1, food: 1, headdress: 1, reddish brown color: 1, a close up of a piece of metal: 1, sitting: 1, piece: 1, brown: 1, table: 1, chocolate: 1, old: 1, pair: 1, close: 1, sticking: 1, white: 1, cake: 1, laying: 1",
		"vase: 3, flower: 3, still life: 2, art: 2, jug: 2, pottery: 2, painting: 2, container: 1, pot: 1, no person: 1, candle: 1, decoration: 1, indoors: 1, one: 1, flora: 1, people: 1, urn: 1, leaf: 1, flower arrangement: 1, light: 1, glass items: 1, brown and white ceramic vase: 1, flowers in vase painting: 1, still life photography: 1, artwork: 1, coal: 1, photography: 1, plant: 1, visual arts: 1, porcelain: 1, catacomb: 1, alabaster color: 1, olive green color: 1, a vase of flowers sitting in a bowl: 1, indoor: 1, sitting: 1, small: 1, table: 1, bowl: 1, white: 1, old: 1, room: 1, wooden: 1",
		"art: 3, painting: 3, illustration: 2, woman: 2, people: 2, man: 2, plate: 2, person: 2, religion: 1, print: 1, god: 1, saint: 1, renaissance: 1, adult: 1, two: 1, nymph: 1, baroque: 1, child: 1, one: 1, nude: 1, allegory: 1, spirituality: 1, brown and green ceramic decorative plate: 1, woman feeding man red fruit near trees: 1, photography: 1, stock photography: 1, tree: 1, tableware: 1, fictional character: 1, human: 1, pieta (statue): 1, porthole: 1, window: 1, framework: 1, supporting structure: 1, masterpiece: 1, oil paint: 1, paint: 1, altarpiece: 1, screen: 1, indoors: 1, utensil: 1, figure: 1, olive green color: 1, jade green color: 1, sitting: 1, photo: 1, holding: 1, old: 1, view: 1, mirror: 1, table: 1, different: 1, baby: 1, phone: 1, water: 1, group: 1, standing: 1, bear: 1, vase: 1",
		"building: 5, city: 4, architecture: 3, house: 3, campus: 3, university: 2, office: 2, urban: 2, tree: 2, facade: 2, brick: 2, headquarters: 2, grass: 2, tower: 2, modern: 1, window: 1, sky: 1, museum: 1, glass items: 1, no person: 1, business: 1, outdoors: 1, construction: 1, brown and blue concrete building: 1, blue painted building: 1, corporate headquarters: 1, office building: 1, town: 1, billboard: 1, advertisement: 1, downtown: 1, art: 1, high rise: 1, asphalt: 1, tarmac: 1, college: 1, chancellery: 1, government building: 1, clock tower: 1, steel blue color: 1, blue color: 1, a large brick building with grass in front of a house with art gallery of ontario in the background: 1, outdoor: 1, front: 1, street: 1, sign: 1, large: 1, green: 1, church: 1, old: 1, park: 1, field: 1, stop: 1, red: 1, man: 1, graffiti: 1, parked: 1, tall: 1, standing: 1, traffic: 1, clock: 1",
		"painting: 4, art: 3, illustration: 2, old: 2, modern art: 2, plant: 2, building: 2, religion: 1, church: 1, god: 1, artistic: 1, saint: 1, no person: 1, spirituality: 1, holy: 1, color: 1, coloring: 1, architecture: 1, symbol: 1, sculpture: 1, fantasy: 1, chapel: 1, visuals: 1, green and brown abstract painting: 1, white church painting: 1, visual arts: 1, watercolor paint: 1, still life: 1, artwork: 1, pothos: 1, vine: 1, oil paint: 1, paint: 1, golden pothos: 1, bottle green color: 1, a painting of a green building: 1, green: 1, colorful: 1, table: 1, sitting: 1, small: 1, train: 1, covered: 1, street: 1, painted: 1, bench: 1, bird: 1, parked: 1, room: 1, track: 1, umbrella: 1, water: 1, standing: 1, white: 1, man: 1, window: 1, clock: 1, riding: 1",
		"room: 3, art: 3, painting: 3, furniture: 3, building: 3, indoors: 2, old: 2, no person: 1, house: 1, window: 1, retro: 1, architecture: 1, mirror: 1, vintage: 1, abandoned: 1, antique: 1, seat: 1, interior design: 1, lamp: 1, family: 1, brown wooden framed wall mirror: 1, brown wooden table: 1, visual arts: 1, still life: 1, plaster: 1, paint: 1, wood: 1, plywood: 1, cradle: 1, burial chamber: 1, enclosure: 1, basement: 1, support: 1, supporting structure: 1, art studio: 1, storeroom: 1, pale yellow color: 1, alabaster color: 1, a room filled with luggage: 1, indoor: 1, sitting: 1, table: 1, luggage: 1, small: 1, filled: 1, yellow: 1, suitcase: 1, bed: 1, white: 1, living: 1, bedroom: 1, covered: 1, street: 1",
		"art: 3, painting: 3, portrait: 2, illustration: 2, man: 2, old: 2, cup: 2, food: 2, people: 1, vintage: 1, print: 1, visuals: 1, one: 1, face: 1, adult: 1, leader: 1, paper: 1, engraving: 1, antique: 1, sepia pigment: 1, artistic: 1, retro: 1, gray and black tiger print jacket: 1, man wearing jester costume painting: 1, head: 1, forehead: 1, self-portrait: 1, drawing: 1, facial hair: 1, sketch: 1, pottery: 1, glass: 1, goblet: 1, coffee cup: 1, bread: 1, furniture: 1, recess: 1, enclosure: 1, museum (indoor): 1, bell jar: 1, protective covering: 1, vault: 1, indoors: 1, science museum: 1, lp: 1, memory device: 1, musical instrument: 1, recording: 1, light brown color: 1, sitting: 1, banana: 1, front: 1, table: 1, small: 1, filled: 1, plate: 1, fruit: 1, woman: 1, cat: 1, bowl: 1, white: 1, holding: 1, red: 1",
		"art: 3, sculpture: 2, statue: 2, man: 2, person: 2, text: 2, photo: 2, nude: 1, no person: 1, woman: 1, figure: 1, one: 1, artistic: 1, renaissance: 1, sky: 1, marble: 1, classic: 1, ancient: 1, bronze: 1, baroque: 1, old: 1, travel: 1, antique: 1, man in black suit figurine: 1, cross decor: 1, religious item: 1, crucifix: 1, cross: 1, bronze sculpture: 1, symbol: 1, classical sculpture: 1, artifact: 1, painting: 1, human: 1, drawing: 1, face: 1, portrait: 1, photography: 1, skin: 1, sketch: 1, museum (indoor): 1, art gallery: 1, indoors: 1, art studio: 1, black color: 1, alabaster color: 1, a close up of a person holding a book: 1, book: 1",
		"art: 3, painting: 2, man: 2, woman: 2, sculpture: 2, crucifix: 2, people: 1, nude: 1, renaissance: 1, adult: 1, one: 1, saint: 1, baroque: 1, portrait: 1, religion: 1, veil: 1, shirtless: 1, son: 1, two: 1, facial hair: 1, wear: 1, offensive: 1, religious angel painting: 1, angel: 1, mythology: 1, lady: 1, cupid: 1, supernatural creature: 1, fictional character: 1, cg artwork: 1, visual arts: 1, cross: 1, symbol: 1, statue: 1, museum (indoor): 1, atlas: 1, support: 1, art gallery: 1, indoors: 1, sport: 1, alabaster color: 1, a person standing in a dark room: 1, indoor: 1, standing: 1, front: 1, black: 1, legs: 1, television: 1, dark: 1, cat: 1, living: 1, holding: 1, room: 1, table: 1, jumping: 1, white: 1, playing: 1",
		"art: 3, person: 3, sculpture: 2, man: 2, people: 2, face: 2, painting: 2, no person: 1, ancient: 1, one: 1, veil: 1, mask: 1, old: 1, museum: 1, travel: 1, religion: 1, traditional: 1, portrait: 1, statue: 1, antique: 1, skull: 1, artistic: 1, brown and gray ceramic figurine: 1, brown head bust decor: 1, head: 1, forehead: 1, anthropology: 1, jaw: 1, chin: 1, mouth: 1, carving: 1, human: 1, angel: 1, archangel: 1, art gallery: 1, indoors: 1, museum (indoor): 1, oil paint: 1, paint: 1, alabaster color: 1, indian red color: 1, a group of people posing for the camera: 1, indoor: 1, dog: 1, brown: 1, holding: 1, sitting: 1, small: 1, woman: 1, standing: 1, young: 1, white: 1, black: 1, laying: 1, large: 1, group: 1, playing: 1",
		"art: 3, painting: 2, sculpture: 2, man: 2, statue: 2, baroque: 1, renaissance: 1, saint: 1, people: 1, religion: 1, nude: 1, group: 1, illustration: 1, cavalry: 1, god: 1, mary: 1, baby: 1, reclining: 1, book: 1, mourn: 1, pain: 1, offensive: 1, people fighting painting: 1, mythology: 1, tapestry: 1, visual arts: 1, textile: 1, prophet: 1, middle ages: 1, history: 1, stock photography: 1, head: 1, figurine: 1, archaeology: 1, canopic jar: 1, jar: 1, pharaoh: 1, person: 1, alabaster color: 1, a statue of a person: 1, indoor: 1, table: 1, sitting: 1, piece: 1, cake: 1, brown: 1, face: 1, mug: 1, large: 1, pair: 1, black: 1, old: 1, cut: 1, holding: 1, white: 1, standing: 1",
		"people: 2, group: 2, winter: 2, snow: 2, man: 2, many: 2, painting: 2, cavalry: 1, seated: 1, recreation: 1, adult: 1, house: 1, woman: 1, no person: 1, outdoors: 1, child: 1, mammal: 1, group together: 1, travel: 1, barn: 1, tent: 1, group of people near building painting: 1, brown wooden houses: 1, christmas eve: 1, sled dog: 1, christmas: 1, art: 1, person: 1, human: 1, pieta (statue): 1, memorial: 1, tapestry: 1, fabric: 1, altarpiece: 1, screen: 1, indoors: 1, masterpiece: 1, alabaster color: 1, a group of stuffed animals on display: 1, indoor: 1, building: 1, dog: 1, bunch: 1, different: 1, room: 1, pile: 1, table: 1, filled: 1, covered: 1, display: 1, large: 1, laying: 1, lot: 1, bed: 1, white: 1, standing: 1, stuffed: 1, zebra: 1, bedroom: 1",
		"painting: 3, art: 3, building: 3, people: 2, man: 2, street: 2, group: 2, old: 2, city: 2, child: 1, illustration: 1, adult: 1, woman: 1, wear: 1, recreation: 1, travel: 1, vintage: 1, print: 1, two: 1, religion: 1, transportation system: 1, brown wooden framed painting of man riding horse: 1, people near building painting: 1, modern art: 1, visual arts: 1, picture frame: 1, artwork: 1, still life: 1, housing: 1, person: 1, human: 1, house: 1, cottage: 1, nature: 1, outdoors: 1, transportation: 1, vehicle: 1, villa: 1, mansion: 1, ski lodge: 1, hotel: 1, ski resort: 1, hotel building: 1, chestnut color: 1, azure color: 1, a group of people riding on the back of a horse drawn carriage: 1, outdoor: 1, snow: 1, horse: 1, cow: 1, walking: 1, drawn: 1, carriage: 1, covered: 1, brown: 1, riding: 1, cattle: 1, sheep: 1, herd: 1, standing: 1, large: 1, dog: 1, field: 1",
				
	]
	

	var art_raw_cats = [

		"no person:Clarifai, food:Clarifai, container:Clarifai, people:Clarifai, grow:Clarifai, one:Clarifai, jar:Clarifai, cooking:Clarifai, kitchenware:Clarifai, art:Clarifai, business:Clarifai, still life:Clarifai, man:Clarifai, retro:Clarifai, adult:Clarifai, indoors:Clarifai, woman:Clarifai, money:Clarifai, bowl:Clarifai, science:Clarifai, brown wooden framed wall decor:CloudSight, bread beside jar painting:CloudSight Hybrid, still life:Google Vision, painting:Google Vision, still life photography:Google Vision, dishware:Google Vision, plate:Google Vision, serveware:Google Vision, photography:Google Vision, artwork:Google Vision, tableware:Google Vision, dinnerware set:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, pottery:Amazon Rekognition, goblet:Amazon Rekognition, glass:Amazon Rekognition, cup:Amazon Rekognition, coffee cup:Amazon Rekognition, furniture:Amazon Rekognition, saucer:Amazon Rekognition, food:Amazon Rekognition, bread:Amazon Rekognition, alcohol:Amazon Rekognition, beer:Amazon Rekognition, beverage:Amazon Rekognition, drink:Amazon Rekognition, jug:Amazon Rekognition, bell jar:IBM Visual Recognition, protective covering:IBM Visual Recognition, lp:IBM Visual Recognition, memory device:IBM Visual Recognition, drum:IBM Visual Recognition, percussion instrument:IBM Visual Recognition, musical instrument:IBM Visual Recognition, phonograph record:IBM Visual Recognition, recording:IBM Visual Recognition, indoors:IBM Visual Recognition, light brown color:IBM Visual Recognition, reddish brown color:IBM Visual Recognition, a cup of coffee:Microsoft Computer Vision, sitting:Microsoft Computer Vision, small:Microsoft Computer Vision, old:Microsoft Computer Vision, table:Microsoft Computer Vision, brown:Microsoft Computer Vision, food:Microsoft Computer Vision, banana:Microsoft Computer Vision, man:Microsoft Computer Vision, black:Microsoft Computer Vision, cup:Microsoft Computer Vision, white:Microsoft Computer Vision, plate:Microsoft Computer Vision, holding:Microsoft Computer Vision, woman:Microsoft Computer Vision, red:Microsoft Computer Vision, cat:Microsoft Computer Vision",
		"street:Clarifai, room:Clarifai, chair:Clarifai, no person:Clarifai, furniture:Clarifai, people:Clarifai, monochrome:Clarifai, seat:Clarifai, city:Clarifai, indoors:Clarifai, window:Clarifai, desk:Clarifai, table:Clarifai, architecture:Clarifai, house:Clarifai, urban:Clarifai, family:Clarifai, business:Clarifai, art:Clarifai, office:Clarifai, black wooden framed glass panel:CloudSight, gray gang chair and graffiti wall art:CloudSight Hybrid, black:Google Vision, black-and-white:Google Vision, room:Google Vision, monochrome:Google Vision, furniture:Google Vision, interior design:Google Vision, table:Google Vision, monochrome photography:Google Vision, still life photography:Google Vision, photography:Google Vision, chair:Amazon Rekognition, furniture:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, table:Amazon Rekognition, road:Amazon Rekognition, street:Amazon Rekognition, building:Amazon Rekognition, town:Amazon Rekognition, urban:Amazon Rekognition, city:Amazon Rekognition, indoors:Amazon Rekognition, electronics:Amazon Rekognition, wall:Amazon Rekognition, leisure activities:Amazon Rekognition, alleyway:Amazon Rekognition, alley:Amazon Rekognition, alley:IBM Visual Recognition, laundry:IBM Visual Recognition, office:IBM Visual Recognition, building:IBM Visual Recognition, basement:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, indoors:IBM Visual Recognition, gray color:IBM Visual Recognition, black color:IBM Visual Recognition, a chair in a room:Microsoft Computer Vision, indoor:Microsoft Computer Vision, room:Microsoft Computer Vision, table:Microsoft Computer Vision, furniture:Microsoft Computer Vision, living:Microsoft Computer Vision, chair:Microsoft Computer Vision, window:Microsoft Computer Vision, sitting:Microsoft Computer Vision, photo:Microsoft Computer Vision, small:Microsoft Computer Vision, white:Microsoft Computer Vision, bed:Microsoft Computer Vision, desk:Microsoft Computer Vision, black:Microsoft Computer Vision, laptop:Microsoft Computer Vision, bench:Microsoft Computer Vision, computer:Microsoft Computer Vision, kitchen:Microsoft Computer Vision, old:Microsoft Computer Vision, bedroom:Microsoft Computer Vision, covered:Microsoft Computer Vision, woman:Microsoft Computer Vision, stove:Microsoft Computer Vision",
		"painting:Clarifai, art:Clarifai, illustration:Clarifai, nymph:Clarifai, woman:Clarifai, vintage:Clarifai, artistic:Clarifai, print:Clarifai, people:Clarifai, impressionism:Clarifai, retro:Clarifai, wear:Clarifai, dress:Clarifai, portrait:Clarifai, princess:Clarifai, fashion:Clarifai, canvas:Clarifai, pastel:Clarifai, fairy:Clarifai, one:Clarifai, woman in white dress painting:CloudSight, woman in white top painting:CloudSight Hybrid, painting:Google Vision, lady:Google Vision, portrait:Google Vision, art:Google Vision, watercolor paint:Google Vision, self-portrait:Google Vision, retro style:Google Vision, visual arts:Google Vision, modern art:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, portrait:Amazon Rekognition, photo:Amazon Rekognition, photography:Amazon Rekognition, face:Amazon Rekognition, apparel:Amazon Rekognition, clothing:Amazon Rekognition, person:IBM Visual Recognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, clothing:IBM Visual Recognition, headdress:IBM Visual Recognition, reddish orange color:IBM Visual Recognition, luisa casati looking at the camera:Microsoft Computer Vision, looking:Microsoft Computer Vision, wearing:Microsoft Computer Vision, front:Microsoft Computer Vision, standing:Microsoft Computer Vision, holding:Microsoft Computer Vision, old:Microsoft Computer Vision, woman:Microsoft Computer Vision, hair:Microsoft Computer Vision, glass:Microsoft Computer Vision, man:Microsoft Computer Vision, large:Microsoft Computer Vision, young:Microsoft Computer Vision, display:Microsoft Computer Vision, water:Microsoft Computer Vision",
		"wood:Clarifai, retro:Clarifai, no person:Clarifai, alphabet:Clarifai, carpentry:Clarifai, furniture:Clarifai, carve:Clarifai, writing:Clarifai, empty:Clarifai, design:Clarifai, antique:Clarifai, art:Clarifai, old:Clarifai, rustic:Clarifai, disjunct:Clarifai, dirty:Clarifai, wooden:Clarifai, hardwood:Clarifai, typeset:Clarifai, typography:Clarifai, brown wooden 2-door cabinet:CloudSight, brown furniture leg:CloudSight Hybrid, wood:Google Vision, stick:Amazon Rekognition, cane:Amazon Rekognition, tool:Amazon Rekognition, axe:Amazon Rekognition, ax head:IBM Visual Recognition, inclined plane:IBM Visual Recognition, machine:IBM Visual Recognition, mechanical device:IBM Visual Recognition, hatchet:IBM Visual Recognition, ax:IBM Visual Recognition, cutlery:IBM Visual Recognition, tool:IBM Visual Recognition, boomerang:IBM Visual Recognition, weapon:IBM Visual Recognition, tomahawk:IBM Visual Recognition, stick:IBM Visual Recognition, reddish brown color:IBM Visual Recognition, dark red color:IBM Visual Recognition, a wooden table:Microsoft Computer Vision, wooden:Microsoft Computer Vision, dark:Microsoft Computer Vision, sitting:Microsoft Computer Vision, table:Microsoft Computer Vision, mirror:Microsoft Computer Vision, standing:Microsoft Computer Vision, room:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"painting:Clarifai, art:Clarifai, illustration:Clarifai, tree:Clarifai, no person:Clarifai, religion:Clarifai, travel:Clarifai, visuals:Clarifai, cave:Clarifai, old:Clarifai, landscape:Clarifai, nature:Clarifai, color:Clarifai, wall:Clarifai, image:Clarifai, fall:Clarifai, artistic:Clarifai, wood:Clarifai, deep:Clarifai, print:Clarifai, green and brown abstract painting:CloudSight, painting of trees:CloudSight Hybrid, painting:Google Vision, art:Google Vision, modern art:Google Vision, visual arts:Google Vision, watercolor paint:Google Vision, acrylic paint:Google Vision, tree:Google Vision, landscape:Google Vision, artwork:Google Vision, formation:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, plant:Amazon Rekognition, nature:Amazon Rekognition, mural:Amazon Rekognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, indoors:IBM Visual Recognition, nature:IBM Visual Recognition, fabric:IBM Visual Recognition, olive green color:IBM Visual Recognition, greenishness color:IBM Visual Recognition, a painting of a canyon:Microsoft Computer Vision, canyon:Microsoft Computer Vision, mountain:Microsoft Computer Vision, grass:Microsoft Computer Vision, forest:Microsoft Computer Vision, old:Microsoft Computer Vision, painting:Microsoft Computer Vision, field:Microsoft Computer Vision, colorful:Microsoft Computer Vision, grazing:Microsoft Computer Vision, train:Microsoft Computer Vision",
		"art:Clarifai, painting:Clarifai, canvas:Clarifai, artistic:Clarifai, illustration:Clarifai, visuals:Clarifai, graphic:Clarifai, abstract:Clarifai, texture:Clarifai, watercolor:Clarifai, color:Clarifai, pastel:Clarifai, design:Clarifai, creativity:Clarifai, impression:Clarifai, pattern:Clarifai, water:Clarifai, paper:Clarifai, brush:Clarifai, stain:Clarifai, green and blue abstract painting:CloudSight, trees and grass painting:CloudSight Hybrid, painting:Google Vision, acrylic paint:Google Vision, art:Google Vision, water:Google Vision, watercolor paint:Google Vision, visual arts:Google Vision, wave:Google Vision, modern art:Google Vision, landscape:Google Vision, wind wave:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, nature:Amazon Rekognition, outdoors:Amazon Rekognition, animal:Amazon Rekognition, modern art:Amazon Rekognition, bird:Amazon Rekognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, encaustic paint:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, greenish blue color:IBM Visual Recognition, a painting of a waterfall:Microsoft Computer Vision, painting:Microsoft Computer Vision, mountain:Microsoft Computer Vision, bird:Microsoft Computer Vision, riding:Microsoft Computer Vision, man:Microsoft Computer Vision, water:Microsoft Computer Vision, standing:Microsoft Computer Vision, sitting:Microsoft Computer Vision, brown:Microsoft Computer Vision, large:Microsoft Computer Vision, blue:Microsoft Computer Vision, waterfall:Microsoft Computer Vision, covered:Microsoft Computer Vision, young:Microsoft Computer Vision, horse:Microsoft Computer Vision, colorful:Microsoft Computer Vision, surfing:Microsoft Computer Vision, group:Microsoft Computer Vision, field:Microsoft Computer Vision, grazing:Microsoft Computer Vision, wave:Microsoft Computer Vision, zebra:Microsoft Computer Vision, animal:Microsoft Computer Vision, white:Microsoft Computer Vision, snow:Microsoft Computer Vision, laying:Microsoft Computer Vision, herd:Microsoft Computer Vision",
		"wood:Clarifai, tree:Clarifai, leaf:Clarifai, nature:Clarifai, landscape:Clarifai, jungle:Clarifai, no person:Clarifai, mist:Clarifai, rainforest:Clarifai, dawn:Clarifai, desktop:Clarifai, color:Clarifai, fall:Clarifai, park:Clarifai, branch:Clarifai, lush:Clarifai, guidance:Clarifai, flora:Clarifai, summer:Clarifai, barbaric:Clarifai, offensive:CloudSight, green trees painting:CloudSight Hybrid, tree:Google Vision, green:Google Vision, forest:Google Vision, natural environment:Google Vision, nature:Google Vision, northern hardwood forest:Google Vision, woodland:Google Vision, old-growth forest:Google Vision, vegetation:Google Vision, tropical and subtropical coniferous forests:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, cottage:Amazon Rekognition, house:Amazon Rekognition, building:Amazon Rekognition, housing:Amazon Rekognition, plant:Amazon Rekognition, tree:Amazon Rekognition, outdoors:Amazon Rekognition, forest:IBM Visual Recognition, plant:IBM Visual Recognition, rainforest:IBM Visual Recognition, nature:IBM Visual Recognition, alpine ash:IBM Visual Recognition, eucalyptus:IBM Visual Recognition, tree:IBM Visual Recognition, new zealand beech:IBM Visual Recognition, black beech:IBM Visual Recognition, loblolly pine:IBM Visual Recognition, pine tree:IBM Visual Recognition, greenishness color:IBM Visual Recognition, a tree in a forest:Microsoft Computer Vision, grass:Microsoft Computer Vision, plant:Microsoft Computer Vision, tree:Microsoft Computer Vision, forest:Microsoft Computer Vision, green:Microsoft Computer Vision, field:Microsoft Computer Vision, wooded:Microsoft Computer Vision, area:Microsoft Computer Vision, sitting:Microsoft Computer Vision, grazing:Microsoft Computer Vision, red:Microsoft Computer Vision, black:Microsoft Computer Vision, standing:Microsoft Computer Vision, bench:Microsoft Computer Vision, large:Microsoft Computer Vision, giraffe:Microsoft Computer Vision, yellow:Microsoft Computer Vision, grassy:Microsoft Computer Vision, white:Microsoft Computer Vision, group:Microsoft Computer Vision",
		"art:Clarifai, portrait:Clarifai, one:Clarifai, no person:Clarifai, wear:Clarifai, people:Clarifai, adult:Clarifai, paper:Clarifai, vintage:Clarifai, retro:Clarifai, painting:Clarifai, woman:Clarifai, print:Clarifai, monochrome:Clarifai, snow:Clarifai, man:Clarifai, nude:Clarifai, antique:Clarifai, desktop:Clarifai, illustration:Clarifai, offensive:CloudSight, helga matura grayscale photo:CloudSight Hybrid, photograph:Google Vision, lady:Google Vision, portrait:Google Vision, photography:Google Vision, black-and-white:Google Vision, art:Google Vision, stock photography:Google Vision, drawing:Google Vision, chest:Google Vision, long hair:Google Vision, art:Amazon Rekognition, drawing:Amazon Rekognition, painting:Amazon Rekognition, face:Amazon Rekognition, sketch:Amazon Rekognition, skin:Amazon Rekognition, outdoors:Amazon Rekognition, canvas:Amazon Rekognition, photo:Amazon Rekognition, photography:Amazon Rekognition, portrait:Amazon Rekognition, nature:Amazon Rekognition, person:IBM Visual Recognition, painting:IBM Visual Recognition, passe-partout (frame):IBM Visual Recognition, framework:IBM Visual Recognition, supporting structure:IBM Visual Recognition, silverpoint:IBM Visual Recognition, black color:IBM Visual Recognition, ash grey color:IBM Visual Recognition, a waterfall in the background:Microsoft Computer Vision, photo:Microsoft Computer Vision, white:Microsoft Computer Vision, waterfall:Microsoft Computer Vision, laying:Microsoft Computer Vision, water:Microsoft Computer Vision, cat:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"people:Clarifai, painting:Clarifai, portrait:Clarifai, art:Clarifai, one:Clarifai, adult:Clarifai, wear:Clarifai, woman:Clarifai, print:Clarifai, illustration:Clarifai, coat:Clarifai, veil:Clarifai, outerwear:Clarifai, vintage:Clarifai, lid:Clarifai, retro:Clarifai, man:Clarifai, model:Clarifai, girl:Clarifai, music:Clarifai, black and yellow long sleeve shirt:CloudSight, woman wearing black dress holding drinking glass painting:CloudSight Hybrid, painting:Google Vision, art:Google Vision, portrait:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, apparel:Amazon Rekognition, clothing:Amazon Rekognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, person:IBM Visual Recognition, clothing:IBM Visual Recognition, fish:IBM Visual Recognition, bottle green color:IBM Visual Recognition, a man standing in front of a door:Microsoft Computer Vision, man:Microsoft Computer Vision, standing:Microsoft Computer Vision, person:Microsoft Computer Vision, holding:Microsoft Computer Vision, front:Microsoft Computer Vision, black:Microsoft Computer Vision, walking:Microsoft Computer Vision, wearing:Microsoft Computer Vision, young:Microsoft Computer Vision, street:Microsoft Computer Vision, door:Microsoft Computer Vision, boy:Microsoft Computer Vision, large:Microsoft Computer Vision, suit:Microsoft Computer Vision, riding:Microsoft Computer Vision, water:Microsoft Computer Vision, rain:Microsoft Computer Vision, old:Microsoft Computer Vision, umbrella:Microsoft Computer Vision, board:Microsoft Computer Vision, night:Microsoft Computer Vision, white:Microsoft Computer Vision, room:Microsoft Computer Vision",
		"no person:Clarifai, one:Clarifai, wear:Clarifai, isolated:Clarifai, fashion:Clarifai, man:Clarifai, figure:Clarifai, steel:Clarifai, sculpture:Clarifai, woman:Clarifai, cutout:Clarifai, leather:Clarifai, adult:Clarifai, indoors:Clarifai, people:Clarifai, retro:Clarifai, military:Clarifai, contemporary:Clarifai, chrome:Clarifai, glazed:Clarifai, black handled knife with sheath:CloudSight, man wearing coat figurine:CloudSight Hybrid, figurine:Google Vision, standing:Google Vision, sculpture:Google Vision, outerwear:Google Vision, formal wear:Google Vision, gentleman:Google Vision, toy:Google Vision, statue:Google Vision, neck:Google Vision, art:Google Vision, jar:Amazon Rekognition, pottery:Amazon Rekognition, vase:Amazon Rekognition, appliance:Amazon Rekognition, coat:Amazon Rekognition, overcoat:Amazon Rekognition, clothing:Amazon Rekognition, apparel:Amazon Rekognition, museum (indoor):IBM Visual Recognition, cruet (bottle):IBM Visual Recognition, bottle:IBM Visual Recognition, toby jug:IBM Visual Recognition, drinking vessel:IBM Visual Recognition, lamp:IBM Visual Recognition, bottle green color:IBM Visual Recognition, charcoal color:IBM Visual Recognition, indoor:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, black:Microsoft Computer Vision, pair:Microsoft Computer Vision, clock:Microsoft Computer Vision, white:Microsoft Computer Vision, desk:Microsoft Computer Vision, holding:Microsoft Computer Vision, standing:Microsoft Computer Vision",
		"child:Clarifai, people:Clarifai, girl:Clarifai, family:Clarifai, son:Clarifai, baby:Clarifai, woman:Clarifai, portrait:Clarifai, seat:Clarifai, three:Clarifai, group:Clarifai, offspring:Clarifai, furniture:Clarifai, two:Clarifai, adolescence:Clarifai, play:Clarifai, adult:Clarifai, indoors:Clarifai, wear:Clarifai, man:Clarifai, brown wooden framed painting of woman:CloudSight, two children sitting on seat painting:CloudSight Hybrid, painting:Google Vision, child:Google Vision, reading:Google Vision, art:Google Vision, portrait:Google Vision, still life:Google Vision, visual arts:Google Vision, sitting:Google Vision, mother:Google Vision, human:Amazon Rekognition, person:Amazon Rekognition, art:Amazon Rekognition, painting:Amazon Rekognition, furniture:Amazon Rekognition, wood:Amazon Rekognition, couch:Amazon Rekognition, reading:Amazon Rekognition, sculpture:Amazon Rekognition, clothing:Amazon Rekognition, apparel:Amazon Rekognition, blonde:Amazon Rekognition, woman:Amazon Rekognition, girl:Amazon Rekognition, teen:Amazon Rekognition, child:Amazon Rekognition, kid:Amazon Rekognition, female:Amazon Rekognition, sitting:Amazon Rekognition, sleeping beauty:IBM Visual Recognition, person:IBM Visual Recognition, big sister:IBM Visual Recognition, pieta (statue):IBM Visual Recognition, church bench:IBM Visual Recognition, bench:IBM Visual Recognition, seat:IBM Visual Recognition, furniture:IBM Visual Recognition, people:IBM Visual Recognition, indoors:IBM Visual Recognition, clothing:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a little girl lying on a bed:Microsoft Computer Vision, indoor:Microsoft Computer Vision, girl:Microsoft Computer Vision, person:Microsoft Computer Vision, child:Microsoft Computer Vision, little:Microsoft Computer Vision, window:Microsoft Computer Vision, sitting:Microsoft Computer Vision, bed:Microsoft Computer Vision, small:Microsoft Computer Vision, young:Microsoft Computer Vision, laying:Microsoft Computer Vision, book:Microsoft Computer Vision, lying:Microsoft Computer Vision, baby:Microsoft Computer Vision, high:Microsoft Computer Vision, woman:Microsoft Computer Vision, cat:Microsoft Computer Vision, holding:Microsoft Computer Vision, train:Microsoft Computer Vision, sleeping:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"landscape:Clarifai, people:Clarifai, painting:Clarifai, one:Clarifai, no person:Clarifai, tree:Clarifai, mountain:Clarifai, water:Clarifai, travel:Clarifai, art:Clarifai, exploration:Clarifai, lake:Clarifai, two:Clarifai, recreation:Clarifai, calamity:Clarifai, snow:Clarifai, wood:Clarifai, transportation system:Clarifai, winter:Clarifai, vehicle:Clarifai, brown and black wooden frame:CloudSight, green tree:CloudSight Hybrid, art:Google Vision, painting:Google Vision, visual arts:Google Vision, illustration:Google Vision, modern art:Google Vision, watercolor paint:Google Vision, tree:Google Vision, rock:Google Vision, drawing:Google Vision, acrylic paint:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, canvas:Amazon Rekognition, modern art:Amazon Rekognition, cushion:Amazon Rekognition, pillow:Amazon Rekognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, sailboard:IBM Visual Recognition, boat:IBM Visual Recognition, watercraft:IBM Visual Recognition, craft:IBM Visual Recognition, vehicle:IBM Visual Recognition, beach:IBM Visual Recognition, nature:IBM Visual Recognition, golden gate bridge:IBM Visual Recognition, bridge:IBM Visual Recognition, mechanism:IBM Visual Recognition, shore:IBM Visual Recognition, reddish brown color:IBM Visual Recognition, a tree next to a body of water:Microsoft Computer Vision, water:Microsoft Computer Vision, mountain:Microsoft Computer Vision, tree:Microsoft Computer Vision, sitting:Microsoft Computer Vision, looking:Microsoft Computer Vision, body:Microsoft Computer Vision, view:Microsoft Computer Vision, river:Microsoft Computer Vision, covered:Microsoft Computer Vision, lake:Microsoft Computer Vision, large:Microsoft Computer Vision, bird:Microsoft Computer Vision, table:Microsoft Computer Vision, standing:Microsoft Computer Vision, bed:Microsoft Computer Vision, ocean:Microsoft Computer Vision",
		"no person:Clarifai, desktop:Clarifai, retro:Clarifai, nature:Clarifai, vintage:Clarifai, texture:Clarifai, illustration:Clarifai, paper:Clarifai, wood:Clarifai, panoramic:Clarifai, art:Clarifai, pattern:Clarifai, grass:Clarifai, design:Clarifai, tree:Clarifai, old:Clarifai, wallpaper:Clarifai, outdoors:Clarifai, background:Clarifai, artistic:Clarifai, blue and green abstract painting:CloudSight, green mountain scenery:CloudSight Hybrid, green:Google Vision, grass:Google Vision, leaf:Google Vision, tree:Google Vision, painting:Google Vision, pattern:Google Vision, plant:Google Vision, rectangle:Google Vision, art:Google Vision, plant:Amazon Rekognition, vegetation:Amazon Rekognition, rug:Amazon Rekognition, grass:Amazon Rekognition, land:Amazon Rekognition, outdoors:Amazon Rekognition, nature:Amazon Rekognition, bush:Amazon Rekognition, tree:Amazon Rekognition, green:Amazon Rekognition, woodland:Amazon Rekognition, forest:Amazon Rekognition, forest:IBM Visual Recognition, plant:IBM Visual Recognition, cliff:IBM Visual Recognition, nature:IBM Visual Recognition, lake (natural):IBM Visual Recognition, rainforest:IBM Visual Recognition, tree:IBM Visual Recognition, olive green color:IBM Visual Recognition, greenishness color:IBM Visual Recognition, a close up of a green field:Microsoft Computer Vision, green:Microsoft Computer Vision, water:Microsoft Computer Vision, door:Microsoft Computer Vision, field:Microsoft Computer Vision, boat:Microsoft Computer Vision, standing:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"abandoned:Clarifai, no person:Clarifai, decay:Clarifai, art:Clarifai, tunnel:Clarifai, light:Clarifai, architecture:Clarifai, old:Clarifai, creepy:Clarifai, wood:Clarifai, building:Clarifai, vintage:Clarifai, house:Clarifai, window:Clarifai, ghost:Clarifai, derelict:Clarifai, room:Clarifai, dark:Clarifai, broken:Clarifai, painting:Clarifai, black and brown wooden cabinet:CloudSight, moss train interior:CloudSight Hybrid, tree:Google Vision, room:Google Vision, forest:Google Vision, building:Google Vision, art:Google Vision, water:Amazon Rekognition, room:Amazon Rekognition, indoors:Amazon Rekognition, waterfront:Amazon Rekognition, dock:Amazon Rekognition, pier:Amazon Rekognition, port:Amazon Rekognition, outdoors:Amazon Rekognition, nature:Amazon Rekognition, building:Amazon Rekognition, bunker:IBM Visual Recognition, photo with bars:IBM Visual Recognition, institution:IBM Visual Recognition, building:IBM Visual Recognition, vivarium (for plants):IBM Visual Recognition, enclosure:IBM Visual Recognition, partition:IBM Visual Recognition, indoors:IBM Visual Recognition, sea green color:IBM Visual Recognition, olive green color:IBM Visual Recognition, a glass door:Microsoft Computer Vision, indoor:Microsoft Computer Vision, building:Microsoft Computer Vision, window:Microsoft Computer Vision, green:Microsoft Computer Vision, old:Microsoft Computer Vision, door:Microsoft Computer Vision, sitting:Microsoft Computer Vision, room:Microsoft Computer Vision, small:Microsoft Computer Vision, area:Microsoft Computer Vision, view:Microsoft Computer Vision, open:Microsoft Computer Vision, dirty:Microsoft Computer Vision, public:Microsoft Computer Vision, bus:Microsoft Computer Vision, train:Microsoft Computer Vision, glass:Microsoft Computer Vision, bench:Microsoft Computer Vision, street:Microsoft Computer Vision, field:Microsoft Computer Vision, covered:Microsoft Computer Vision, white:Microsoft Computer Vision, dirt:Microsoft Computer Vision, rain:Microsoft Computer Vision",
		"art:Clarifai, sculpture:Clarifai, statue:Clarifai, religion:Clarifai, god:Clarifai, man:Clarifai, old:Clarifai, church:Clarifai, people:Clarifai, priest:Clarifai, portrait:Clarifai, sacred:Clarifai, spirituality:Clarifai, cross:Clarifai, culture:Clarifai, holy:Clarifai, classic:Clarifai, marble:Clarifai, ancient:Clarifai, worship:Clarifai, white ceramic woman holding sword figurine:CloudSight, pope john paul head bust:CloudSight Hybrid, sculpture:Google Vision, art:Google Vision, classical sculpture:Google Vision, forehead:Google Vision, statue:Google Vision, nonbuilding structure:Google Vision, stone carving:Google Vision, marble:Google Vision, art:Amazon Rekognition, statue:Amazon Rekognition, sculpture:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, ivory:Amazon Rekognition, socle:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, religion related:IBM Visual Recognition, patriarch:IBM Visual Recognition, person:IBM Visual Recognition, man:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, clothing:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a statue of a person:Microsoft Computer Vision, sitting:Microsoft Computer Vision, standing:Microsoft Computer Vision, man:Microsoft Computer Vision, looking:Microsoft Computer Vision, white:Microsoft Computer Vision, holding:Microsoft Computer Vision, front:Microsoft Computer Vision, black:Microsoft Computer Vision, large:Microsoft Computer Vision, table:Microsoft Computer Vision, shirt:Microsoft Computer Vision, yellow:Microsoft Computer Vision, room:Microsoft Computer Vision, clock:Microsoft Computer Vision, phone:Microsoft Computer Vision",
		"painting:Clarifai, art:Clarifai, people:Clarifai, woman:Clarifai, mary:Clarifai, religion:Clarifai, wear:Clarifai, two:Clarifai, man:Clarifai, aura:Clarifai, veil:Clarifai, baby:Clarifai, church:Clarifai, adult:Clarifai, gown (clothing):Clarifai, renaissance:Clarifai, picture frame:Clarifai, window:Clarifai, book series:Clarifai, saint:Clarifai, man in black suit painting:CloudSight, religious painting:CloudSight Hybrid, painting:Google Vision, picture frame:Google Vision, art:Google Vision, visual arts:Google Vision, still life:Google Vision, artwork:Google Vision, modern art:Google Vision, tourist attraction:Google Vision, person:Amazon Rekognition, human:Amazon Rekognition, art:Amazon Rekognition, painting:Amazon Rekognition, art gallery:IBM Visual Recognition, indoors:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, olive green color:IBM Visual Recognition, a group of people sitting in front of a door:Microsoft Computer Vision, room:Microsoft Computer Vision, sitting:Microsoft Computer Vision, cat:Microsoft Computer Vision, window:Microsoft Computer Vision, photo:Microsoft Computer Vision, small:Microsoft Computer Vision, door:Microsoft Computer Vision, front:Microsoft Computer Vision, woman:Microsoft Computer Vision, girl:Microsoft Computer Vision, box:Microsoft Computer Vision, standing:Microsoft Computer Vision, wooden:Microsoft Computer Vision, sign:Microsoft Computer Vision, man:Microsoft Computer Vision, holding:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, store:Microsoft Computer Vision, walking:Microsoft Computer Vision, mirror:Microsoft Computer Vision, bench:Microsoft Computer Vision, train:Microsoft Computer Vision, display:Microsoft Computer Vision, bear:Microsoft Computer Vision, clock:Microsoft Computer Vision, white:Microsoft Computer Vision, people:Microsoft Computer Vision, street:Microsoft Computer Vision, group:Microsoft Computer Vision, graffiti:Microsoft Computer Vision",
		"sculpture:Clarifai, veil:Clarifai, one:Clarifai, no person:Clarifai, people:Clarifai, metalwork:Clarifai, wear:Clarifai, mask:Clarifai, art:Clarifai, man:Clarifai, portrait:Clarifai, still life:Clarifai, face disguise:Clarifai, helmet:Clarifai, adult:Clarifai, armor:Clarifai, jewelry:Clarifai, ancient:Clarifai, handmade:Clarifai, mammal:Clarifai, brown and black leather cowboy boots:CloudSight, brown mask wall decor:CloudSight Hybrid, sculpture:Google Vision, headgear:Google Vision, mask:Google Vision, bronze:Google Vision, artifact:Google Vision, bronze sculpture:Google Vision, metal:Google Vision, art:Google Vision, helmet:Amazon Rekognition, apparel:Amazon Rekognition, clothing:Amazon Rekognition, mask:Amazon Rekognition, art:Amazon Rekognition, painting:Amazon Rekognition, mask:IBM Visual Recognition, 'catchers mask':IBM Visual Recognition, face mask:IBM Visual Recognition, protective covering:IBM Visual Recognition, plate:IBM Visual Recognition, food:IBM Visual Recognition, headdress:IBM Visual Recognition, reddish brown color:IBM Visual Recognition, a close up of a piece of metal:Microsoft Computer Vision, sitting:Microsoft Computer Vision, piece:Microsoft Computer Vision, brown:Microsoft Computer Vision, table:Microsoft Computer Vision, metal:Microsoft Computer Vision, chocolate:Microsoft Computer Vision, old:Microsoft Computer Vision, pair:Microsoft Computer Vision, close:Microsoft Computer Vision, sticking:Microsoft Computer Vision, white:Microsoft Computer Vision, cake:Microsoft Computer Vision, laying:Microsoft Computer Vision",
		"vase:Clarifai, flower:Clarifai, still life:Clarifai, container:Clarifai, pot:Clarifai, no person:Clarifai, candle:Clarifai, art:Clarifai, decoration:Clarifai, indoors:Clarifai, one:Clarifai, jug:Clarifai, flora:Clarifai, pottery:Clarifai, people:Clarifai, urn:Clarifai, leaf:Clarifai, flower arrangement:Clarifai, light:Clarifai, glass items:Clarifai, brown and white ceramic vase:CloudSight, flowers in vase painting:CloudSight Hybrid, still life:Google Vision, painting:Google Vision, still life photography:Google Vision, flower:Google Vision, artwork:Google Vision, coal:Google Vision, photography:Google Vision, plant:Google Vision, vase:Google Vision, visual arts:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, porcelain:Amazon Rekognition, pottery:Amazon Rekognition, jug:Amazon Rekognition, catacomb:IBM Visual Recognition, alabaster color:IBM Visual Recognition, olive green color:IBM Visual Recognition, a vase of flowers sitting in a bowl:Microsoft Computer Vision, indoor:Microsoft Computer Vision, sitting:Microsoft Computer Vision, small:Microsoft Computer Vision, flower:Microsoft Computer Vision, table:Microsoft Computer Vision, bowl:Microsoft Computer Vision, vase:Microsoft Computer Vision, white:Microsoft Computer Vision, old:Microsoft Computer Vision, room:Microsoft Computer Vision, wooden:Microsoft Computer Vision",
		"illustration:Clarifai, art:Clarifai, woman:Clarifai, people:Clarifai, man:Clarifai, religion:Clarifai, painting:Clarifai, print:Clarifai, god:Clarifai, saint:Clarifai, renaissance:Clarifai, adult:Clarifai, two:Clarifai, nymph:Clarifai, baroque:Clarifai, child:Clarifai, one:Clarifai, nude:Clarifai, allegory:Clarifai, spirituality:Clarifai, brown and green ceramic decorative plate:CloudSight, woman feeding man red fruit near trees:CloudSight Hybrid, painting:Google Vision, photography:Google Vision, stock photography:Google Vision, art:Google Vision, tree:Google Vision, tableware:Google Vision, illustration:Google Vision, fictional character:Google Vision, plate:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, pieta (statue):IBM Visual Recognition, porthole:IBM Visual Recognition, window:IBM Visual Recognition, framework:IBM Visual Recognition, supporting structure:IBM Visual Recognition, masterpiece:IBM Visual Recognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, altarpiece:IBM Visual Recognition, screen:IBM Visual Recognition, indoors:IBM Visual Recognition, utensil:IBM Visual Recognition, figure:IBM Visual Recognition, olive green color:IBM Visual Recognition, jade green color:IBM Visual Recognition, person:Microsoft Computer Vision, sitting:Microsoft Computer Vision, photo:Microsoft Computer Vision, man:Microsoft Computer Vision, holding:Microsoft Computer Vision, woman:Microsoft Computer Vision, old:Microsoft Computer Vision, view:Microsoft Computer Vision, mirror:Microsoft Computer Vision, table:Microsoft Computer Vision, people:Microsoft Computer Vision, different:Microsoft Computer Vision, baby:Microsoft Computer Vision, phone:Microsoft Computer Vision, water:Microsoft Computer Vision, group:Microsoft Computer Vision, standing:Microsoft Computer Vision, plate:Microsoft Computer Vision, bear:Microsoft Computer Vision, vase:Microsoft Computer Vision",
		"architecture:Clarifai, building:Clarifai, university:Clarifai, modern:Clarifai, city:Clarifai, house:Clarifai, window:Clarifai, sky:Clarifai, museum:Clarifai, glass items:Clarifai, office:Clarifai, no person:Clarifai, urban:Clarifai, business:Clarifai, campus:Clarifai, outdoors:Clarifai, construction:Clarifai, tree:Clarifai, facade:Clarifai, brick:Clarifai, brown and blue concrete building:CloudSight, blue painted building:CloudSight Hybrid, architecture:Google Vision, building:Google Vision, house:Google Vision, tree:Google Vision, campus:Google Vision, headquarters:Google Vision, corporate headquarters:Google Vision, grass:Google Vision, facade:Google Vision, city:Google Vision, office building:Amazon Rekognition, building:Amazon Rekognition, urban:Amazon Rekognition, town:Amazon Rekognition, city:Amazon Rekognition, architecture:Amazon Rekognition, billboard:Amazon Rekognition, advertisement:Amazon Rekognition, campus:Amazon Rekognition, downtown:Amazon Rekognition, art:Amazon Rekognition, high rise:Amazon Rekognition, asphalt:Amazon Rekognition, tarmac:Amazon Rekognition, college:IBM Visual Recognition, chancellery:IBM Visual Recognition, government building:IBM Visual Recognition, building:IBM Visual Recognition, headquarters:IBM Visual Recognition, office:IBM Visual Recognition, university:IBM Visual Recognition, clock tower:IBM Visual Recognition, tower:IBM Visual Recognition, steel blue color:IBM Visual Recognition, blue color:IBM Visual Recognition, a large brick building with grass in front of a house with art gallery of ontario in the background:Microsoft Computer Vision, grass:Microsoft Computer Vision, building:Microsoft Computer Vision, outdoor:Microsoft Computer Vision, house:Microsoft Computer Vision, front:Microsoft Computer Vision, brick:Microsoft Computer Vision, street:Microsoft Computer Vision, sign:Microsoft Computer Vision, large:Microsoft Computer Vision, green:Microsoft Computer Vision, church:Microsoft Computer Vision, old:Microsoft Computer Vision, park:Microsoft Computer Vision, city:Microsoft Computer Vision, field:Microsoft Computer Vision, stop:Microsoft Computer Vision, red:Microsoft Computer Vision, man:Microsoft Computer Vision, graffiti:Microsoft Computer Vision, tower:Microsoft Computer Vision, parked:Microsoft Computer Vision, tall:Microsoft Computer Vision, standing:Microsoft Computer Vision, traffic:Microsoft Computer Vision, clock:Microsoft Computer Vision",
		"art:Clarifai, religion:Clarifai, painting:Clarifai, church:Clarifai, illustration:Clarifai, god:Clarifai, artistic:Clarifai, saint:Clarifai, no person:Clarifai, old:Clarifai, spirituality:Clarifai, holy:Clarifai, color:Clarifai, coloring:Clarifai, architecture:Clarifai, symbol:Clarifai, sculpture:Clarifai, fantasy:Clarifai, chapel:Clarifai, visuals:Clarifai, green and brown abstract painting:CloudSight, white church painting:CloudSight Hybrid, painting:Google Vision, art:Google Vision, visual arts:Google Vision, modern art:Google Vision, watercolor paint:Google Vision, still life:Google Vision, plant:Google Vision, illustration:Google Vision, artwork:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, modern art:Amazon Rekognition, pothos:IBM Visual Recognition, vine:IBM Visual Recognition, plant:IBM Visual Recognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, golden pothos:IBM Visual Recognition, building:IBM Visual Recognition, bottle green color:IBM Visual Recognition, a painting of a green building:Microsoft Computer Vision, green:Microsoft Computer Vision, building:Microsoft Computer Vision, colorful:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, small:Microsoft Computer Vision, train:Microsoft Computer Vision, old:Microsoft Computer Vision, painting:Microsoft Computer Vision, covered:Microsoft Computer Vision, street:Microsoft Computer Vision, painted:Microsoft Computer Vision, bench:Microsoft Computer Vision, bird:Microsoft Computer Vision, parked:Microsoft Computer Vision, room:Microsoft Computer Vision, track:Microsoft Computer Vision, umbrella:Microsoft Computer Vision, water:Microsoft Computer Vision, standing:Microsoft Computer Vision, white:Microsoft Computer Vision, man:Microsoft Computer Vision, window:Microsoft Computer Vision, clock:Microsoft Computer Vision, riding:Microsoft Computer Vision",
		"room:Clarifai, art:Clarifai, painting:Clarifai, indoors:Clarifai, furniture:Clarifai, no person:Clarifai, house:Clarifai, window:Clarifai, old:Clarifai, retro:Clarifai, architecture:Clarifai, mirror:Clarifai, vintage:Clarifai, building:Clarifai, abandoned:Clarifai, antique:Clarifai, seat:Clarifai, interior design:Clarifai, lamp:Clarifai, family:Clarifai, brown wooden framed wall mirror:CloudSight, brown wooden table:CloudSight Hybrid, painting:Google Vision, room:Google Vision, visual arts:Google Vision, still life:Google Vision, art:Google Vision, plaster:Google Vision, furniture:Google Vision, paint:Google Vision, furniture:Amazon Rekognition, painting:Amazon Rekognition, art:Amazon Rekognition, wood:Amazon Rekognition, plywood:Amazon Rekognition, cradle:Amazon Rekognition, burial chamber:IBM Visual Recognition, enclosure:IBM Visual Recognition, basement:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, art studio:IBM Visual Recognition, indoors:IBM Visual Recognition, storeroom:IBM Visual Recognition, building:IBM Visual Recognition, pale yellow color:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a room filled with luggage:Microsoft Computer Vision, indoor:Microsoft Computer Vision, building:Microsoft Computer Vision, sitting:Microsoft Computer Vision, room:Microsoft Computer Vision, old:Microsoft Computer Vision, table:Microsoft Computer Vision, luggage:Microsoft Computer Vision, small:Microsoft Computer Vision, filled:Microsoft Computer Vision, yellow:Microsoft Computer Vision, suitcase:Microsoft Computer Vision, bed:Microsoft Computer Vision, white:Microsoft Computer Vision, living:Microsoft Computer Vision, bedroom:Microsoft Computer Vision, covered:Microsoft Computer Vision, street:Microsoft Computer Vision",
		"portrait:Clarifai, art:Clarifai, illustration:Clarifai, people:Clarifai, man:Clarifai, vintage:Clarifai, painting:Clarifai, old:Clarifai, print:Clarifai, visuals:Clarifai, one:Clarifai, face:Clarifai, adult:Clarifai, leader:Clarifai, paper:Clarifai, engraving:Clarifai, antique:Clarifai, sepia pigment:Clarifai, artistic:Clarifai, retro:Clarifai, gray and black tiger print jacket:CloudSight, man wearing jester costume painting:CloudSight Hybrid, head:Google Vision, illustration:Google Vision, forehead:Google Vision, self-portrait:Google Vision, art:Google Vision, drawing:Google Vision, portrait:Google Vision, facial hair:Google Vision, painting:Google Vision, sketch:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, pottery:Amazon Rekognition, glass:Amazon Rekognition, goblet:Amazon Rekognition, cup:Amazon Rekognition, coffee cup:Amazon Rekognition, bread:Amazon Rekognition, food:Amazon Rekognition, furniture:Amazon Rekognition, recess:IBM Visual Recognition, enclosure:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, bell jar:IBM Visual Recognition, protective covering:IBM Visual Recognition, vault:IBM Visual Recognition, indoors:IBM Visual Recognition, science museum:IBM Visual Recognition, lp:IBM Visual Recognition, memory device:IBM Visual Recognition, musical instrument:IBM Visual Recognition, recording:IBM Visual Recognition, light brown color:IBM Visual Recognition, sitting:Microsoft Computer Vision, banana:Microsoft Computer Vision, front:Microsoft Computer Vision, table:Microsoft Computer Vision, small:Microsoft Computer Vision, old:Microsoft Computer Vision, filled:Microsoft Computer Vision, food:Microsoft Computer Vision, plate:Microsoft Computer Vision, fruit:Microsoft Computer Vision, man:Microsoft Computer Vision, woman:Microsoft Computer Vision, cat:Microsoft Computer Vision, bowl:Microsoft Computer Vision, white:Microsoft Computer Vision, holding:Microsoft Computer Vision, red:Microsoft Computer Vision, cup:Microsoft Computer Vision",
		"art:Clarifai, nude:Clarifai, sculpture:Clarifai, no person:Clarifai, woman:Clarifai, statue:Clarifai, figure:Clarifai, one:Clarifai, artistic:Clarifai, renaissance:Clarifai, sky:Clarifai, man:Clarifai, marble:Clarifai, classic:Clarifai, ancient:Clarifai, bronze:Clarifai, baroque:Clarifai, old:Clarifai, travel:Clarifai, antique:Clarifai, man in black suit figurine:CloudSight, cross decor:CloudSight Hybrid, religious item:Google Vision, sculpture:Google Vision, crucifix:Google Vision, statue:Google Vision, cross:Google Vision, bronze sculpture:Google Vision, symbol:Google Vision, art:Google Vision, classical sculpture:Google Vision, artifact:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, drawing:Amazon Rekognition, face:Amazon Rekognition, text:Amazon Rekognition, photo:Amazon Rekognition, portrait:Amazon Rekognition, photography:Amazon Rekognition, skin:Amazon Rekognition, sketch:Amazon Rekognition, person:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, art gallery:IBM Visual Recognition, indoors:IBM Visual Recognition, art studio:IBM Visual Recognition, black color:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a close up of a person holding a book:Microsoft Computer Vision, text:Microsoft Computer Vision, book:Microsoft Computer Vision, photo:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"art:Clarifai, people:Clarifai, painting:Clarifai, nude:Clarifai, renaissance:Clarifai, adult:Clarifai, man:Clarifai, one:Clarifai, saint:Clarifai, woman:Clarifai, baroque:Clarifai, portrait:Clarifai, sculpture:Clarifai, religion:Clarifai, veil:Clarifai, shirtless:Clarifai, son:Clarifai, two:Clarifai, facial hair:Clarifai, wear:Clarifai, offensive:CloudSight, religious angel painting:CloudSight Hybrid, painting:Google Vision, angel:Google Vision, mythology:Google Vision, lady:Google Vision, cupid:Google Vision, supernatural creature:Google Vision, art:Google Vision, fictional character:Google Vision, cg artwork:Google Vision, visual arts:Google Vision, cross:Amazon Rekognition, symbol:Amazon Rekognition, crucifix:Amazon Rekognition, art:Amazon Rekognition, sculpture:Amazon Rekognition, statue:Amazon Rekognition, museum (indoor):IBM Visual Recognition, crucifix:IBM Visual Recognition, atlas:IBM Visual Recognition, support:IBM Visual Recognition, art gallery:IBM Visual Recognition, indoors:IBM Visual Recognition, sport:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a person standing in a dark room:Microsoft Computer Vision, indoor:Microsoft Computer Vision, standing:Microsoft Computer Vision, front:Microsoft Computer Vision, black:Microsoft Computer Vision, legs:Microsoft Computer Vision, television:Microsoft Computer Vision, dark:Microsoft Computer Vision, man:Microsoft Computer Vision, cat:Microsoft Computer Vision, living:Microsoft Computer Vision, holding:Microsoft Computer Vision, room:Microsoft Computer Vision, table:Microsoft Computer Vision, woman:Microsoft Computer Vision, jumping:Microsoft Computer Vision, white:Microsoft Computer Vision, playing:Microsoft Computer Vision",
		"sculpture:Clarifai, no person:Clarifai, ancient:Clarifai, art:Clarifai, one:Clarifai, man:Clarifai, veil:Clarifai, mask:Clarifai, people:Clarifai, face:Clarifai, old:Clarifai, museum:Clarifai, travel:Clarifai, religion:Clarifai, traditional:Clarifai, portrait:Clarifai, statue:Clarifai, antique:Clarifai, skull:Clarifai, artistic:Clarifai, brown and gray ceramic figurine:CloudSight, brown head bust decor:CloudSight Hybrid, face:Google Vision, head:Google Vision, forehead:Google Vision, sculpture:Google Vision, anthropology:Google Vision, jaw:Google Vision, chin:Google Vision, art:Google Vision, mouth:Google Vision, carving:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, angel:Amazon Rekognition, archangel:Amazon Rekognition, person:IBM Visual Recognition, painting:IBM Visual Recognition, art gallery:IBM Visual Recognition, indoors:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, alabaster color:IBM Visual Recognition, indian red color:IBM Visual Recognition, a group of people posing for the camera:Microsoft Computer Vision, person:Microsoft Computer Vision, indoor:Microsoft Computer Vision, man:Microsoft Computer Vision, dog:Microsoft Computer Vision, brown:Microsoft Computer Vision, holding:Microsoft Computer Vision, sitting:Microsoft Computer Vision, small:Microsoft Computer Vision, woman:Microsoft Computer Vision, standing:Microsoft Computer Vision, young:Microsoft Computer Vision, white:Microsoft Computer Vision, black:Microsoft Computer Vision, laying:Microsoft Computer Vision, people:Microsoft Computer Vision, large:Microsoft Computer Vision, group:Microsoft Computer Vision, playing:Microsoft Computer Vision",
		"art:Clarifai, baroque:Clarifai, renaissance:Clarifai, saint:Clarifai, painting:Clarifai, people:Clarifai, religion:Clarifai, nude:Clarifai, group:Clarifai, illustration:Clarifai, cavalry:Clarifai, god:Clarifai, mary:Clarifai, baby:Clarifai, reclining:Clarifai, sculpture:Clarifai, man:Clarifai, book:Clarifai, mourn:Clarifai, pain:Clarifai, offensive:CloudSight, people fighting painting:CloudSight Hybrid, painting:Google Vision, art:Google Vision, mythology:Google Vision, tapestry:Google Vision, visual arts:Google Vision, textile:Google Vision, prophet:Google Vision, middle ages:Google Vision, history:Google Vision, stock photography:Google Vision, head:Amazon Rekognition, sculpture:Amazon Rekognition, art:Amazon Rekognition, statue:Amazon Rekognition, figurine:Amazon Rekognition, archaeology:Amazon Rekognition, canopic jar:IBM Visual Recognition, jar:IBM Visual Recognition, pharaoh:IBM Visual Recognition, person:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a statue of a person:Microsoft Computer Vision, indoor:Microsoft Computer Vision, statue:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, piece:Microsoft Computer Vision, cake:Microsoft Computer Vision, brown:Microsoft Computer Vision, face:Microsoft Computer Vision, mug:Microsoft Computer Vision, large:Microsoft Computer Vision, pair:Microsoft Computer Vision, black:Microsoft Computer Vision, old:Microsoft Computer Vision, cut:Microsoft Computer Vision, holding:Microsoft Computer Vision, man:Microsoft Computer Vision, white:Microsoft Computer Vision, standing:Microsoft Computer Vision",
		"people:Clarifai, cavalry:Clarifai, group:Clarifai, winter:Clarifai, snow:Clarifai, man:Clarifai, many:Clarifai, seated:Clarifai, recreation:Clarifai, adult:Clarifai, house:Clarifai, woman:Clarifai, no person:Clarifai, outdoors:Clarifai, child:Clarifai, mammal:Clarifai, group together:Clarifai, travel:Clarifai, barn:Clarifai, tent:Clarifai, group of people near building painting:CloudSight, brown wooden houses:CloudSight Hybrid, winter:Google Vision, painting:Google Vision, snow:Google Vision, christmas eve:Google Vision, sled dog:Google Vision, christmas:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, pieta (statue):IBM Visual Recognition, memorial:IBM Visual Recognition, tapestry:IBM Visual Recognition, fabric:IBM Visual Recognition, altarpiece:IBM Visual Recognition, screen:IBM Visual Recognition, indoors:IBM Visual Recognition, masterpiece:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a group of stuffed animals on display:Microsoft Computer Vision, indoor:Microsoft Computer Vision, building:Microsoft Computer Vision, dog:Microsoft Computer Vision, bunch:Microsoft Computer Vision, different:Microsoft Computer Vision, group:Microsoft Computer Vision, room:Microsoft Computer Vision, man:Microsoft Computer Vision, many:Microsoft Computer Vision, pile:Microsoft Computer Vision, table:Microsoft Computer Vision, filled:Microsoft Computer Vision, covered:Microsoft Computer Vision, display:Microsoft Computer Vision, large:Microsoft Computer Vision, laying:Microsoft Computer Vision, lot:Microsoft Computer Vision, bed:Microsoft Computer Vision, white:Microsoft Computer Vision, standing:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, people:Microsoft Computer Vision, zebra:Microsoft Computer Vision, bedroom:Microsoft Computer Vision",
		"painting:Clarifai, people:Clarifai, art:Clarifai, child:Clarifai, man:Clarifai, illustration:Clarifai, adult:Clarifai, woman:Clarifai, wear:Clarifai, street:Clarifai, group:Clarifai, recreation:Clarifai, travel:Clarifai, vintage:Clarifai, print:Clarifai, two:Clarifai, old:Clarifai, religion:Clarifai, city:Clarifai, transportation system:Clarifai, brown wooden framed painting of man riding horse:CloudSight, people near building painting:CloudSight Hybrid, painting:Google Vision, modern art:Google Vision, art:Google Vision, visual arts:Google Vision, picture frame:Google Vision, artwork:Google Vision, still life:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, building:Amazon Rekognition, housing:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, house:Amazon Rekognition, cottage:Amazon Rekognition, nature:Amazon Rekognition, outdoors:Amazon Rekognition, transportation:Amazon Rekognition, vehicle:Amazon Rekognition, villa:Amazon Rekognition, mansion:Amazon Rekognition, ski lodge:IBM Visual Recognition, hotel:IBM Visual Recognition, building:IBM Visual Recognition, ski resort:IBM Visual Recognition, hotel building:IBM Visual Recognition, chestnut color:IBM Visual Recognition, azure color:IBM Visual Recognition, a group of people riding on the back of a horse drawn carriage:Microsoft Computer Vision, outdoor:Microsoft Computer Vision, building:Microsoft Computer Vision, snow:Microsoft Computer Vision, horse:Microsoft Computer Vision, cow:Microsoft Computer Vision, street:Microsoft Computer Vision, people:Microsoft Computer Vision, group:Microsoft Computer Vision, walking:Microsoft Computer Vision, drawn:Microsoft Computer Vision, carriage:Microsoft Computer Vision, covered:Microsoft Computer Vision, brown:Microsoft Computer Vision, riding:Microsoft Computer Vision, cattle:Microsoft Computer Vision, sheep:Microsoft Computer Vision, herd:Microsoft Computer Vision, man:Microsoft Computer Vision, old:Microsoft Computer Vision, standing:Microsoft Computer Vision, large:Microsoft Computer Vision, dog:Microsoft Computer Vision, field:Microsoft Computer Vision, city:Microsoft Computer Vision",

	]

	var art_weight = []


	// CATEGORIZED BY SERVICE

	var art_cats = []

	for (var i = 0; i < art_raw_cats.length; i++) {
		piece_cats = art_raw_cats[i]
		split_cats = piece_cats.split(", ")
		art_cats.push(split_cats)

		piece_weight = art_raw[i]
		split_weight = piece_weight.split(", ")
		art_weight.push(split_weight)
	};

	// console.log("art_weight LIST")
	// console.log(art_weight)

	console.log("cats")
	console.log(art_cats.length)
	console.log("weight")
	console.log(art_weight.length)

	count = 0
	for (var i = 0; i < art_cats.length; i++) {
		piece_cats = art_cats[i]

		piece_weight = art_weight[i]

		print_tags(count.toString(), piece_cats, piece_weight)
		count += 1
	};

	function print_tags(div, piece, piece_weighted) {

		console.log("Printing tags")

		services = ["Clarifai", "CloudSight", "CloudSight_Hybrid", "Google_Vision", "Amazon_Rekognition", "IBM_Visual_Recognition", "Microsoft_Computer_Vision"]

//		 Clarifai, CloudSight, Google_Vision, Amazon_Rekognition, IBM_Visual_Recognition, Microsoft_Computer_Vision

		master = {"Clarifai":[], "CloudSight":[], "CloudSight_Hybrid":[], "Google_Vision":[], "Amazon_Rekognition":[], "IBM_Visual_Recognition":[], "Microsoft_Computer_Vision":[]}


		weight_dict = {}

		for (var i = 0; i < piece_weighted.length; i++) {

			touple_weight = piece_weighted[i]
			singles_weight = touple_weight.split(": ")

			weight_dict[singles_weight[0]] = parseInt(singles_weight[1])
		}


		console.log("dictionary")
		console.log(weight_dict)

		graph_id = div + "_pie"

		//create_graphs(graph_id, weight_dict)
		//create_graphs_bar(graph_id, weight_dict)

		for (var i = 0; i < piece.length; i++) {

			touple = piece[i]

			singles = touple.split(":")

			// singles[0] - the tag, singles_weight[1] - the weight
			tag_and_weight = singles[0]

			// singles[1] - the service
			service = singles[1].replace(/ /g, "_")

			// current values of list
			curs = []

			// list to be copied over
			news = []

			curs = master[service]

			for (var j = 0; j < curs.length; j++) {
				news.push(curs[j])
			}

			news.push(tag_and_weight)

			master[service] = news

		}

		console.log(master)

		for (var i = 0; i < services.length; i++) {

			tags = master[services[i]]

			id = "#" + services[i] + "_" + div
			update_tags(services[i], tags, id, weight_dict)

		}		

		
	};

	function update_tags(service, tags, id, weight_dict) {


		color_dict = ["#616161", "#fab95b", "#ff502f", "#009975", "#454d66", "#7572f4", "#207dff"]

		html_output = "<p>"

		for (var j = 0; j < tags.length; j++) {

			weight = weight_dict[tags[j]]


			color = "<span style='color:" + color_dict[weight - 1] + "'>"

			//html_output += tags[j]

			html_output += color + tags[j] + "</span>"


			if (j != tags.length - 1) {
				html_output += ", "
			}
		}

		html_output += "</p>"


		$(id).html(html_output);
	}

	function create_graphs(id, weight_dict) {

		tags = []
		weights = []

		for (var key in weight_dict) {
		    // check if the property/key is defined in the object itself, not in parent
		    if (weight_dict.hasOwnProperty(key)) {           
		        console.log(key, weight_dict[key]);
		        tags.push(key)
		        weights.push(weight_dict[key])
		    }
		}




	  	var ctxP = document.getElementById(id).getContext('2d');
	  	var myPieChart = new Chart(ctxP, {
	    	type: 'pie',
	    	data: {
	      		labels: tags,
	      		datasets: [{
	        		data: weights,
	        		// backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
	        		// hoverBackgroundColor: ["#FF5A5E", "#5AD3D1", "#FFC870", "#A8B3C5", "#616774"]
	      		}]
	    	},
	    	options: {
	    		legend: {
		            display: true,
		            position: 'left'
		         },
		        plugins: {
			      	colorschemes: {
			        	scheme: 'tableau.Tableau20'
			      	}
			    },
		    	
				
	      		responsive: true
	    	},
		});

	}

	function create_graphs_bar(id, weight_dict) {

		tags = []
		weights = []

		for (var key in weight_dict) {
		    // check if the property/key is defined in the object itself, not in parent
		    if (weight_dict.hasOwnProperty(key)) {           
		        console.log(key, weight_dict[key]);
		        tags.push(key)
		        weights.push(weight_dict[key])
		    }
		}
		var ctx = document.getElementById(id).getContext('2d');

		var myBarChart = new Chart(ctx, {
		    type: 'horizontalBar',
	    	data: {
	      		labels: tags,
	      		datasets: [{
	        		data: weights,
	        		// backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
	        		// hoverBackgroundColor: ["#FF5A5E", "#5AD3D1", "#FFC870", "#A8B3C5", "#616774"]
	      		}]
	    	},
		});
	}
});


