$(document).ready(function(){





	var art_raw = [
		"porcelain: 3, earthenware: 3, art: 2, pottery: 2, tableware: 2, ceramic: 2, plate: 2, utensil: 2, no person: 1, design: 1, round: 1, ornate: 1, round out: 1, decoration: 1, illustration: 1, handmade: 1, pattern: 1, shape: 1, dish: 1, antique: 1, artistic: 1, round white and blue ceramic plate: 1, round multicolored ceramic plate decor: 1, dishware: 1, platter: 1, circle: 1, serveware: 1, emblem: 1, bowl: 1, rug: 1, saucer: 1, majolica earthenware: 1, faience eartherware: 1, ultramarine color: 1, jade green color: 1, a gold coin: 1, colorful: 1, decorated: 1, white: 1, black: 1, large: 1, red: 1, gold: 1, painted: 1, blue: 1, yellow: 1",
		"portrait: 2, art: 2, man: 2, woman: 2, photography: 2, photo: 2, people: 1, one: 1, lid: 1, adult: 1, veil: 1, wear: 1, cap: 1, military: 1, profile: 1, facial hair: 1, vintage: 1, painting: 1, sepia: 1, retro: 1, royalty: 1, military uniform: 1, man wearing black suit jacket photo: 1, woman wearing headband: 1, photograph: 1, headgear: 1, history: 1, vintage clothing: 1, person: 1, human: 1, face: 1, head: 1, accessories: 1, accessory: 1, jewelry: 1, archaeology: 1, passe-partout (frame): 1, framework: 1, supporting structure: 1, frame: 1, picture frame: 1, book: 1, book jacket: 1, wrapping: 1, maroon color: 1, a black and white photo of a person: 1, black: 1, white: 1, monitor: 1, sitting: 1, old: 1, food: 1, holding: 1, standing: 1, cat: 1",
		"nature: 4, landscape: 3, hill: 3, field: 3, mountain: 2, outdoors: 2, sky: 2, grass: 2, countryside: 2, farm: 2, rural: 2, painting: 2, no person: 1, tree: 1, valley: 1, scenic: 1, agriculture: 1, dawn: 1, travel: 1, cropland: 1, sunset: 1, brown and green trees painting: 1, green leaf tree: 1, natural landscape: 1, watercolor paint: 1, rural area: 1, plain: 1, acrylic paint: 1, art: 1, building: 1, housing: 1, scenery: 1, house: 1, grassland: 1, hut: 1, oil paint: 1, paint: 1, hay: 1, fodder: 1, feed: 1, food: 1, slope: 1, natural elevation: 1, olive green color: 1, ultramarine color: 1, a waterfall with a mountain in the background: 1, outdoor: 1, sheep: 1, water: 1, rock: 1, large: 1, grazing: 1, view: 1, waterfall: 1, old: 1, green: 1, standing: 1, rocky: 1, horse: 1, many: 1, covered: 1, herd: 1, grassy: 1, man: 1, flock: 1, river: 1",
		"pattern: 3, white: 3, blue: 3, art: 2, design: 2, no person: 1, illustration: 1, desktop: 1, paper: 1, vintage: 1, decoration: 1, abstract: 1, retro: 1, symbol: 1, card: 1, color: 1, one: 1, flower: 1, texture: 1, still life: 1, container: 1, cutout: 1, and green floral textile: 1, orange and blue floral board: 1, textile: 1, visual arts: 1, porcelain: 1, pottery: 1, rug: 1, embroidery: 1, graphics: 1, floral design: 1, clutch bag: 1, handbag: 1, purse: 1, bag: 1, etui (ladies bag): 1, pencil box: 1, box: 1, cardcase: 1, utensil: 1, food: 1, fabric: 1, ultramarine color: 1, thing: 1, decorated: 1, sitting: 1, table: 1, colorful: 1, side: 1, large: 1, yellow: 1, board: 1, red: 1, vase: 1",
		"sculpture: 2, statue: 2, art: 2, museum: 2, marble: 2, stone: 2, building: 2, monument: 1, old: 1, travel: 1, architecture: 1, ancient: 1, grave: 1, religion: 1, urban: 1, city: 1, church: 1, cemetery: 1, lion: 1, god: 1, offensive: 1, knight statue: 1, classical sculpture: 1, stone carving: 1, carving: 1, relief: 1, visual arts: 1, soil: 1, archaeology: 1, flagstone: 1, sarcophagus  coffin: 1, box: 1, memorial: 1, stele (stone slab with markings): 1, gargoyle (water spout): 1, alabaster color: 1, stuffed: 1, sitting: 1, teddy: 1, sidewalk: 1, bear: 1, laying: 1, food: 1, table: 1, floor: 1, lying: 1, feet: 1, dog: 1, holding: 1, large: 1, board: 1, baby: 1, man: 1, cutting: 1, standing: 1, kitchen: 1, street: 1, white: 1",
		"portrait: 3, face: 3, person: 3, old: 2, art: 2, man: 2, hair: 2, head: 2, photo: 2, people: 1, woman: 1, one: 1, eye: 1, girl: 1, texture: 1, vintage: 1, paper: 1, fashion: 1, sepia: 1, antique: 1, desktop: 1, adult: 1, black and white abstract painting: 1, womans face: 1, forehead: 1, facial hair: 1, eyebrow: 1, nose: 1, chin: 1, self-portrait: 1, painting: 1, human: 1, drawing: 1, photography: 1, sketch: 1, silverpoint: 1, gray color: 1, ash grey color: 1, a person looking at the camera: 1, text: 1, book: 1, looking: 1, sitting: 1, young: 1, white: 1, cat: 1, standing: 1",
		"art: 3, painting: 3, illustration: 2, architecture: 2, building: 2, room: 2, old: 2, clock: 2, house: 1, print: 1, people: 1, no person: 1, bird: 1, lamp: 1, family: 1, vintage: 1, furniture: 1, wood: 1, window: 1, lithograph: 1, woman: 1, brown wooden framed wall decor: 1, brown bird house illustration: 1, visual arts: 1, tower: 1, clock tower: 1, human: 1, person: 1, drawing: 1, cuckoo clock: 1, timepiece: 1, measuring instrument: 1, kachina dolls: 1, shadow box: 1, box: 1, light brown color: 1, dark red color: 1, a bedroom with a bed and a mirror: 1, indoor: 1, photo: 1, sitting: 1, small: 1, items: 1, mirror: 1, table: 1, various: 1, brown: 1, cat: 1, black: 1, bed: 1, man: 1, living: 1, hanging: 1, laying: 1, sink: 1, bedroom: 1, kitchen: 1, white: 1, holding: 1, stove: 1, display: 1, sleeping: 1",
		"figurine: 3, sculpture: 2, art: 2, antique: 2, statue: 2, bronze: 2, no person: 1, carpentry: 1, metalwork: 1, one: 1, ancient: 1, wood: 1, retro: 1, figure: 1, old: 1, people: 1, steel: 1, woman: 1, arts and crafts: 1, traditional: 1, man: 1, brass-colored metal frame: 1, gray and brown figurine: 1, bronze sculpture: 1, metal: 1, monument: 1, nonbuilding structure: 1, toy: 1, architecture: 1, building: 1, symbol: 1, emblem: 1, column: 1, pillar: 1, person: 1, human: 1, totem: 1, tiki: 1, reliquary container: 1, oil lamp: 1, lamp: 1, safety lamp: 1, mouthpiece: 1, acoustic device: 1, controller: 1, game equipment: 1, alabaster color: 1, ultramarine color: 1, thing: 1, indoor: 1, sitting: 1, table: 1, clock: 1, wooden: 1, brown: 1, tall: 1, orange: 1, large: 1, display: 1, standing: 1, cat: 1, vase: 1, holding: 1",
		"clothing: 4, coat: 4, jacket: 3, fashion: 2, woman: 2, man: 2, dress: 2, costume: 2, red: 2, sleeve: 2, fur: 2, person: 2, winter: 1, portrait: 1, wear: 1, leather: 1, studio: 1, model: 1, art: 1, adult: 1, traditional: 1, retro: 1, girl: 1, one: 1, elegant: 1, christmas: 1, womens red and brown long sleeve dress: 1, red and gold traditional dress on white background: 1, outerwear: 1, maroon: 1, robe: 1, velvet: 1, apparel: 1, overcoat: 1, human: 1, long sleeve: 1, toy: 1, doll: 1, garment: 1, overgarment: 1, jabot (ruffle of dress): 1, dolman jacket: 1, coating: 1, fabric: 1, dark red color: 1, indian red color: 1, a woman wearing a red dress standing in front of a coat: 1, wearing: 1, dressed: 1, phone: 1, cellphone: 1, looking: 1, lady: 1, hat: 1, standing: 1, outfit: 1, walking: 1, snow: 1, holding: 1, talking: 1, suit: 1, field: 1, covered: 1, large: 1, white: 1, head: 1, shirt: 1, street: 1, skiing: 1, umbrella: 1",
		"sculpture: 4, statue: 4, art: 3, temple: 2, old: 2, figurine: 2, archaeology: 2, stone: 2, person: 2, ancient: 1, buddha: 1, religion: 1, no person: 1, veil: 1, travel: 1, god: 1, culture: 1, museum: 1, grave: 1, antique: 1, spirituality: 1, gray and black ceramic figurine: 1, concrete statue: 1, stone carving: 1, classical sculpture: 1, forehead: 1, monument: 1, artifact: 1, stock photography: 1, human: 1, kneeling: 1, socle: 1, support: 1, supporting structure: 1, stele (stone slab with markings): 1, ancient person: 1, alabaster color: 1, a statue of a person: 1, sitting: 1, standing: 1, man: 1, suit: 1, wearing: 1, green: 1, brown: 1, gray: 1, clock: 1, tower: 1, large: 1, tall: 1, hat: 1, luggage: 1, brick: 1, white: 1, stacked: 1",
		"pattern: 4, rug: 4, art: 3, fabric: 3, textile: 2, paisley: 2, decoration: 1, flower: 1, texture: 1, retro: 1, design: 1, desktop: 1, abstract: 1, vintage: 1, antique: 1, floral: 1, illustration: 1, style: 1, old: 1, handicraft: 1, ornate: 1, handmade: 1, green: 1, red: 1, and yellow floral textile: 1, brown and green dragon graphic carpet: 1, motif: 1, visual arts: 1, applique: 1, tapestry: 1, floor cover: 1, scatter rug: 1, paisley fabric: 1, olive green color: 1, a fabric surface: 1, clothing: 1",
		"art: 3, painting: 3, person: 3, people: 2, man: 2, portrait: 2, standing: 2, clothing: 2, vintage: 1, lid: 1, one: 1, retro: 1, fall: 1, tree: 1, woman: 1, old: 1, adult: 1, antique: 1, nature: 1, illustration: 1, wear: 1, veil: 1, color: 1, man in black suit painting: 1, man wearing magician hat painting: 1, lady: 1, visual arts: 1, self-portrait: 1, artist: 1, apparel: 1, human: 1, hat: 1, golf: 1, athletic game: 1, sport: 1, cassock: 1, gown: 1, outerwear: 1, frock coat: 1, coat: 1, overgarment: 1, garment: 1, olive green color: 1, coal black color: 1, a man that is standing in the grass: 1, grass: 1, outdoor: 1, field: 1, building: 1, cellphone: 1, phone: 1, holding: 1, wearing: 1, black: 1, walking: 1, young: 1, park: 1, baseball: 1, street: 1, ball: 1, white: 1",
		"sculpture: 3, mammal: 3, figurine: 3, bronze: 3, animal: 3, art: 2, dog: 2, wildlife: 2, carnivore: 2, no person: 1, lion: 1, statue: 1, museum: 1, metalwork: 1, deer: 1, ancient: 1, one: 1, cavalry: 1, nude: 1, illustration: 1, reindeer: 1, brown wooden horse head figurine: 1, brass-colored lion figurine: 1, bronze sculpture: 1, animal figure: 1, metal: 1, brass: 1, canidae: 1, ancient dog breeds: 1, antelope: 1, horse: 1, musical instrument: 1, brass section: 1, cushion: 1, wood: 1, furniture: 1, andiron (used in fireplace): 1, support: 1, gilt (golden faced): 1, coating: 1, saber-toothed tiger: 1, big cat: 1, feline: 1, artifact: 1, light brown color: 1, a close up of a dog: 1, brown: 1, sitting: 1, zebra: 1, standing: 1, playing: 1, man: 1",
		"gun: 5, weapon: 4, firearm: 2, rifle: 2, still life: 1, art: 1, no person: 1, vintage: 1, cutout: 1, retro: 1, pistol: 1, old: 1, one: 1, studio: 1, metalwork: 1, antique: 1, wear: 1, furniture: 1, steel: 1, mammal: 1, military: 1, people: 1, white and brown wooden ship scale model: 1, two white flintlocks: 1, bow and arrow: 1, trigger: 1, ranged weapon: 1, bow: 1, wood: 1, crossbow: 1, shotgun: 1, weaponry: 1, handgun: 1, flintlock gun: 1, matchlock: 1, muzzle loader gun: 1, alabaster color: 1, a close up of a gun: 1, thing: 1, sitting: 1, table: 1, small: 1, water: 1, black: 1, boat: 1, laying: 1, air: 1, white: 1",
		"furniture: 4, gold: 3, bronze: 3, table: 3, antique: 2, old: 2, brass: 2, metal: 2, no person: 1, metalwork: 1, art: 1, ornate: 1, luxury: 1, gilt: 1, ancient: 1, carpentry: 1, wealth: 1, baroque: 1, classic: 1, castle: 1, architecture: 1, victorian: 1, brown wooden wall mount rack: 1, brass-colored container: 1, coffee table: 1, end table: 1, games: 1, miniature: 1, treasure: 1, cabinet: 1, tabletop: 1, crib: 1, settee (bench): 1, bench: 1, seat: 1, sheraton furniture: 1, dressing table: 1, sideboard (counter): 1, reddish brown color: 1, olive green color: 1, a gold clock sitting on top of a table: 1, small: 1, sitting: 1, clock: 1, hanging: 1, room: 1, white: 1, water: 1, standing: 1",
		"building: 5, city: 4, tower: 4, architecture: 3, town: 3, art: 2, people: 2, street: 2, group: 2, many: 2, plaza: 2, urban: 2, travel: 1, cathedral: 1, church: 1, religion: 1, bridge: 1, no person: 1, sunset: 1, sky: 1, brown wooden framed painting of house: 1, venice- 16th cenutry: 1, othello by emma thornton on prezi: 1, landmark: 1, human settlement: 1, public space: 1, town square: 1, clock tower: 1, person: 1, human: 1, painting: 1, downtown: 1, lighthouse: 1, beacon: 1, temple: 1, shrine: 1, worship: 1, landscape: 1, nature: 1, panoramic: 1, outdoors: 1, scenery: 1, bell tower: 1, column: 1, pillar: 1, religious building: 1, belfry tower: 1, mecca: 1, blue color: 1, a group of people walking in front of piazza san marco: 1, outdoor: 1, standing: 1, walking: 1, sheep: 1, large: 1, front: 1, snow: 1, horse: 1, clock: 1, old: 1, rug: 1, man: 1, riding: 1, water: 1, flock: 1, herd: 1",
		"art: 3, painting: 3, illustration: 2, picture frame: 2, old: 2, religion: 1, god: 1, narrative: 1, vintage: 1, retro: 1, aura: 1, ancient: 1, woman: 1, desktop: 1, culture: 1, spirituality: 1, manuscript: 1, design: 1, baby: 1, style: 1, woman in white dress painting: 1, woman and man painting: 1, miniature: 1, visual arts: 1, fictional character: 1, human: 1, person: 1, mail: 1, envelope: 1, prayer: 1, worship: 1, greeting card: 1, tapestry: 1, fabric: 1, framework: 1, supporting structure: 1, shadow box: 1, box: 1, light brown color: 1, beige color: 1, a close up of a book: 1, text: 1, photo: 1, sitting: 1, book: 1, table: 1, suitcase: 1, luggage: 1, brown: 1, bear: 1, computer: 1, stuffed: 1",
		"furniture: 4, table: 4, antique: 2, cabinet: 2, old: 2, desk: 2, drawer: 2, metalwork: 1, no person: 1, art: 1, ornate: 1, inlay: 1, carpentry: 1, painting: 1, wood: 1, gold: 1, container: 1, decoration: 1, ancient: 1, one: 1, illustration: 1, ebony: 1, bronze: 1, brown wooden single pedestal desk: 1, brown and black wooden cabinet: 1, napoleon iii style: 1, nightstand: 1, end table: 1, sideboard: 1, tabletop: 1, lowboy: 1, davenport desk: 1, marquetry (veneers): 1, boulle (furniture): 1, reddish brown color: 1, a wooden table: 1, indoor: 1, small: 1, sitting: 1, wooden: 1, room: 1, bed: 1, living: 1, large: 1, carriage: 1",
		"glass: 4, lamp: 3, bottle: 2, silver: 2, no person: 1, glass items: 1, still life: 1, wine: 1, h2o: 1, trophy: 1, vodka: 1, reflection: 1, victory: 1, antique: 1, drink: 1, empty: 1, cup: 1, retro: 1, luxury: 1, classic: 1, container: 1, old: 1, clear glass base table lamp: 1, clear glass footed beverage dispenser: 1, product: 1, still life photography: 1, metal: 1, barware: 1, lantern: 1, goblet: 1, lighting: 1, censer container: 1, samovar urn: 1, pot: 1, porringer bowl: 1, bowl: 1, tableware: 1, utensil: 1, oil lamp: 1, gray color: 1, ivory color: 1, a tall glass vase on a table: 1, indoor: 1, table: 1, sitting: 1, small: 1, vase: 1, black: 1, white: 1, clock: 1, desk: 1, flower: 1, holding: 1, clear: 1, display: 1, room: 1, tall: 1",
		"art: 2, furniture: 2, indoors: 2, room: 2, screen: 2, people: 1, illustration: 1, no person: 1, education: 1, man: 1, school: 1, wood: 1, painting: 1, business: 1, print: 1, travel: 1, container: 1, chalk: 1, adult: 1, study: 1, retro: 1, brown wooden framed wall decor: 1, black 3-panel wooden room divider with art: 1, modern art: 1, banner: 1, calligraphy: 1, room divider: 1, visual arts: 1, metal: 1, rectangle: 1, electronics: 1, monitor: 1, display: 1, advertisement: 1, lcd screen: 1, billboard: 1, shop: 1, marquetry (veneers): 1, multi panel pictures/art: 1, passe-partout (frame): 1, framework: 1, supporting structure: 1, pale yellow color: 1, a close up of a sign: 1, photo: 1, black: 1, table: 1, wooden: 1, sign: 1, refrigerator: 1, kitchen: 1, computer: 1",
		"bag: 4, handbag: 3, accessory: 2, retro: 1, no person: 1, antique: 1, classic: 1, leather: 1, container: 1, handmade: 1, vintage: 1, old: 1, elegant: 1, handle: 1, luxury: 1, style: 1, wood: 1, arts and crafts: 1, fashion: 1, art: 1, isolated: 1, one: 1, brass: 1, brown and black floral leather tote bag: 1, gold and black floral watering can: 1, brown: 1, fashion accessory: 1, shoulder bag: 1, accessories: 1, watering can: 1, can: 1, tin: 1, pottery: 1, pot: 1, coal scuttle: 1, carpetbag: 1, traveling bag: 1, luggage: 1, purse: 1, clothing: 1, light brown color: 1, beige color: 1, indoor: 1, table: 1, sitting: 1, cup: 1, small: 1, coffee: 1, piece: 1, decorated: 1, vase: 1, wooden: 1, black: 1, flower: 1, cake: 1, banana: 1, plate: 1, fruit: 1, board: 1, water: 1, white: 1",
		"art: 3, painting: 3, church: 2, people: 2, group: 2, architecture: 2, altar: 2, person: 2, building: 2, saint: 1, religion: 1, mary: 1, god: 1, kneeling: 1, book: 1, cross: 1, chapel: 1, veil: 1, cathedral: 1, throne: 1, aura: 1, apostle: 1, renaissance: 1, gown (clothing): 1, brown wooden framed wall decor: 1, religious painting: 1, holy places: 1, history: 1, stock photography: 1, statue: 1, middle ages: 1, arch: 1, human: 1, altarpiece: 1, screen: 1, indoors: 1, indian red color: 1, alabaster color: 1, a group of people sitting on a bench posing for the camera: 1, bench: 1, sitting: 1, photo: 1, standing: 1, man: 1, posing: 1, wooden: 1, old: 1, water: 1, woman: 1",
		"violin: 4, cello: 4, viola: 4, musical instrument: 3, music: 2, instrument: 2, bowed stringed instrument: 2, string instrument: 2, viol: 2, classical music: 1, no person: 1, classic: 1, wood: 1, artistic: 1, art: 1, sound: 1, orchestra: 1, musician: 1, antique: 1, retro: 1, carpentry: 1, one: 1, old: 1, brown and black violin with bow: 1, brown violin: 1, violin family: 1, bowed string instrument: 1, violone: 1, leisure activities: 1, fiddle: 1, guitar: 1, stringed instrument: 1, viola da gamba: 1, 'viola damore': 1, reddish brown color: 1, a close up of a violin: 1, brown: 1, orange: 1",
		"painting: 4, art: 3, person: 3, woman: 2, people: 1, print: 1, portrait: 1, vintage: 1, nude: 1, one: 1, baby: 1, retro: 1, adult: 1, illustration: 1, decoration: 1, furniture: 1, antique: 1, interior: 1, girl: 1, family: 1, old: 1, womens black hair: 1, woman combing her hair holding hand mirror painting: 1, lady: 1, picture frame: 1, fictional character: 1, still life: 1, photography: 1, long hair: 1, visual arts: 1, modern art: 1, human: 1, oil paint: 1, paint: 1, kisser: 1, beige color: 1, a person holding a cat: 1, indoor: 1, sitting: 1, looking: 1, cat: 1, holding: 1, man: 1, brown: 1, hair: 1, playing: 1, phone: 1, dog: 1, mouth: 1, white: 1, teeth: 1, laying: 1, room: 1, bed: 1, standing: 1, brushing: 1, stuffed: 1",
		"painting: 4, art: 3, illustration: 2, people: 2, old: 2, elephant: 2, tapestry: 2, print: 1, fish: 1, animal: 1, prehistoric: 1, bird: 1, ancient: 1, engraving: 1, vintage: 1, pattern: 1, design: 1, mammal: 1, religion: 1, antique: 1, symbol: 1, blue and brown wooden wall decor: 1, painting of angel over fish: 1, visual arts: 1, history: 1, fictional character: 1, prophet: 1, person: 1, human: 1, clothing: 1, apparel: 1, drawing: 1, fabric: 1, rug: 1, floor cover: 1, beige color: 1, olive green color: 1, a painting of a book: 1, text: 1, book: 1, photo: 1, sitting: 1, holding: 1, man: 1, stuffed: 1, woman: 1, table: 1, bed: 1, bear: 1, laying: 1, riding: 1",
		"boat: 5, vehicle: 4, watercraft: 3, water: 2, people: 2, river: 2, lake: 2, painting: 2, art: 2, fisherman: 1, rowboat: 1, transportation system: 1, fishing boat: 1, travel: 1, sea: 1, ocean: 1, canoe: 1, beach: 1, ship: 1, seashore: 1, no person: 1, fish: 1, brown and white sailing boat painting: 1, brown boat: 1, water transportation: 1, watercolor paint: 1, boating: 1, transportation: 1, human: 1, person: 1, jolly boat: 1, small boat: 1, craft: 1, sampan skif: 1, dugout canoe: 1, sea green color: 1, a small boat in a body of water: 1, outdoor: 1, small: 1, sitting: 1, old: 1, black: 1, man: 1, row: 1, body: 1, white: 1, parked: 1, table: 1, woman: 1, floating: 1, large: 1, riding: 1, bowl: 1, group: 1, standing: 1, city: 1, docked: 1, snow: 1",
	]

	var art_raw_cats = [
		"art:Clarifai, pottery:Clarifai, no person:Clarifai, design:Clarifai, round:Clarifai, ornate:Clarifai, round out:Clarifai, decoration:Clarifai, tableware:Clarifai, porcelain:Clarifai, illustration:Clarifai, handmade:Clarifai, pattern:Clarifai, shape:Clarifai, ceramic:Clarifai, dish:Clarifai, earthenware:Clarifai, plate:Clarifai, antique:Clarifai, artistic:Clarifai, round white and blue ceramic plate:CloudSight, round multicolored ceramic plate decor:CloudSight Hybrid, dishware:Google Vision, porcelain:Google Vision, plate:Google Vision, ceramic:Google Vision, tableware:Google Vision, platter:Google Vision, circle:Google Vision, serveware:Google Vision, earthenware:Google Vision, emblem:Google Vision, pottery:Amazon Rekognition, art:Amazon Rekognition, porcelain:Amazon Rekognition, bowl:Amazon Rekognition, rug:Amazon Rekognition, saucer:Amazon Rekognition, majolica earthenware:IBM Visual Recognition, earthenware:IBM Visual Recognition, utensil:IBM Visual Recognition, faience eartherware:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, jade green color:IBM Visual Recognition, a gold coin:Microsoft Computer Vision, utensil:Microsoft Computer Vision, colorful:Microsoft Computer Vision, decorated:Microsoft Computer Vision, white:Microsoft Computer Vision, black:Microsoft Computer Vision, large:Microsoft Computer Vision, red:Microsoft Computer Vision, gold:Microsoft Computer Vision, painted:Microsoft Computer Vision, blue:Microsoft Computer Vision, yellow:Microsoft Computer Vision",
		"portrait:Clarifai, people:Clarifai, art:Clarifai, one:Clarifai, lid:Clarifai, adult:Clarifai, veil:Clarifai, wear:Clarifai, man:Clarifai, cap:Clarifai, woman:Clarifai, military:Clarifai, profile:Clarifai, facial hair:Clarifai, vintage:Clarifai, painting:Clarifai, sepia:Clarifai, retro:Clarifai, royalty:Clarifai, military uniform:Clarifai, man wearing black suit jacket photo:CloudSight, woman wearing headband:CloudSight Hybrid, photograph:Google Vision, art:Google Vision, headgear:Google Vision, history:Google Vision, vintage clothing:Google Vision, photography:Google Vision, person:Amazon Rekognition, human:Amazon Rekognition, face:Amazon Rekognition, head:Amazon Rekognition, photography:Amazon Rekognition, portrait:Amazon Rekognition, photo:Amazon Rekognition, accessories:Amazon Rekognition, accessory:Amazon Rekognition, jewelry:Amazon Rekognition, archaeology:Amazon Rekognition, passe-partout (frame):IBM Visual Recognition, framework:IBM Visual Recognition, supporting structure:IBM Visual Recognition, frame:IBM Visual Recognition, picture frame:IBM Visual Recognition, book:IBM Visual Recognition, book jacket:IBM Visual Recognition, wrapping:IBM Visual Recognition, maroon color:IBM Visual Recognition, a black and white photo of a person:Microsoft Computer Vision, photo:Microsoft Computer Vision, black:Microsoft Computer Vision, white:Microsoft Computer Vision, monitor:Microsoft Computer Vision, sitting:Microsoft Computer Vision, woman:Microsoft Computer Vision, old:Microsoft Computer Vision, food:Microsoft Computer Vision, holding:Microsoft Computer Vision, man:Microsoft Computer Vision, standing:Microsoft Computer Vision, cat:Microsoft Computer Vision",
		"no person:Clarifai, landscape:Clarifai, nature:Clarifai, mountain:Clarifai, hill:Clarifai, tree:Clarifai, outdoors:Clarifai, valley:Clarifai, scenic:Clarifai, agriculture:Clarifai, dawn:Clarifai, travel:Clarifai, sky:Clarifai, grass:Clarifai, countryside:Clarifai, farm:Clarifai, rural:Clarifai, cropland:Clarifai, sunset:Clarifai, field:Clarifai, brown and green trees painting:CloudSight, green leaf tree:CloudSight Hybrid, painting:Google Vision, nature:Google Vision, sky:Google Vision, natural landscape:Google Vision, hill:Google Vision, watercolor paint:Google Vision, rural area:Google Vision, plain:Google Vision, landscape:Google Vision, acrylic paint:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, nature:Amazon Rekognition, outdoors:Amazon Rekognition, countryside:Amazon Rekognition, building:Amazon Rekognition, rural:Amazon Rekognition, housing:Amazon Rekognition, landscape:Amazon Rekognition, scenery:Amazon Rekognition, field:Amazon Rekognition, farm:Amazon Rekognition, house:Amazon Rekognition, grassland:Amazon Rekognition, hut:Amazon Rekognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, hay:IBM Visual Recognition, fodder:IBM Visual Recognition, feed:IBM Visual Recognition, food:IBM Visual Recognition, slope:IBM Visual Recognition, natural elevation:IBM Visual Recognition, olive green color:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, a waterfall with a mountain in the background:Microsoft Computer Vision, grass:Microsoft Computer Vision, mountain:Microsoft Computer Vision, nature:Microsoft Computer Vision, outdoor:Microsoft Computer Vision, sheep:Microsoft Computer Vision, field:Microsoft Computer Vision, water:Microsoft Computer Vision, rock:Microsoft Computer Vision, large:Microsoft Computer Vision, grazing:Microsoft Computer Vision, view:Microsoft Computer Vision, waterfall:Microsoft Computer Vision, old:Microsoft Computer Vision, green:Microsoft Computer Vision, standing:Microsoft Computer Vision, rocky:Microsoft Computer Vision, horse:Microsoft Computer Vision, many:Microsoft Computer Vision, hill:Microsoft Computer Vision, covered:Microsoft Computer Vision, herd:Microsoft Computer Vision, grassy:Microsoft Computer Vision, man:Microsoft Computer Vision, flock:Microsoft Computer Vision, river:Microsoft Computer Vision",
		"no person:Clarifai, illustration:Clarifai, art:Clarifai, desktop:Clarifai, design:Clarifai, paper:Clarifai, vintage:Clarifai, decoration:Clarifai, abstract:Clarifai, retro:Clarifai, symbol:Clarifai, card:Clarifai, pattern:Clarifai, color:Clarifai, one:Clarifai, flower:Clarifai, texture:Clarifai, still life:Clarifai, container:Clarifai, cutout:Clarifai, white:CloudSight, blue:CloudSight, and green floral textile:CloudSight, white:CloudSight Hybrid, orange and blue floral board:CloudSight Hybrid, blue:Google Vision, pattern:Google Vision, design:Google Vision, textile:Google Vision, visual arts:Google Vision, porcelain:Amazon Rekognition, art:Amazon Rekognition, pottery:Amazon Rekognition, pattern:Amazon Rekognition, rug:Amazon Rekognition, embroidery:Amazon Rekognition, graphics:Amazon Rekognition, floral design:Amazon Rekognition, clutch bag:IBM Visual Recognition, handbag:IBM Visual Recognition, purse:IBM Visual Recognition, bag:IBM Visual Recognition, etui (ladies bag):IBM Visual Recognition, pencil box:IBM Visual Recognition, box:IBM Visual Recognition, cardcase:IBM Visual Recognition, utensil:IBM Visual Recognition, food:IBM Visual Recognition, fabric:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, thing:Microsoft Computer Vision, decorated:Microsoft Computer Vision, sitting:Microsoft Computer Vision, table:Microsoft Computer Vision, colorful:Microsoft Computer Vision, blue:Microsoft Computer Vision, white:Microsoft Computer Vision, side:Microsoft Computer Vision, large:Microsoft Computer Vision, yellow:Microsoft Computer Vision, board:Microsoft Computer Vision, red:Microsoft Computer Vision, vase:Microsoft Computer Vision",
		"sculpture:Clarifai, statue:Clarifai, art:Clarifai, museum:Clarifai, monument:Clarifai, old:Clarifai, travel:Clarifai, architecture:Clarifai, marble:Clarifai, stone:Clarifai, ancient:Clarifai, building:Clarifai, grave:Clarifai, religion:Clarifai, urban:Clarifai, city:Clarifai, church:Clarifai, cemetery:Clarifai, lion:Clarifai, god:Clarifai, offensive:CloudSight, knight statue:CloudSight Hybrid, sculpture:Google Vision, statue:Google Vision, classical sculpture:Google Vision, art:Google Vision, stone carving:Google Vision, carving:Google Vision, relief:Google Vision, museum:Google Vision, visual arts:Google Vision, marble:Google Vision, soil:Amazon Rekognition, archaeology:Amazon Rekognition, flagstone:Amazon Rekognition, sarcophagus  coffin:IBM Visual Recognition, box:IBM Visual Recognition, memorial:IBM Visual Recognition, stele (stone slab with markings):IBM Visual Recognition, gargoyle (water spout):IBM Visual Recognition, alabaster color:IBM Visual Recognition, building:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, sitting:Microsoft Computer Vision, teddy:Microsoft Computer Vision, sidewalk:Microsoft Computer Vision, bear:Microsoft Computer Vision, laying:Microsoft Computer Vision, food:Microsoft Computer Vision, table:Microsoft Computer Vision, floor:Microsoft Computer Vision, lying:Microsoft Computer Vision, feet:Microsoft Computer Vision, dog:Microsoft Computer Vision, holding:Microsoft Computer Vision, large:Microsoft Computer Vision, board:Microsoft Computer Vision, baby:Microsoft Computer Vision, man:Microsoft Computer Vision, cutting:Microsoft Computer Vision, standing:Microsoft Computer Vision, kitchen:Microsoft Computer Vision, street:Microsoft Computer Vision, white:Microsoft Computer Vision, stone:Microsoft Computer Vision",
		"portrait:Clarifai, face:Clarifai, old:Clarifai, art:Clarifai, people:Clarifai, woman:Clarifai, man:Clarifai, one:Clarifai, eye:Clarifai, girl:Clarifai, texture:Clarifai, hair:Clarifai, vintage:Clarifai, paper:Clarifai, fashion:Clarifai, sepia:Clarifai, antique:Clarifai, desktop:Clarifai, adult:Clarifai, person:Clarifai, black and white abstract painting:CloudSight, womans face:CloudSight Hybrid, face:Google Vision, hair:Google Vision, head:Google Vision, forehead:Google Vision, facial hair:Google Vision, portrait:Google Vision, eyebrow:Google Vision, nose:Google Vision, chin:Google Vision, self-portrait:Google Vision, art:Amazon Rekognition, head:Amazon Rekognition, painting:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, face:Amazon Rekognition, drawing:Amazon Rekognition, photo:Amazon Rekognition, photography:Amazon Rekognition, portrait:Amazon Rekognition, sketch:Amazon Rekognition, person:IBM Visual Recognition, silverpoint:IBM Visual Recognition, gray color:IBM Visual Recognition, ash grey color:IBM Visual Recognition, a person looking at the camera:Microsoft Computer Vision, text:Microsoft Computer Vision, book:Microsoft Computer Vision, photo:Microsoft Computer Vision, looking:Microsoft Computer Vision, man:Microsoft Computer Vision, old:Microsoft Computer Vision, sitting:Microsoft Computer Vision, young:Microsoft Computer Vision, white:Microsoft Computer Vision, cat:Microsoft Computer Vision, standing:Microsoft Computer Vision",
		"art:Clarifai, illustration:Clarifai, house:Clarifai, painting:Clarifai, print:Clarifai, people:Clarifai, no person:Clarifai, bird:Clarifai, lamp:Clarifai, architecture:Clarifai, building:Clarifai, family:Clarifai, room:Clarifai, vintage:Clarifai, furniture:Clarifai, wood:Clarifai, window:Clarifai, old:Clarifai, lithograph:Clarifai, woman:Clarifai, brown wooden framed wall decor:CloudSight, brown bird house illustration:CloudSight Hybrid, illustration:Google Vision, painting:Google Vision, art:Google Vision, visual arts:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, tower:Amazon Rekognition, building:Amazon Rekognition, clock tower:Amazon Rekognition, architecture:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, drawing:Amazon Rekognition, cuckoo clock:IBM Visual Recognition, clock:IBM Visual Recognition, timepiece:IBM Visual Recognition, measuring instrument:IBM Visual Recognition, kachina dolls:IBM Visual Recognition, shadow box:IBM Visual Recognition, box:IBM Visual Recognition, light brown color:IBM Visual Recognition, dark red color:IBM Visual Recognition, a bedroom with a bed and a mirror:Microsoft Computer Vision, indoor:Microsoft Computer Vision, photo:Microsoft Computer Vision, sitting:Microsoft Computer Vision, small:Microsoft Computer Vision, items:Microsoft Computer Vision, mirror:Microsoft Computer Vision, table:Microsoft Computer Vision, room:Microsoft Computer Vision, various:Microsoft Computer Vision, old:Microsoft Computer Vision, brown:Microsoft Computer Vision, cat:Microsoft Computer Vision, black:Microsoft Computer Vision, bed:Microsoft Computer Vision, man:Microsoft Computer Vision, living:Microsoft Computer Vision, hanging:Microsoft Computer Vision, laying:Microsoft Computer Vision, clock:Microsoft Computer Vision, sink:Microsoft Computer Vision, bedroom:Microsoft Computer Vision, kitchen:Microsoft Computer Vision, white:Microsoft Computer Vision, holding:Microsoft Computer Vision, stove:Microsoft Computer Vision, display:Microsoft Computer Vision, sleeping:Microsoft Computer Vision",
		"no person:Clarifai, sculpture:Clarifai, carpentry:Clarifai, art:Clarifai, metalwork:Clarifai, one:Clarifai, ancient:Clarifai, figurine:Clarifai, wood:Clarifai, antique:Clarifai, retro:Clarifai, figure:Clarifai, old:Clarifai, people:Clarifai, steel:Clarifai, woman:Clarifai, statue:Clarifai, arts and crafts:Clarifai, traditional:Clarifai, man:Clarifai, brass-colored metal frame:CloudSight, gray and brown figurine:CloudSight Hybrid, sculpture:Google Vision, statue:Google Vision, bronze sculpture:Google Vision, figurine:Google Vision, art:Google Vision, bronze:Google Vision, metal:Google Vision, monument:Google Vision, antique:Google Vision, nonbuilding structure:Google Vision, toy:Amazon Rekognition, architecture:Amazon Rekognition, building:Amazon Rekognition, bronze:Amazon Rekognition, symbol:Amazon Rekognition, emblem:Amazon Rekognition, column:Amazon Rekognition, pillar:Amazon Rekognition, figurine:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, totem:Amazon Rekognition, tiki:Amazon Rekognition, reliquary container:IBM Visual Recognition, oil lamp:IBM Visual Recognition, lamp:IBM Visual Recognition, safety lamp:IBM Visual Recognition, mouthpiece:IBM Visual Recognition, acoustic device:IBM Visual Recognition, controller:IBM Visual Recognition, game equipment:IBM Visual Recognition, alabaster color:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, thing:Microsoft Computer Vision, indoor:Microsoft Computer Vision, sitting:Microsoft Computer Vision, table:Microsoft Computer Vision, clock:Microsoft Computer Vision, wooden:Microsoft Computer Vision, brown:Microsoft Computer Vision, tall:Microsoft Computer Vision, orange:Microsoft Computer Vision, large:Microsoft Computer Vision, display:Microsoft Computer Vision, standing:Microsoft Computer Vision, cat:Microsoft Computer Vision, vase:Microsoft Computer Vision, holding:Microsoft Computer Vision",
		"fashion:Clarifai, winter:Clarifai, portrait:Clarifai, woman:Clarifai, wear:Clarifai, leather:Clarifai, studio:Clarifai, man:Clarifai, model:Clarifai, art:Clarifai, adult:Clarifai, dress:Clarifai, traditional:Clarifai, jacket:Clarifai, retro:Clarifai, costume:Clarifai, girl:Clarifai, one:Clarifai, elegant:Clarifai, christmas:Clarifai, womens red and brown long sleeve dress:CloudSight, red and gold traditional dress on white background:CloudSight Hybrid, clothing:Google Vision, outerwear:Google Vision, red:Google Vision, sleeve:Google Vision, maroon:Google Vision, robe:Google Vision, fur:Google Vision, coat:Google Vision, velvet:Google Vision, jacket:Google Vision, clothing:Amazon Rekognition, apparel:Amazon Rekognition, costume:Amazon Rekognition, overcoat:Amazon Rekognition, coat:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, sleeve:Amazon Rekognition, long sleeve:Amazon Rekognition, toy:Amazon Rekognition, fashion:Amazon Rekognition, doll:Amazon Rekognition, fur:IBM Visual Recognition, garment:IBM Visual Recognition, overgarment:IBM Visual Recognition, jabot (ruffle of dress):IBM Visual Recognition, dolman jacket:IBM Visual Recognition, coat:IBM Visual Recognition, coating:IBM Visual Recognition, clothing:IBM Visual Recognition, fabric:IBM Visual Recognition, dark red color:IBM Visual Recognition, indian red color:IBM Visual Recognition, a woman wearing a red dress standing in front of a coat:Microsoft Computer Vision, red:Microsoft Computer Vision, person:Microsoft Computer Vision, coat:Microsoft Computer Vision, clothing:Microsoft Computer Vision, wearing:Microsoft Computer Vision, woman:Microsoft Computer Vision, dressed:Microsoft Computer Vision, phone:Microsoft Computer Vision, cellphone:Microsoft Computer Vision, dress:Microsoft Computer Vision, looking:Microsoft Computer Vision, jacket:Microsoft Computer Vision, lady:Microsoft Computer Vision, hat:Microsoft Computer Vision, standing:Microsoft Computer Vision, outfit:Microsoft Computer Vision, walking:Microsoft Computer Vision, snow:Microsoft Computer Vision, holding:Microsoft Computer Vision, talking:Microsoft Computer Vision, suit:Microsoft Computer Vision, field:Microsoft Computer Vision, covered:Microsoft Computer Vision, large:Microsoft Computer Vision, white:Microsoft Computer Vision, head:Microsoft Computer Vision, shirt:Microsoft Computer Vision, street:Microsoft Computer Vision, skiing:Microsoft Computer Vision, umbrella:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, statue:Clarifai, ancient:Clarifai, buddha:Clarifai, religion:Clarifai, no person:Clarifai, temple:Clarifai, veil:Clarifai, travel:Clarifai, old:Clarifai, god:Clarifai, figurine:Clarifai, culture:Clarifai, museum:Clarifai, archaeology:Clarifai, grave:Clarifai, antique:Clarifai, spirituality:Clarifai, stone:Clarifai, gray and black ceramic figurine:CloudSight, concrete statue:CloudSight Hybrid, sculpture:Google Vision, statue:Google Vision, stone carving:Google Vision, classical sculpture:Google Vision, art:Google Vision, forehead:Google Vision, monument:Google Vision, artifact:Google Vision, stock photography:Google Vision, temple:Google Vision, person:Amazon Rekognition, human:Amazon Rekognition, sculpture:Amazon Rekognition, art:Amazon Rekognition, statue:Amazon Rekognition, archaeology:Amazon Rekognition, figurine:Amazon Rekognition, kneeling:Amazon Rekognition, socle:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, stele (stone slab with markings):IBM Visual Recognition, ancient person:IBM Visual Recognition, person:IBM Visual Recognition, sculpture:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a statue of a person:Microsoft Computer Vision, old:Microsoft Computer Vision, sitting:Microsoft Computer Vision, standing:Microsoft Computer Vision, man:Microsoft Computer Vision, suit:Microsoft Computer Vision, wearing:Microsoft Computer Vision, green:Microsoft Computer Vision, brown:Microsoft Computer Vision, gray:Microsoft Computer Vision, clock:Microsoft Computer Vision, tower:Microsoft Computer Vision, statue:Microsoft Computer Vision, large:Microsoft Computer Vision, tall:Microsoft Computer Vision, stone:Microsoft Computer Vision, hat:Microsoft Computer Vision, luggage:Microsoft Computer Vision, brick:Microsoft Computer Vision, white:Microsoft Computer Vision, stacked:Microsoft Computer Vision",
		"art:Clarifai, pattsern:Clarifai, decoration:Clarifai, flower:Clarifai, texture:Clarifai, retro:Clarifai, design:Clarifai, desktop:Clarifai, abstract:Clarifai, vintage:Clarifai, antique:Clarifai, floral:Clarifai, illustration:Clarifai, textile:Clarifai, style:Clarifai, old:Clarifai, handicraft:Clarifai, fabric:Clarifai, ornate:Clarifai, handmade:Clarifai, green:CloudSight, red:CloudSight, and yellow floral textile:CloudSight, brown and green dragon graphic carpet:CloudSight Hybrid, pattern:Google Vision, textile:Google Vision, motif:Google Vision, visual arts:Google Vision, art:Google Vision, paisley:Google Vision, rug:Google Vision, pattern:Google Vision, rug:Amazon Rekognition, pattern:Amazon Rekognition, art:Amazon Rekognition, applique:Amazon Rekognition, paisley:Amazon Rekognition, tapestry:IBM Visual Recognition, fabric:IBM Visual Recognition, rug:IBM Visual Recognition, floor cover:IBM Visual Recognition, scatter rug:IBM Visual Recognition, paisley fabric:IBM Visual Recognition, olive green color:IBM Visual Recognition, a fabric surface:Microsoft Computer Vision, clothing:Microsoft Computer Vision, fabric:Microsoft Computer Vision, rug:Microsoft Computer Vision",
		"art:Clarifai, vintage:Clarifai, painting:Clarifai, lid:Clarifai, people:Clarifai, one:Clarifai, retro:Clarifai, man:Clarifai, fall:Clarifai, tree:Clarifai, woman:Clarifai, old:Clarifai, portrait:Clarifai, adult:Clarifai, antique:Clarifai, nature:Clarifai, illustration:Clarifai, wear:Clarifai, veil:Clarifai, color:Clarifai, man in black suit painting:CloudSight, man wearing magician hat painting:CloudSight Hybrid, painting:Google Vision, lady:Google Vision, portrait:Google Vision, art:Google Vision, standing:Google Vision, visual arts:Google Vision, self-portrait:Google Vision, artist:Google Vision, clothing:Amazon Rekognition, apparel:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, painting:Amazon Rekognition, art:Amazon Rekognition, people:Amazon Rekognition, hat:Amazon Rekognition, golf:IBM Visual Recognition, athletic game:IBM Visual Recognition, sport:IBM Visual Recognition, cassock:IBM Visual Recognition, gown:IBM Visual Recognition, outerwear:IBM Visual Recognition, frock coat:IBM Visual Recognition, coat:IBM Visual Recognition, overgarment:IBM Visual Recognition, garment:IBM Visual Recognition, person:IBM Visual Recognition, clothing:IBM Visual Recognition, olive green color:IBM Visual Recognition, coal black color:IBM Visual Recognition, a man that is standing in the grass:Microsoft Computer Vision, grass:Microsoft Computer Vision, man:Microsoft Computer Vision, outdoor:Microsoft Computer Vision, person:Microsoft Computer Vision, standing:Microsoft Computer Vision, field:Microsoft Computer Vision, building:Microsoft Computer Vision, cellphone:Microsoft Computer Vision, phone:Microsoft Computer Vision, holding:Microsoft Computer Vision, wearing:Microsoft Computer Vision, black:Microsoft Computer Vision, walking:Microsoft Computer Vision, young:Microsoft Computer Vision, park:Microsoft Computer Vision, baseball:Microsoft Computer Vision, street:Microsoft Computer Vision, ball:Microsoft Computer Vision, white:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, mammal:Clarifai, no person:Clarifai, lion:Clarifai, statue:Clarifai, museum:Clarifai, figurine:Clarifai, bronze:Clarifai, animal:Clarifai, metalwork:Clarifai, deer:Clarifai, ancient:Clarifai, one:Clarifai, dog:Clarifai, cavalry:Clarifai, nude:Clarifai, wildlife:Clarifai, illustration:Clarifai, reindeer:Clarifai, brown wooden horse head figurine:CloudSight, brass-colored lion figurine:CloudSight Hybrid, sculpture:Google Vision, bronze sculpture:Google Vision, animal figure:Google Vision, metal:Google Vision, bronze:Google Vision, brass:Google Vision, figurine:Google Vision, canidae:Google Vision, carnivore:Google Vision, ancient dog breeds:Google Vision, figurine:Amazon Rekognition, bronze:Amazon Rekognition, mammal:Amazon Rekognition, wildlife:Amazon Rekognition, animal:Amazon Rekognition, antelope:Amazon Rekognition, horse:Amazon Rekognition, art:Amazon Rekognition, sculpture:Amazon Rekognition, musical instrument:Amazon Rekognition, brass section:Amazon Rekognition, cushion:Amazon Rekognition, wood:Amazon Rekognition, furniture:Amazon Rekognition, andiron (used in fireplace):IBM Visual Recognition, support:IBM Visual Recognition, gilt (golden faced):IBM Visual Recognition, coating:IBM Visual Recognition, saber-toothed tiger:IBM Visual Recognition, big cat:IBM Visual Recognition, feline:IBM Visual Recognition, carnivore:IBM Visual Recognition, mammal:IBM Visual Recognition, animal:IBM Visual Recognition, artifact:IBM Visual Recognition, light brown color:IBM Visual Recognition, a close up of a dog:Microsoft Computer Vision, dog:Microsoft Computer Vision, brown:Microsoft Computer Vision, sitting:Microsoft Computer Vision, zebra:Microsoft Computer Vision, standing:Microsoft Computer Vision, playing:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"weapon:Clarifai, gun:Clarifai, still life:Clarifai, art:Clarifai, no person:Clarifai, vintage:Clarifai, cutout:Clarifai, retro:Clarifai, pistol:Clarifai, old:Clarifai, one:Clarifai, studio:Clarifai, metalwork:Clarifai, antique:Clarifai, wear:Clarifai, furniture:Clarifai, steel:Clarifai, mammal:Clarifai, military:Clarifai, people:Clarifai, white and brown wooden ship scale model:CloudSight, two white flintlocks:CloudSight Hybrid, gun:Google Vision, firearm:Google Vision, bow and arrow:Google Vision, trigger:Google Vision, ranged weapon:Google Vision, rifle:Google Vision, bow:Google Vision, wood:Google Vision, crossbow:Google Vision, shotgun:Google Vision, weapon:Amazon Rekognition, weaponry:Amazon Rekognition, gun:Amazon Rekognition, handgun:Amazon Rekognition, rifle:Amazon Rekognition, flintlock gun:IBM Visual Recognition, matchlock:IBM Visual Recognition, muzzle loader gun:IBM Visual Recognition, firearm:IBM Visual Recognition, gun:IBM Visual Recognition, weapon:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a close up of a gun:Microsoft Computer Vision, thing:Microsoft Computer Vision, gun:Microsoft Computer Vision, weapon:Microsoft Computer Vision, sitting:Microsoft Computer Vision, table:Microsoft Computer Vision, small:Microsoft Computer Vision, water:Microsoft Computer Vision, black:Microsoft Computer Vision, boat:Microsoft Computer Vision, laying:Microsoft Computer Vision, air:Microsoft Computer Vision, white:Microsoft Computer Vision",
		"no person:Clarifai, metalwork:Clarifai, art:Clarifai, furniture:Clarifai, antique:Clarifai, gold:Clarifai, ornate:Clarifai, luxury:Clarifai, gilt:Clarifai, ancient:Clarifai, bronze:Clarifai, carpentry:Clarifai, wealth:Clarifai, old:Clarifai, brass:Clarifai, baroque:Clarifai, classic:Clarifai, castle:Clarifai, architecture:Clarifai, victorian:Clarifai, brown wooden wall mount rack:CloudSight, brass-colored container:CloudSight Hybrid, table:Google Vision, furniture:Google Vision, brass:Google Vision, metal:Google Vision, bronze:Google Vision, antique:Google Vision, coffee table:Google Vision, end table:Google Vision, games:Google Vision, miniature:Google Vision, furniture:Amazon Rekognition, treasure:Amazon Rekognition, cabinet:Amazon Rekognition, bronze:Amazon Rekognition, tabletop:Amazon Rekognition, gold:Amazon Rekognition, crib:Amazon Rekognition, settee (bench):IBM Visual Recognition, bench:IBM Visual Recognition, seat:IBM Visual Recognition, furniture:IBM Visual Recognition, sheraton furniture:IBM Visual Recognition, dressing table:IBM Visual Recognition, table:IBM Visual Recognition, sideboard (counter):IBM Visual Recognition, reddish brown color:IBM Visual Recognition, olive green color:IBM Visual Recognition, a gold clock sitting on top of a table:Microsoft Computer Vision, table:Microsoft Computer Vision, small:Microsoft Computer Vision, metal:Microsoft Computer Vision, gold:Microsoft Computer Vision, sitting:Microsoft Computer Vision, clock:Microsoft Computer Vision, hanging:Microsoft Computer Vision, room:Microsoft Computer Vision, old:Microsoft Computer Vision, white:Microsoft Computer Vision, water:Microsoft Computer Vision, standing:Microsoft Computer Vision",
		"architecture:Clarifai, travel:Clarifai, building:Clarifai, art:Clarifai, people:Clarifai, city:Clarifai, street:Clarifai, group:Clarifai, cathedral:Clarifai, church:Clarifai, tower:Clarifai, religion:Clarifai, bridge:Clarifai, many:Clarifai, no person:Clarifai, plaza:Clarifai, town:Clarifai, urban:Clarifai, sunset:Clarifai, sky:Clarifai, brown wooden framed painting of house:CloudSight, venice- 16th cenutry:CloudSight Hybrid, othello by emma thornton on prezi:CloudSight Hybrid, landmark:Google Vision, city:Google Vision, human settlement:Google Vision, public space:Google Vision, town square:Google Vision, town:Google Vision, architecture:Google Vision, building:Google Vision, clock tower:Google Vision, plaza:Google Vision, building:Amazon Rekognition, architecture:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, art:Amazon Rekognition, painting:Amazon Rekognition, tower:Amazon Rekognition, urban:Amazon Rekognition, town:Amazon Rekognition, city:Amazon Rekognition, downtown:Amazon Rekognition, lighthouse:Amazon Rekognition, beacon:Amazon Rekognition, temple:Amazon Rekognition, shrine:Amazon Rekognition, worship:Amazon Rekognition, landscape:Amazon Rekognition, nature:Amazon Rekognition, panoramic:Amazon Rekognition, outdoors:Amazon Rekognition, scenery:Amazon Rekognition, bell tower:Amazon Rekognition, column:Amazon Rekognition, pillar:Amazon Rekognition, religious building:IBM Visual Recognition, building:IBM Visual Recognition, belfry tower:IBM Visual Recognition, tower:IBM Visual Recognition, mecca:IBM Visual Recognition, blue color:IBM Visual Recognition, a group of people walking in front of piazza san marco:Microsoft Computer Vision, building:Microsoft Computer Vision, outdoor:Microsoft Computer Vision, standing:Microsoft Computer Vision, walking:Microsoft Computer Vision, sheep:Microsoft Computer Vision, city:Microsoft Computer Vision, large:Microsoft Computer Vision, group:Microsoft Computer Vision, people:Microsoft Computer Vision, front:Microsoft Computer Vision, snow:Microsoft Computer Vision, horse:Microsoft Computer Vision, clock:Microsoft Computer Vision, old:Microsoft Computer Vision, rug:Microsoft Computer Vision, street:Microsoft Computer Vision, man:Microsoft Computer Vision, many:Microsoft Computer Vision, riding:Microsoft Computer Vision, tower:Microsoft Computer Vision, water:Microsoft Computer Vision, flock:Microsoft Computer Vision, herd:Microsoft Computer Vision",
		"illustration:Clarifai, art:Clarifai, religion:Clarifai, god:Clarifai, narrative:Clarifai, vintage:Clarifai, painting:Clarifai, picture frame:Clarifai, retro:Clarifai, aura:Clarifai, old:Clarifai, ancient:Clarifai, woman:Clarifai, desktop:Clarifai, culture:Clarifai, spirituality:Clarifai, manuscript:Clarifai, design:Clarifai, baby:Clarifai, style:Clarifai, woman in white dress painting:CloudSight, woman and man painting:CloudSight Hybrid, painting:Google Vision, art:Google Vision, illustration:Google Vision, miniature:Google Vision, visual arts:Google Vision, fictional character:Google Vision, human:Amazon Rekognition, person:Amazon Rekognition, art:Amazon Rekognition, mail:Amazon Rekognition, envelope:Amazon Rekognition, painting:Amazon Rekognition, prayer:Amazon Rekognition, worship:Amazon Rekognition, greeting card:Amazon Rekognition, tapestry:IBM Visual Recognition, fabric:IBM Visual Recognition, picture frame:IBM Visual Recognition, framework:IBM Visual Recognition, supporting structure:IBM Visual Recognition, shadow box:IBM Visual Recognition, box:IBM Visual Recognition, light brown color:IBM Visual Recognition, beige color:IBM Visual Recognition, a close up of a book:Microsoft Computer Vision, text:Microsoft Computer Vision, photo:Microsoft Computer Vision, old:Microsoft Computer Vision, sitting:Microsoft Computer Vision, book:Microsoft Computer Vision, table:Microsoft Computer Vision, suitcase:Microsoft Computer Vision, luggage:Microsoft Computer Vision, brown:Microsoft Computer Vision, bear:Microsoft Computer Vision, computer:Microsoft Computer Vision, stuffed:Microsoft Computer Vision",
		"furniture:Clarifai, metalwork:Clarifai, no person:Clarifai, art:Clarifai, ornate:Clarifai, antique:Clarifai, inlay:Clarifai, carpentry:Clarifai, painting:Clarifai, wood:Clarifai, gold:Clarifai, container:Clarifai, decoration:Clarifai, cabinet:Clarifai, ancient:Clarifai, one:Clarifai, illustration:Clarifai, ebony:Clarifai, old:Clarifai, bronze:Clarifai, brown wooden single pedestal desk:CloudSight, brown and black wooden cabinet:CloudSight Hybrid, furniture:Google Vision, antique:Google Vision, table:Google Vision, desk:Google Vision, napoleon iii style:Google Vision, nightstand:Google Vision, end table:Google Vision, drawer:Google Vision, furniture:Amazon Rekognition, sideboard:Amazon Rekognition, table:Amazon Rekognition, desk:Amazon Rekognition, tabletop:Amazon Rekognition, cabinet:Amazon Rekognition, drawer:Amazon Rekognition, lowboy:IBM Visual Recognition, furniture:IBM Visual Recognition, davenport desk:IBM Visual Recognition, table:IBM Visual Recognition, marquetry (veneers):IBM Visual Recognition, boulle (furniture):IBM Visual Recognition, reddish brown color:IBM Visual Recognition, a wooden table:Microsoft Computer Vision, indoor:Microsoft Computer Vision, table:Microsoft Computer Vision, small:Microsoft Computer Vision, old:Microsoft Computer Vision, sitting:Microsoft Computer Vision, wooden:Microsoft Computer Vision, room:Microsoft Computer Vision, bed:Microsoft Computer Vision, living:Microsoft Computer Vision, large:Microsoft Computer Vision, carriage:Microsoft Computer Vision",
		"no person:Clarifai, glass:Clarifai, glass items:Clarifai, still life:Clarifai, wine:Clarifai, h2o:Clarifai, bottle:Clarifai, trophy:Clarifai, vodka:Clarifai, reflection:Clarifai, victory:Clarifai, antique:Clarifai, drink:Clarifai, empty:Clarifai, cup:Clarifai, retro:Clarifai, luxury:Clarifai, classic:Clarifai, container:Clarifai, old:Clarifai, clear glass base table lamp:CloudSight, clear glass footed beverage dispenser:CloudSight Hybrid, product:Google Vision, glass:Google Vision, still life photography:Google Vision, metal:Google Vision, barware:Google Vision, silver:Google Vision, silver:Google Vision, lamp:Amazon Rekognition, glass:Amazon Rekognition, lantern:Amazon Rekognition, goblet:Amazon Rekognition, lighting:Amazon Rekognition, censer container:IBM Visual Recognition, samovar urn:IBM Visual Recognition, pot:IBM Visual Recognition, porringer bowl:IBM Visual Recognition, bowl:IBM Visual Recognition, tableware:IBM Visual Recognition, utensil:IBM Visual Recognition, oil lamp:IBM Visual Recognition, lamp:IBM Visual Recognition, gray color:IBM Visual Recognition, ivory color:IBM Visual Recognition, a tall glass vase on a table:Microsoft Computer Vision, indoor:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, small:Microsoft Computer Vision, vase:Microsoft Computer Vision, glass:Microsoft Computer Vision, black:Microsoft Computer Vision, lamp:Microsoft Computer Vision, white:Microsoft Computer Vision, clock:Microsoft Computer Vision, desk:Microsoft Computer Vision, flower:Microsoft Computer Vision, holding:Microsoft Computer Vision, clear:Microsoft Computer Vision, bottle:Microsoft Computer Vision, display:Microsoft Computer Vision, room:Microsoft Computer Vision, tall:Microsoft Computer Vision",
		"people:Clarifai, illustration:Clarifai, no person:Clarifai, education:Clarifai, man:Clarifai, school:Clarifai, art:Clarifai, furniture:Clarifai, indoors:Clarifai, wood:Clarifai, painting:Clarifai, business:Clarifai, print:Clarifai, room:Clarifai, travel:Clarifai, container:Clarifai, chalk:Clarifai, adult:Clarifai, study:Clarifai, retro:Clarifai, brown wooden framed wall decor:CloudSight, black 3-panel wooden room divider with art:CloudSight Hybrid, modern art:Google Vision, art:Google Vision, banner:Google Vision, furniture:Google Vision, calligraphy:Google Vision, room divider:Google Vision, visual arts:Google Vision, metal:Google Vision, rectangle:Google Vision, electronics:Amazon Rekognition, screen:Amazon Rekognition, monitor:Amazon Rekognition, display:Amazon Rekognition, advertisement:Amazon Rekognition, lcd screen:Amazon Rekognition, billboard:Amazon Rekognition, shop:Amazon Rekognition, screen:IBM Visual Recognition, indoors:IBM Visual Recognition, marquetry (veneers):IBM Visual Recognition, multi panel pictures/art:IBM Visual Recognition, passe-partout (frame):IBM Visual Recognition, framework:IBM Visual Recognition, supporting structure:IBM Visual Recognition, pale yellow color:IBM Visual Recognition, a close up of a sign:Microsoft Computer Vision, room:Microsoft Computer Vision, photo:Microsoft Computer Vision, black:Microsoft Computer Vision, table:Microsoft Computer Vision, wooden:Microsoft Computer Vision, sign:Microsoft Computer Vision, refrigerator:Microsoft Computer Vision, kitchen:Microsoft Computer Vision, computer:Microsoft Computer Vision",
		"retro:Clarifai, no person:Clarifai, antique:Clarifai, classic:Clarifai, leather:Clarifai, container:Clarifai, handmade:Clarifai, vintage:Clarifai, old:Clarifai, elegant:Clarifai, handle:Clarifai, luxury:Clarifai, style:Clarifai, wood:Clarifai, arts and crafts:Clarifai, fashion:Clarifai, art:Clarifai, isolated:Clarifai, one:Clarifai, brass:Clarifai, brown and black floral leather tote bag:CloudSight, gold and black floral watering can:CloudSight Hybrid, bag:Google Vision, handbag:Google Vision, brown:Google Vision, fashion accessory:Google Vision, shoulder bag:Google Vision, bag:Amazon Rekognition, accessories:Amazon Rekognition, accessory:Amazon Rekognition, handbag:Amazon Rekognition, watering can:Amazon Rekognition, can:Amazon Rekognition, tin:Amazon Rekognition, pottery:Amazon Rekognition, pot:Amazon Rekognition, handbag:IBM Visual Recognition, coal scuttle:IBM Visual Recognition, carpetbag:IBM Visual Recognition, traveling bag:IBM Visual Recognition, luggage:IBM Visual Recognition, purse:IBM Visual Recognition, bag:IBM Visual Recognition, accessory:IBM Visual Recognition, clothing:IBM Visual Recognition, light brown color:IBM Visual Recognition, beige color:IBM Visual Recognition, indoor:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, cup:Microsoft Computer Vision, small:Microsoft Computer Vision, coffee:Microsoft Computer Vision, piece:Microsoft Computer Vision, decorated:Microsoft Computer Vision, vase:Microsoft Computer Vision, wooden:Microsoft Computer Vision, black:Microsoft Computer Vision, flower:Microsoft Computer Vision, cake:Microsoft Computer Vision, banana:Microsoft Computer Vision, plate:Microsoft Computer Vision, bag:Microsoft Computer Vision, fruit:Microsoft Computer Vision, board:Microsoft Computer Vision, water:Microsoft Computer Vision, white:Microsoft Computer Vision",
		"saint:Clarifai, religion:Clarifai, art:Clarifai, mary:Clarifai, church:Clarifai, painting:Clarifai, god:Clarifai, kneeling:Clarifai, people:Clarifai, book:Clarifai, cross:Clarifai, chapel:Clarifai, veil:Clarifai, cathedral:Clarifai, throne:Clarifai, aura:Clarifai, group:Clarifai, apostle:Clarifai, renaissance:Clarifai, gown (clothing):Clarifai, brown wooden framed wall decor:CloudSight, religious painting:CloudSight Hybrid, holy places:Google Vision, painting:Google Vision, architecture:Google Vision, art:Google Vision, altar:Google Vision, history:Google Vision, stock photography:Google Vision, statue:Google Vision, middle ages:Google Vision, arch:Google Vision, person:Amazon Rekognition, human:Amazon Rekognition, art:Amazon Rekognition, painting:Amazon Rekognition, architecture:Amazon Rekognition, building:Amazon Rekognition, altar:Amazon Rekognition, church:Amazon Rekognition, person:IBM Visual Recognition, altarpiece:IBM Visual Recognition, screen:IBM Visual Recognition, indoors:IBM Visual Recognition, indian red color:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a group of people sitting on a bench posing for the camera:Microsoft Computer Vision, building:Microsoft Computer Vision, bench:Microsoft Computer Vision, sitting:Microsoft Computer Vision, photo:Microsoft Computer Vision, standing:Microsoft Computer Vision, man:Microsoft Computer Vision, people:Microsoft Computer Vision, group:Microsoft Computer Vision, posing:Microsoft Computer Vision, wooden:Microsoft Computer Vision, old:Microsoft Computer Vision, water:Microsoft Computer Vision, woman:Microsoft Computer Vision",
		"classical music:Clarifai, violin:Clarifai, no person:Clarifai, classic:Clarifai, music:Clarifai, wood:Clarifai, artistic:Clarifai, instrument:Clarifai, art:Clarifai, bowed stringed instrument:Clarifai, sound:Clarifai, cello:Clarifai, orchestra:Clarifai, musician:Clarifai, antique:Clarifai, viola:Clarifai, retro:Clarifai, carpentry:Clarifai, one:Clarifai, old:Clarifai, brown and black violin with bow:CloudSight, brown violin:CloudSight Hybrid, string instrument:Google Vision, musical instrument:Google Vision, string instrument:Google Vision, violin:Google Vision, viola:Google Vision, violin family:Google Vision, bowed string instrument:Google Vision, cello:Google Vision, violone:Google Vision, viol:Google Vision, leisure activities:Amazon Rekognition, musical instrument:Amazon Rekognition, violin:Amazon Rekognition, fiddle:Amazon Rekognition, viola:Amazon Rekognition, cello:Amazon Rekognition, guitar:Amazon Rekognition, viol:IBM Visual Recognition, bowed stringed instrument:IBM Visual Recognition, stringed instrument:IBM Visual Recognition, musical instrument:IBM Visual Recognition, viola da gamba:IBM Visual Recognition, 'viola damore':IBM Visual Recognition, viola:IBM Visual Recognition, reddish brown color:IBM Visual Recognition, a close up of a violin:Microsoft Computer Vision, instrument:Microsoft Computer Vision, music:Microsoft Computer Vision, violin:Microsoft Computer Vision, brown:Microsoft Computer Vision, cello:Microsoft Computer Vision, orange:Microsoft Computer Vision",
		"art:Clarifai, people:Clarifai, woman:Clarifai, painting:Clarifai, print:Clarifai, portrait:Clarifai, vintage:Clarifai, nude:Clarifai, one:Clarifai, baby:Clarifai, retro:Clarifai, adult:Clarifai, illustration:Clarifai, decoration:Clarifai, furniture:Clarifai, antique:Clarifai, interior:Clarifai, girl:Clarifai, family:Clarifai, old:Clarifai, womens black hair:CloudSight, woman combing her hair holding hand mirror painting:CloudSight Hybrid, painting:Google Vision, lady:Google Vision, art:Google Vision, picture frame:Google Vision, fictional character:Google Vision, still life:Google Vision, photography:Google Vision, long hair:Google Vision, visual arts:Google Vision, modern art:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, painting:IBM Visual Recognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, kisser:IBM Visual Recognition, person:IBM Visual Recognition, beige color:IBM Visual Recognition, a person holding a cat:Microsoft Computer Vision, indoor:Microsoft Computer Vision, person:Microsoft Computer Vision, sitting:Microsoft Computer Vision, looking:Microsoft Computer Vision, cat:Microsoft Computer Vision, holding:Microsoft Computer Vision, man:Microsoft Computer Vision, woman:Microsoft Computer Vision, brown:Microsoft Computer Vision, hair:Microsoft Computer Vision, playing:Microsoft Computer Vision, phone:Microsoft Computer Vision, dog:Microsoft Computer Vision, mouth:Microsoft Computer Vision, white:Microsoft Computer Vision, teeth:Microsoft Computer Vision, laying:Microsoft Computer Vision, room:Microsoft Computer Vision, bed:Microsoft Computer Vision, standing:Microsoft Computer Vision, brushing:Microsoft Computer Vision, stuffed:Microsoft Computer Vision",
		"illustration:Clarifai, art:Clarifai, painting:Clarifai, print:Clarifai, fish:Clarifai, animal:Clarifai, people:Clarifai, prehistoric:Clarifai, bird:Clarifai, ancient:Clarifai, old:Clarifai, engraving:Clarifai, vintage:Clarifai, pattern:Clarifai, design:Clarifai, mammal:Clarifai, religion:Clarifai, elephant:Clarifai, antique:Clarifai, symbol:Clarifai, blue and brown wooden wall decor:CloudSight, painting of angel over fish:CloudSight Hybrid, painting:Google Vision, art:Google Vision, illustration:Google Vision, visual arts:Google Vision, history:Google Vision, fictional character:Google Vision, prophet:Google Vision, tapestry:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, clothing:Amazon Rekognition, apparel:Amazon Rekognition, drawing:Amazon Rekognition, tapestry:IBM Visual Recognition, fabric:IBM Visual Recognition, rug:IBM Visual Recognition, floor cover:IBM Visual Recognition, beige color:IBM Visual Recognition, olive green color:IBM Visual Recognition, a painting of a book:Microsoft Computer Vision, text:Microsoft Computer Vision, book:Microsoft Computer Vision, photo:Microsoft Computer Vision, sitting:Microsoft Computer Vision, holding:Microsoft Computer Vision, old:Microsoft Computer Vision, painting:Microsoft Computer Vision, man:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, woman:Microsoft Computer Vision, table:Microsoft Computer Vision, elephant:Microsoft Computer Vision, bed:Microsoft Computer Vision, bear:Microsoft Computer Vision, laying:Microsoft Computer Vision, people:Microsoft Computer Vision, riding:Microsoft Computer Vision",
		"water:Clarifai, watercraft:Clarifai, boat:Clarifai, fisherman:Clarifai, rowboat:Clarifai, transportation system:Clarifai, fishing boat:Clarifai, travel:Clarifai, sea:Clarifai, people:Clarifai, vehicle:Clarifai, ocean:Clarifai, canoe:Clarifai, beach:Clarifai, ship:Clarifai, seashore:Clarifai, river:Clarifai, lake:Clarifai, no person:Clarifai, fish:Clarifai, brown and white sailing boat painting:CloudSight, brown boat:CloudSight Hybrid, boat:Google Vision, water transportation:Google Vision, vehicle:Google Vision, painting:Google Vision, watercolor paint:Google Vision, watercraft:Google Vision, art:Google Vision, boating:Google Vision, transportation:Amazon Rekognition, vehicle:Amazon Rekognition, boat:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, art:Amazon Rekognition, painting:Amazon Rekognition, jolly boat:IBM Visual Recognition, small boat:IBM Visual Recognition, boat:IBM Visual Recognition, watercraft:IBM Visual Recognition, craft:IBM Visual Recognition, vehicle:IBM Visual Recognition, sampan skif:IBM Visual Recognition, dugout canoe:IBM Visual Recognition, sea green color:IBM Visual Recognition, a small boat in a body of water:Microsoft Computer Vision, boat:Microsoft Computer Vision, water:Microsoft Computer Vision, outdoor:Microsoft Computer Vision, small:Microsoft Computer Vision, sitting:Microsoft Computer Vision, old:Microsoft Computer Vision, black:Microsoft Computer Vision, man:Microsoft Computer Vision, row:Microsoft Computer Vision, lake:Microsoft Computer Vision, body:Microsoft Computer Vision, people:Microsoft Computer Vision, white:Microsoft Computer Vision, parked:Microsoft Computer Vision, table:Microsoft Computer Vision, woman:Microsoft Computer Vision, floating:Microsoft Computer Vision, large:Microsoft Computer Vision, riding:Microsoft Computer Vision, bowl:Microsoft Computer Vision, group:Microsoft Computer Vision, standing:Microsoft Computer Vision, city:Microsoft Computer Vision, river:Microsoft Computer Vision, docked:Microsoft Computer Vision, snow:Microsoft Computer Vision",
	]

	var art_weight = []


	// CATEGORIZED BY SERVICE

	var art_cats = []

	for (var i = 0; i < art_raw_cats.length; i++) {
		piece_cats = art_raw_cats[i]
		split_cats = piece_cats.split(", ")
		art_cats.push(split_cats)

		piece_weight = art_raw[i]
		split_weight = piece_weight.split(", ")
		art_weight.push(split_weight)
	};

	// console.log("art_weight LIST")
	// console.log(art_weight)

	console.log("cats")
	console.log(art_cats.length)
	console.log("weight")
	console.log(art_weight.length)

	count = 0
	for (var i = 0; i < art_cats.length; i++) {
		piece_cats = art_cats[i]

		piece_weight = art_weight[i]

		print_tags(count.toString(), piece_cats, piece_weight)
		count += 1
	};

	function print_tags(div, piece, piece_weighted) {

		console.log("Printing tags")

		services = ["Clarifai", "CloudSight", "CloudSight_Hybrid", "Google_Vision", "Amazon_Rekognition", "IBM_Visual_Recognition", "Microsoft_Computer_Vision"]

//		 Clarifai, CloudSight, Google_Vision, Amazon_Rekognition, IBM_Visual_Recognition, Microsoft_Computer_Vision

		master = {"Clarifai":[], "CloudSight":[], "CloudSight_Hybrid":[], "Google_Vision":[], "Amazon_Rekognition":[], "IBM_Visual_Recognition":[], "Microsoft_Computer_Vision":[]}


		weight_dict = {}

		for (var i = 0; i < piece_weighted.length; i++) {

			touple_weight = piece_weighted[i]
			singles_weight = touple_weight.split(": ")

			weight_dict[singles_weight[0]] = parseInt(singles_weight[1])
		}


		console.log("dictionary")
		console.log(weight_dict)

		graph_id = div + "_pie"

		//create_graphs(graph_id, weight_dict)
		//create_graphs_bar(graph_id, weight_dict)

		for (var i = 0; i < piece.length; i++) {

			touple = piece[i]

			singles = touple.split(":")

			// singles[0] - the tag, singles_weight[1] - the weight
			tag_and_weight = singles[0]

			// singles[1] - the service
			service = singles[1].replace(/ /g, "_")

			// current values of list
			curs = []

			// list to be copied over
			news = []

			curs = master[service]

			for (var j = 0; j < curs.length; j++) {
				news.push(curs[j])
			}

			news.push(tag_and_weight)

			master[service] = news

		}



		for (var i = 0; i < services.length; i++) {

			tags = master[services[i]]

			id = "#" + services[i] + "_" + div
			update_tags(services[i], tags, id, weight_dict)

		}		

		
	};

	function update_tags(service, tags, id, weight_dict) {


		color_dict = ["#616161", "#fab95b", "#ff502f", "#009975", "#454d66", "#7572f4", "#207dff"]

		html_output = "<p>"

		for (var j = 0; j < tags.length; j++) {

			weight = weight_dict[tags[j]]


			color = "<span style='color:" + color_dict[weight - 1] + "'>"

			//html_output += tags[j]

			html_output += color + tags[j] + "</span>"


			if (j != tags.length - 1) {
				html_output += ", "
			}
		}

		html_output += "</p>"


		$(id).html(html_output);
	}

	function create_graphs(id, weight_dict) {

		tags = []
		weights = []

		for (var key in weight_dict) {
		    // check if the property/key is defined in the object itself, not in parent
		    if (weight_dict.hasOwnProperty(key)) {           
		        console.log(key, weight_dict[key]);
		        tags.push(key)
		        weights.push(weight_dict[key])
		    }
		}




	  	var ctxP = document.getElementById(id).getContext('2d');
	  	var myPieChart = new Chart(ctxP, {
	    	type: 'pie',
	    	data: {
	      		labels: tags,
	      		datasets: [{
	        		data: weights,
	        		// backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
	        		// hoverBackgroundColor: ["#FF5A5E", "#5AD3D1", "#FFC870", "#A8B3C5", "#616774"]
	      		}]
	    	},
	    	options: {
	    		legend: {
		            display: true,
		            position: 'left'
		         },
		        plugins: {
			      	colorschemes: {
			        	scheme: 'tableau.Tableau20'
			      	}
			    },
		    	
				
	      		responsive: true
	    	},
		});

	}

	function create_graphs_bar(id, weight_dict) {

		tags = []
		weights = []

		for (var key in weight_dict) {
		    // check if the property/key is defined in the object itself, not in parent
		    if (weight_dict.hasOwnProperty(key)) {           
		        console.log(key, weight_dict[key]);
		        tags.push(key)
		        weights.push(weight_dict[key])
		    }
		}
		var ctx = document.getElementById(id).getContext('2d');

		var myBarChart = new Chart(ctx, {
		    type: 'horizontalBar',
	    	data: {
	      		labels: tags,
	      		datasets: [{
	        		data: weights,
	        		// backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
	        		// hoverBackgroundColor: ["#FF5A5E", "#5AD3D1", "#FFC870", "#A8B3C5", "#616774"]
	      		}]
	    	},
		});
	}
});


