$(document).ready(function(){





	var art_raw = [
		"sculpture: 5, statue: 3, art: 3, person: 3, man: 2, old: 2, stone: 2, standing: 2, figurine: 2, nude: 1, marble: 1, figure: 1, ancient: 1, monument: 1, museum: 1, people: 1, carve: 1, no person: 1, architecture: 1, renaissance: 1, anatomy: 1, artistic: 1, classic: 1, man and woman ceramic figurine: 1, nude man statue: 1, classical sculpture: 1, male: 1, muscle: 1, human body: 1, chest: 1, human: 1, archaeology: 1, museum (indoor): 1, alabaster color: 1, a sculpture of a man: 1, building: 1, holding: 1, front: 1, wearing: 1, large: 1, posing: 1, white: 1, table: 1, suit: 1, cake: 1, board: 1, young: 1",
		"sculpture: 3, art: 3, statue: 2, man: 2, archaeology: 2, head: 2, figurine: 2, person: 2, ancient: 1, no person: 1, one: 1, people: 1, buddha: 1, religion: 1, carve: 1, pottery: 1, old: 1, spirituality: 1, antique: 1, traditional: 1, portrait: 1, clay: 1, museum: 1, brown wooden tiki mask decor: 1, woman head figurine: 1, forehead: 1, chin: 1, stone carving: 1, classical sculpture: 1, carving: 1, bronze: 1, human: 1, artifact: 1, socle: 1, support: 1, supporting structure: 1, alabaster color: 1, a close up of a person: 1, black: 1, looking: 1, brown: 1, cat: 1, standing: 1",
		"hair: 4, person: 4, portrait: 3, man: 3, beard: 3, sunglasses: 3, glasses: 3, eyewear: 2, face: 2, old: 2, photo: 2, people: 1, one: 1, adult: 1, eyeglasses: 1, facial hair: 1, mustache: 1, writer: 1, monochrome: 1, popularity: 1, look: 1, scientist: 1, mens black framed eyeglasses: 1, mens wearing black sunglasses illustration: 1, photograph: 1, hairstyle: 1, chin: 1, forehead: 1, self-portrait: 1, moustache: 1, human: 1, accessory: 1, accessories: 1, head: 1, photography: 1, drawing: 1, art: 1, art gallery: 1, indoors: 1, museum (indoor): 1, coonskin cap: 1, cap: 1, headdress: 1, ash grey color: 1, gray color: 1, a man wearing glasses posing for the camera: 1, wearing: 1, looking: 1, posing: 1, standing: 1, camera: 1, black: 1, white: 1, close: 1, young: 1, shirt: 1",
		"building: 5, temple: 3, architecture: 2, gold: 2, old: 2, spire: 2, bronze: 2, tower: 2, travel: 1, ancient: 1, culture: 1, religion: 1, art: 1, no person: 1, castle: 1, buddha: 1, sky: 1, traditional: 1, city: 1, sacred: 1, spirituality: 1, ornate: 1, monument: 1, brown and black leather tote bag: 1, two brown and white temple miniatures: 1, place of worship: 1, brass: 1, metal: 1, stupa: 1, mosque: 1, vehicle: 1, rocket: 1, transportation: 1, furniture: 1, shrine: 1, worship: 1, dome: 1, steeple: 1, repository (monument): 1, enclosure: 1, inkstand: 1, tray: 1, utensil: 1, mausoleum: 1, religious site: 1, religious building: 1, ultramarine color: 1, a statue of a person: 1, table: 1, sitting: 1, front: 1, large: 1, standing: 1, man: 1, boat: 1, water: 1, statue: 1, yellow: 1, white: 1, clock: 1, holding: 1, display: 1, tall: 1, people: 1, street: 1",
		"art: 3, painting: 3, person: 3, woman: 2, portrait: 2, statue: 2, religion: 1, sculpture: 1, people: 1, adult: 1, one: 1, renaissance: 1, veil: 1, saint: 1, god: 1, temple: 1, cave: 1, nude: 1, church: 1, gold: 1, wear: 1, offensive: 1, woman in white and yellow dress painting: 1, lady: 1, visual arts: 1, stock photography: 1, self-portrait: 1, human: 1, oil paint: 1, paint: 1, burial chamber: 1, enclosure: 1, masterpiece: 1, museum (indoor): 1, clothing: 1, alabaster color: 1, a statue of a person: 1, standing: 1, man: 1, photo: 1, holding: 1, looking: 1, old: 1, posing: 1, front: 1, wearing: 1, sitting: 1, white: 1, dress: 1, large: 1, room: 1, umbrella: 1",
		"food: 4, sculpture: 3, art: 2, statue: 2, cream: 2, dessert: 2, cake: 2, no person: 1, desktop: 1, sweet: 1, isolate: 1, nature: 1, icee: 1, delicious: 1, ball: 1, old: 1, health: 1, cold: 1, beautiful: 1, closeup: 1, chilled: 1, head: 1, white and brown floral textile: 1, white carved mountain: 1, stone carving: 1, classical sculpture: 1, carving: 1, rock: 1, figurine: 1, monument: 1, marble: 1, wedding cake: 1, creme: 1, crystal: 1, confectionery: 1, sweets: 1, dish: 1, meal: 1, icing: 1, mineral: 1, glyptic art: 1, figure: 1, vanilla ice cream: 1, ice cream: 1, nutrition: 1, food product: 1, alabaster color: 1, a stuffed animal on display: 1, sitting: 1, white: 1, table: 1, large: 1, standing: 1, holding: 1, display: 1, bear: 1, stuffed: 1, plate: 1, man: 1",
		"painting: 3, woman: 3, art: 3, person: 3, people: 2, man: 2, portrait: 2, sitting: 2, adult: 1, elderly: 1, two: 1, war: 1, one: 1, religion: 1, wear: 1, military: 1, lid: 1, battle: 1, veil: 1, soldier: 1, sit: 1, family: 1, offensive: 1, man and woman painting: 1, photography: 1, gentleman: 1, human: 1, catacomb: 1, grandson: 1, female: 1, grandmother: 1, grandfather: 1, senior citizen: 1, cadaver: 1, reddish brown color: 1, dark red color: 1, a man and a woman sitting on a couch: 1, holding: 1, old: 1, older: 1, table: 1, young: 1, white: 1, group: 1",
		"painting: 3, art: 3, illustration: 2, modern art: 2, tapestry: 2, wall: 1, desktop: 1, abstract: 1, texture: 1, pattern: 1, color: 1, design: 1, old: 1, vintage: 1, paper: 1, rock: 1, canvas: 1, image: 1, wallpaper: 1, gold: 1, retro: 1, background: 1, brown and green abstract painting: 1, trees under sun painting: 1, visual arts: 1, organism: 1, textile: 1, mythology: 1, history: 1, tile: 1, mosaic: 1, mural: 1, fabric: 1, artwork: 1, map: 1, multi panel pictures/art: 1, game equipment: 1, indoors: 1, paint: 1, olive green color: 1, a close up of some leaves: 1",
		"statue: 4, sculpture: 3, art: 3, bronze: 3, museum: 2, wood: 2, no person: 1, metalwork: 1, religion: 1, visual arts sculpture: 1, exhibition: 1, people: 1, ancient: 1, marble: 1, stone: 1, architecture: 1, artistic: 1, travel: 1, one: 1, nude: 1, brown wooden elephant table decor: 1, brown stone miniature: 1, classical sculpture: 1, bronze sculpture: 1, nonbuilding structure: 1, sculptor: 1, visual arts: 1, flooring: 1, floor: 1, torso: 1, figurine: 1, kneeling: 1, toy: 1, socle: 1, support: 1, supporting structure: 1, art gallery: 1, indoors: 1, museum (indoor): 1, bookend: 1, alabaster color: 1, a statue of a bear sitting on top of a wooden table: 1, indoor: 1, table: 1, sitting: 1, bear: 1, chair: 1, wooden: 1, box: 1, vase: 1, brown: 1, teddy: 1, display: 1, black: 1, large: 1, giant: 1, stuffed: 1, desk: 1, room: 1, living: 1, perched: 1",
		"art: 3, painting: 3, people: 2, illustration: 2, man: 2, book: 2, group: 2, mural: 2, religion: 1, god: 1, saint: 1, sword: 1, aura: 1, adult: 1, culture: 1, church: 1, woman: 1, cross: 1, print: 1, gothic: 1, holy: 1, marvel comics the amazing spider-man comic book: 1, human themed paintings: 1, modern art: 1, visual arts: 1, person: 1, human: 1, leisure activities: 1, skin: 1, comics: 1, multi panel pictures/art: 1, bottle green color: 1, maroon color: 1, a group of people posing for a photo: 1, photo: 1, posing: 1, covered: 1, various: 1, many: 1, different: 1, bunch: 1, colorful: 1, young: 1, large: 1, painted: 1, air: 1, night: 1",
		"people: 3, art: 3, painting: 3, group: 2, woman: 2, man: 2, person: 2, religion: 1, wear: 1, adult: 1, son: 1, gown (clothing): 1, baby: 1, monk: 1, illustration: 1, child: 1, god: 1, saint: 1, monastery: 1, renaissance: 1, prayer: 1, offensive: 1, group of soldier painting: 1, visual arts: 1, temple: 1, mythology: 1, human: 1, creche: 1, dance: 1, altarpiece: 1, screen: 1, indoors: 1, sport: 1, indian red color: 1, ultramarine color: 1, a group of people in a room: 1, standing: 1, cow: 1, night: 1, skiing: 1, holding: 1, room: 1, snow: 1, playing: 1, white: 1",
		"sculpture: 4, statue: 3, art: 3, bird: 3, marble: 2, figurine: 2, no person: 1, nude: 1, woman: 1, ancient: 1, classic: 1, travel: 1, two: 1, sit: 1, religion: 1, renaissance: 1, one: 1, cupid: 1, museum: 1, figure: 1, people: 1, white ceramic elephant figurine with box: 1, white ceramic bird figurine: 1, stone carving: 1, classical sculpture: 1, carving: 1, sculptor: 1, monument: 1, animal: 1, food: 1, cake: 1, dessert: 1, wedding cake: 1, nature: 1, snowman: 1, winter: 1, snow: 1, outdoors: 1, ivory: 1, alabaster color: 1, socle: 1, support: 1, supporting structure: 1, a bird sitting on a white background: 1, sitting: 1, white: 1, standing: 1, black: 1, front: 1, table: 1, parrot: 1, wedding: 1",
		"horse: 4, art: 3, sculpture: 3, figurine: 3, mammal: 2, animal: 2, statue: 2, bronze: 2, man: 2, green: 2, cavalry: 1, illustration: 1, no person: 1, one: 1, equestrian: 1, figure: 1, two: 1, seated: 1, show: 1, retro: 1, artistic: 1, green and black ceramic figurine: 1, green horse figurine: 1, animal figure: 1, metal: 1, bronze sculpture: 1, toy: 1, pottery: 1, porcelain: 1, human: 1, person: 1, cockhorse (toy horse): 1, verdigris (green coating): 1, coating: 1, reptile: 1, greenish blue color: 1, jade green color: 1, a person riding a horse: 1, building: 1, water: 1, walking: 1, standing: 1, riding: 1, black: 1, field: 1, large: 1, white: 1, holding: 1, hill: 1, snow: 1",
		"art: 3, painting: 3, building: 3, people: 2, group: 2, many: 2, man: 2, woman: 2, mural: 2, person: 2, screen: 2, display: 2, religion: 1, adult: 1, saint: 1, renaissance: 1, travel: 1, church: 1, child: 1, cavalry: 1, mary: 1, sword: 1, pain: 1, baroque: 1, kneeling: 1, offensive: 1, painting close-up photography: 1, mythology: 1, visual arts: 1, middle ages: 1, conquistador: 1, pilgrims: 1, history: 1, stock photography: 1, human: 1, apparel: 1, clothing: 1, sari: 1, silk: 1, crypt: 1, architecture: 1, sculpture: 1, lcd screen: 1, monitor: 1, electronics: 1, loggia (roofed arcade of building): 1, painting of people: 1, meal: 1, nutrition: 1, food: 1, altarpiece: 1, indoors: 1, pieta (statue): 1, indian red color: 1, alabaster color: 1, a group of stuffed animals sitting on top of a building: 1, window: 1, sitting: 1, stuffed: 1, table: 1, large: 1, bunch: 1, bench: 1, room: 1, standing: 1, wooden: 1, bear: 1, street: 1, city: 1, riding: 1",
		"person: 3, portrait: 2, man: 2, art: 2, painting: 2, black: 2, people: 1, one: 1, adult: 1, illustration: 1, street: 1, urban: 1, vintage: 1, face: 1, smoke: 1, wear: 1, retro: 1, dark: 1, sit: 1, print: 1, music: 1, man in black suit jacket photo: 1, blue: 1, and yellow abstract painting: 1, self-portrait: 1, visual arts: 1, human: 1, blackboard: 1, goalpost: 1, support: 1, penalty box: 1, bench: 1, seat: 1, furniture: 1, sport: 1, black color: 1, coal black color: 1, yellow: 1, photo: 1, sitting: 1, wearing: 1, sign: 1, holding: 1, standing: 1, table: 1, horse: 1, phone: 1, riding: 1",
		"sculpture: 3, art: 3, statue: 3, person: 3, buddha: 2, old: 2, temple: 2, meditation: 2, man: 2, people: 2, figurine: 2, sitting: 2, artifact: 2, building: 2, ancient: 1, religion: 1, god: 1, traditional: 1, culture: 1, zen: 1, spirituality: 1, figure: 1, travel: 1, veil: 1, man in brown suit figurine: 1, hindu deity statue: 1, stone carving: 1, classical sculpture: 1, monument: 1, worship: 1, architecture: 1, human: 1, shrine: 1, pieta (statue): 1, cadaver: 1, mycenaen artifacts (greek): 1, museum (indoor): 1, toby jug: 1, drinking vessel: 1, alabaster color: 1, a statue of a man: 1, holding: 1, standing: 1, table: 1, phone: 1, wearing: 1, large: 1, yellow: 1, cake: 1, street: 1, zebra: 1",
		"sculpture: 4, statue: 4, art: 3, monument: 3, figurine: 3, bronze: 2, man: 2, standing: 2, ancient: 1, no person: 1, nude: 1, metalwork: 1, travel: 1, religion: 1, museum: 1, figure: 1, renaissance: 1, god: 1, old: 1, artistic: 1, architecture: 1, man in black suit figurine: 1, man riding elephant statuette: 1, classical sculpture: 1, stone carving: 1, carving: 1, visual arts: 1, toy: 1, archaeology: 1, museum (indoor): 1, indoors: 1, alabaster color: 1, a statue of a person: 1, indoor: 1, building: 1, sitting: 1, chain: 1, table: 1, metal: 1, wooden: 1, elephant: 1, large: 1, water: 1, holding: 1, display: 1, room: 1",
		"sculpture: 3, art: 3, statue: 3, stone: 2, archaeology: 2, buddha: 2, face: 2, artifact: 2, ancient: 1, religion: 1, culture: 1, grave: 1, god: 1, old: 1, monument: 1, symbol: 1, temple: 1, figure: 1, religious belief: 1, carve: 1, spirituality: 1, pair of gray suede slip on shoes: 1, gray concrete buddhai statue: 1, stone carving: 1, classical sculpture: 1, carving: 1, head: 1, relief: 1, ancient history: 1, figurine: 1, person: 1, human: 1, photo: 1, photography: 1, painting: 1, portrait: 1, worship: 1, stele (stone slab with markings): 1, alabaster color: 1, a stone statue of a man: 1, building: 1, man: 1, sitting: 1, feet: 1, bear: 1, holding: 1, large: 1, standing: 1, bird: 1, white: 1, stuffed: 1, laying: 1",
		"sculpture: 2, bronze: 2, statue: 2, pedestal: 2, gold: 2, fountain: 2, glass: 2, building: 2, art: 1, ancient: 1, no person: 1, antique: 1, old: 1, marble: 1, classic: 1, architecture: 1, ornate: 1, chess: 1, glass items: 1, luxury: 1, artistic: 1, traditional: 1, design: 1, silver and clear glass candle holder: 1, grey statue: 1, trophy: 1, still life photography: 1, water feature: 1, metal: 1, silver: 1, goblet: 1, symbol: 1, cross: 1, tabletop: 1, furniture: 1, crystal: 1, socle: 1, support: 1, supporting structure: 1, censer container: 1, holding device: 1, alabaster color: 1, sitting: 1, standing: 1, clock: 1, dark: 1, vase: 1, front: 1, black: 1, middle: 1, tall: 1, holding: 1, lamp: 1, table: 1, light: 1, large: 1, tower: 1, white: 1, man: 1, cup: 1, display: 1, street: 1, room: 1",
		"furniture: 4, wood: 3, table: 3, antique: 2, old: 2, cupboard: 2, sideboard: 2, no person: 1, carpentry: 1, art: 1, design: 1, retro: 1, architecture: 1, classic: 1, interior design: 1, ornate: 1, seat: 1, leather: 1, style: 1, sculpture: 1, empty: 1, carve: 1, ancient: 1, brown wooden cabinet with drawer: 1, brown wooden cabinet: 1, carving: 1, chair: 1, wood stain: 1, hardwood: 1, closet: 1, cabinet: 1, mailbox: 1, letterbox: 1, marquetry (veneers): 1, coffer (chest): 1, box: 1, reddish brown color: 1, a wooden clock with furniture: 1, wooden: 1, indoor: 1, clock: 1, sitting: 1, small: 1, room: 1, brown: 1, bed: 1, large: 1, statue: 1, desk: 1, standing: 1, cat: 1",
		"furniture: 5, table: 4, antique: 2, indoors: 2, gold: 2, luxury: 1, baroque: 1, no person: 1, art: 1, classic: 1, ornate: 1, museum: 1, bronze: 1, elegant: 1, victorian: 1, painting: 1, retro: 1, ancient: 1, interior design: 1, vintage: 1, old: 1, brown wooden frame wall decor: 1, gold side table: 1, sofa tables: 1, napoleon iii style: 1, end table: 1, brass: 1, metal: 1, sideboard: 1, tabletop: 1, dining table: 1, desk: 1, console table: 1, pier table: 1, light brown color: 1, beige color: 1, a gold clock sitting on top of a wooden table: 1, indoor: 1, sitting: 1, hanging: 1, wooden: 1, room: 1, bed: 1, clock: 1, water: 1, standing: 1, laying: 1, white: 1",
		"sculpture: 4, art: 3, bronze: 3, statue: 2, figurine: 2, old: 2, figure: 2, person: 2, ancient: 1, nude: 1, travel: 1, god: 1, no person: 1, religion: 1, decoration: 1, museum: 1, goddess: 1, carve: 1, antique: 1, gold: 1, metalwork: 1, brown wooden horse figurine screenshot: 1, brown deity statuette: 1, stone carving: 1, classical sculpture: 1, monument: 1, carving: 1, metal: 1, mythology: 1, wood: 1, building: 1, architecture: 1, temple: 1, worship: 1, symbol: 1, cross: 1, shrine: 1, hardwood: 1, human: 1, flooring: 1, buddha: 1, urban: 1, metropolis: 1, city: 1, town: 1, archaeology: 1, artifact: 1, woodcarving: 1, reliquary container: 1, kachina dolls: 1, censer container: 1, alabaster color: 1, sitting: 1, table: 1, standing: 1, wooden: 1, different: 1, display: 1, group: 1, laying: 1, cat: 1, clock: 1, room: 1",
		"furniture: 3, table: 3, sculpture: 2, wood: 2, art: 2, stool: 2, carpentry: 1, leather: 1, no person: 1, steel: 1, iron: 1, museum: 1, retro: 1, design: 1, people: 1, vintage: 1, old: 1, fashion: 1, ancient: 1, exert: 1, decoration: 1, chrome: 1, gray and black leather handbag: 1, gray robe decor: 1, bar stool: 1, metal: 1, silver: 1, sink faucet: 1, bronze: 1, pedestal table: 1, candlestick: 1, holder: 1, propeller: 1, mechanical device: 1, seat: 1, ax handle: 1, ax: 1, cutlery: 1, tool: 1, footwear: 1, headdress: 1, ash grey color: 1, indoor: 1, sitting: 1, gray: 1, elephant: 1, grey: 1, chair: 1, desk: 1, wooden: 1, mouse: 1, computer: 1, cat: 1, brown: 1, made: 1, keyboard: 1, large: 1, apple: 1, room: 1, standing: 1, white: 1",
		"woman: 2, samurai: 2, sculpture: 1, art: 1, traditional: 1, veil: 1, travel: 1, temple: 1, religion: 1, ancient: 1, people: 1, statue: 1, wear: 1, no person: 1, culture: 1, buddha: 1, tribal: 1, adult: 1, figure: 1, god: 1, spirituality: 1, brown and black ceramic figurine: 1, multicolored samurai armor: 1, armour: 1, armor: 1, person: 1, human: 1, robot: 1, kachina: 1, mechanism: 1, ultramarine color: 1, indian red color: 1, a close up of a toy: 1, toy: 1, doll: 1, table: 1, sitting: 1, cellphone: 1, phone: 1, wearing: 1, yellow: 1, hat: 1, holding: 1, display: 1, covered: 1, white: 1, gold: 1, man: 1, standing: 1, stacked: 1, bed: 1",
		"painting: 5, graffiti: 3, art: 3, illustration: 2, mural: 2, man: 2, modern art: 2, person: 2, wall: 1, artistic: 1, vandalism: 1, caricature: 1, people: 1, visuals: 1, color: 1, woman: 1, hip: 1, culture: 1, street: 1, adult: 1, religion: 1, spray: 1, brown and blue wooden painting: 1, three women painting: 1, visual arts: 1, acrylic paint: 1, watercolor paint: 1, artwork: 1, human: 1, animal: 1, bird: 1, fauve painting: 1, oil paint: 1, paint: 1, tapestry: 1, fabric: 1, indoors: 1, brick red color: 1, indian red color: 1, a painting of a book: 1, text: 1, book: 1, photo: 1, grass: 1, table: 1, painted: 1, elephant: 1, holding: 1, old: 1, birthday: 1, water: 1, board: 1, horse: 1, sign: 1, standing: 1, riding: 1",
		"sleeve: 4, clothing: 3, dress: 2, blouse: 2, fashion: 1, woman: 1, wear: 1, cotton: 1, model: 1, shopping: 1, design: 1, girl: 1, elegant: 1, isolated: 1, no person: 1, color: 1, art: 1, classic: 1, isolate: 1, textile: 1, style: 1, people: 1, womens white and pink floral shorts: 1, mens brown thobe: 1, outerwear: 1, beige: 1, robe: 1, pattern: 1, jacket: 1, lace: 1, embroidery: 1, apparel: 1, long sleeve: 1, human: 1, person: 1, fabric: 1, beige color: 1, a person in a white shirt: 1, indoor: 1, shirt: 1, wearing: 1, white: 1, head: 1, man: 1, holding: 1, standing: 1, room: 1, night: 1",
	]

	var art_raw_cats = [
		"sculpture:Clarifai, statue:Clarifai, art:Clarifai, nude:Clarifai, marble:Clarifai, man:Clarifai, figure:Clarifai, ancient:Clarifai, monument:Clarifai, museum:Clarifai, people:Clarifai, carve:Clarifai, no person:Clarifai, architecture:Clarifai, renaissance:Clarifai, old:Clarifai, anatomy:Clarifai, stone:Clarifai, artistic:Clarifai, classic:Clarifai, man and woman ceramic figurine:CloudSight, nude man statue:CloudSight Hybrid, sculpture:Google Vision, classical sculpture:Google Vision, statue:Google Vision, standing:Google Vision, art:Google Vision, figurine:Google Vision, male:Google Vision, muscle:Google Vision, human body:Google Vision, chest:Google Vision, sculpture:Amazon Rekognition, art:Amazon Rekognition, statue:Amazon Rekognition, figurine:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, archaeology:Amazon Rekognition, person:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, sculpture:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a sculpture of a man:Microsoft Computer Vision, building:Microsoft Computer Vision, sculpture:Microsoft Computer Vision, person:Microsoft Computer Vision, man:Microsoft Computer Vision, standing:Microsoft Computer Vision, holding:Microsoft Computer Vision, front:Microsoft Computer Vision, wearing:Microsoft Computer Vision, large:Microsoft Computer Vision, posing:Microsoft Computer Vision, white:Microsoft Computer Vision, table:Microsoft Computer Vision, suit:Microsoft Computer Vision, stone:Microsoft Computer Vision, cake:Microsoft Computer Vision, old:Microsoft Computer Vision, board:Microsoft Computer Vision, young:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, ancient:Clarifai, statue:Clarifai, no person:Clarifai, one:Clarifai, people:Clarifai, buddha:Clarifai, man:Clarifai, religion:Clarifai, carve:Clarifai, pottery:Clarifai, old:Clarifai, spirituality:Clarifai, antique:Clarifai, archaeology:Clarifai, traditional:Clarifai, portrait:Clarifai, clay:Clarifai, museum:Clarifai, brown wooden tiki mask decor:CloudSight, woman head figurine:CloudSight Hybrid, sculpture:Google Vision, forehead:Google Vision, head:Google Vision, art:Google Vision, chin:Google Vision, figurine:Google Vision, stone carving:Google Vision, classical sculpture:Google Vision, statue:Google Vision, carving:Google Vision, head:Amazon Rekognition, bronze:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, sculpture:Amazon Rekognition, art:Amazon Rekognition, figurine:Amazon Rekognition, archaeology:Amazon Rekognition, person:IBM Visual Recognition, artifact:IBM Visual Recognition, socle:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a close up of a person:Microsoft Computer Vision, black:Microsoft Computer Vision, looking:Microsoft Computer Vision, brown:Microsoft Computer Vision, man:Microsoft Computer Vision, cat:Microsoft Computer Vision, standing:Microsoft Computer Vision",
		"portrait:Clarifai, people:Clarifai, man:Clarifai, one:Clarifai, adult:Clarifai, eyeglasses:Clarifai, facial hair:Clarifai, eyewear:Clarifai, mustache:Clarifai, face:Clarifai, writer:Clarifai, hair:Clarifai, monochrome:Clarifai, beard:Clarifai, popularity:Clarifai, person:Clarifai, old:Clarifai, sunglasses:Clarifai, look:Clarifai, scientist:Clarifai, mens black framed eyeglasses:CloudSight, mens wearing black sunglasses illustration:CloudSight Hybrid, hair:Google Vision, photograph:Google Vision, portrait:Google Vision, hairstyle:Google Vision, chin:Google Vision, forehead:Google Vision, eyewear:Google Vision, self-portrait:Google Vision, moustache:Google Vision, glasses:Google Vision, face:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, accessory:Amazon Rekognition, sunglasses:Amazon Rekognition, accessories:Amazon Rekognition, beard:Amazon Rekognition, head:Amazon Rekognition, portrait:Amazon Rekognition, photo:Amazon Rekognition, photography:Amazon Rekognition, glasses:Amazon Rekognition, hair:Amazon Rekognition, man:Amazon Rekognition, drawing:Amazon Rekognition, art:Amazon Rekognition, art gallery:IBM Visual Recognition, indoors:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, person:IBM Visual Recognition, beard:IBM Visual Recognition, coonskin cap:IBM Visual Recognition, cap:IBM Visual Recognition, headdress:IBM Visual Recognition, ash grey color:IBM Visual Recognition, gray color:IBM Visual Recognition, a man wearing glasses posing for the camera:Microsoft Computer Vision, man:Microsoft Computer Vision, person:Microsoft Computer Vision, glasses:Microsoft Computer Vision, wearing:Microsoft Computer Vision, looking:Microsoft Computer Vision, posing:Microsoft Computer Vision, photo:Microsoft Computer Vision, standing:Microsoft Computer Vision, camera:Microsoft Computer Vision, sunglasses:Microsoft Computer Vision, black:Microsoft Computer Vision, hair:Microsoft Computer Vision, white:Microsoft Computer Vision, close:Microsoft Computer Vision, young:Microsoft Computer Vision, old:Microsoft Computer Vision, shirt:Microsoft Computer Vision",
		"travel:Clarifai, architecture:Clarifai, gold:Clarifai, ancient:Clarifai, temple:Clarifai, old:Clarifai, culture:Clarifai, religion:Clarifai, art:Clarifai, no person:Clarifai, castle:Clarifai, buddha:Clarifai, sky:Clarifai, traditional:Clarifai, city:Clarifai, building:Clarifai, sacred:Clarifai, spirituality:Clarifai, ornate:Clarifai, monument:Clarifai, brown and black leather tote bag:CloudSight, two brown and white temple miniatures:CloudSight Hybrid, place of worship:Google Vision, brass:Google Vision, metal:Google Vision, stupa:Google Vision, mosque:Google Vision, building:Google Vision, spire:Google Vision, bronze:Google Vision, architecture:Amazon Rekognition, building:Amazon Rekognition, gold:Amazon Rekognition, vehicle:Amazon Rekognition, rocket:Amazon Rekognition, transportation:Amazon Rekognition, temple:Amazon Rekognition, bronze:Amazon Rekognition, furniture:Amazon Rekognition, shrine:Amazon Rekognition, worship:Amazon Rekognition, dome:Amazon Rekognition, tower:Amazon Rekognition, spire:Amazon Rekognition, steeple:Amazon Rekognition, repository (monument):IBM Visual Recognition, enclosure:IBM Visual Recognition, inkstand:IBM Visual Recognition, tray:IBM Visual Recognition, utensil:IBM Visual Recognition, mausoleum:IBM Visual Recognition, religious site:IBM Visual Recognition, building:IBM Visual Recognition, religious building:IBM Visual Recognition, temple:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, a statue of a person:Microsoft Computer Vision, table:Microsoft Computer Vision, building:Microsoft Computer Vision, sitting:Microsoft Computer Vision, front:Microsoft Computer Vision, large:Microsoft Computer Vision, standing:Microsoft Computer Vision, man:Microsoft Computer Vision, boat:Microsoft Computer Vision, old:Microsoft Computer Vision, water:Microsoft Computer Vision, statue:Microsoft Computer Vision, yellow:Microsoft Computer Vision, white:Microsoft Computer Vision, clock:Microsoft Computer Vision, holding:Microsoft Computer Vision, display:Microsoft Computer Vision, tall:Microsoft Computer Vision, people:Microsoft Computer Vision, tower:Microsoft Computer Vision, street:Microsoft Computer Vision",
		"art:Clarifai, painting:Clarifai, woman:Clarifai, religion:Clarifai, sculpture:Clarifai, people:Clarifai, portrait:Clarifai, adult:Clarifai, one:Clarifai, renaissance:Clarifai, statue:Clarifai, veil:Clarifai, saint:Clarifai, god:Clarifai, temple:Clarifai, cave:Clarifai, nude:Clarifai, church:Clarifai, gold:Clarifai, wear:Clarifai, offensive:CloudSight, woman in white and yellow dress painting:CloudSight Hybrid, painting:Google Vision, lady:Google Vision, portrait:Google Vision, art:Google Vision, visual arts:Google Vision, stock photography:Google Vision, self-portrait:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, person:IBM Visual Recognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, burial chamber:IBM Visual Recognition, enclosure:IBM Visual Recognition, masterpiece:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, clothing:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a statue of a person:Microsoft Computer Vision, person:Microsoft Computer Vision, standing:Microsoft Computer Vision, man:Microsoft Computer Vision, photo:Microsoft Computer Vision, holding:Microsoft Computer Vision, looking:Microsoft Computer Vision, woman:Microsoft Computer Vision, old:Microsoft Computer Vision, posing:Microsoft Computer Vision, front:Microsoft Computer Vision, wearing:Microsoft Computer Vision, sitting:Microsoft Computer Vision, white:Microsoft Computer Vision, statue:Microsoft Computer Vision, dress:Microsoft Computer Vision, large:Microsoft Computer Vision, room:Microsoft Computer Vision, umbrella:Microsoft Computer Vision",
		"sculpture:Clarifai, no person:Clarifai, desktop:Clarifai, food:Clarifai, sweet:Clarifai, isolate:Clarifai, nature:Clarifai, art:Clarifai, icee:Clarifai, delicious:Clarifai, ball:Clarifai, old:Clarifai, health:Clarifai, statue:Clarifai, cream:Clarifai, cold:Clarifai, beautiful:Clarifai, closeup:Clarifai, chilled:Clarifai, head:Clarifai, white and brown floral textile:CloudSight, white carved mountain:CloudSight Hybrid, stone carving:Google Vision, sculpture:Google Vision, statue:Google Vision, classical sculpture:Google Vision, carving:Google Vision, rock:Google Vision, figurine:Google Vision, art:Google Vision, monument:Google Vision, marble:Google Vision, food:Amazon Rekognition, dessert:Amazon Rekognition, cake:Amazon Rekognition, wedding cake:Amazon Rekognition, creme:Amazon Rekognition, cream:Amazon Rekognition, crystal:Amazon Rekognition, confectionery:Amazon Rekognition, sweets:Amazon Rekognition, dish:Amazon Rekognition, meal:Amazon Rekognition, icing:Amazon Rekognition, mineral:Amazon Rekognition, glyptic art:IBM Visual Recognition, sculpture:IBM Visual Recognition, figure:IBM Visual Recognition, vanilla ice cream:IBM Visual Recognition, ice cream:IBM Visual Recognition, dessert:IBM Visual Recognition, nutrition:IBM Visual Recognition, food:IBM Visual Recognition, food product:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a stuffed animal on display:Microsoft Computer Vision, sitting:Microsoft Computer Vision, white:Microsoft Computer Vision, cake:Microsoft Computer Vision, table:Microsoft Computer Vision, food:Microsoft Computer Vision, large:Microsoft Computer Vision, standing:Microsoft Computer Vision, holding:Microsoft Computer Vision, display:Microsoft Computer Vision, bear:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, plate:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"people:Clarifai, adult:Clarifai, man:Clarifai, elderly:Clarifai, portrait:Clarifai, painting:Clarifai, woman:Clarifai, two:Clarifai, art:Clarifai, war:Clarifai, one:Clarifai, religion:Clarifai, wear:Clarifai, military:Clarifai, lid:Clarifai, battle:Clarifai, veil:Clarifai, soldier:Clarifai, sit:Clarifai, family:Clarifai, offensive:CloudSight, man and woman painting:CloudSight Hybrid, painting:Google Vision, portrait:Google Vision, art:Google Vision, photography:Google Vision, gentleman:Google Vision, sitting:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, catacomb:IBM Visual Recognition, grandson:IBM Visual Recognition, person:IBM Visual Recognition, woman:IBM Visual Recognition, female:IBM Visual Recognition, grandmother:IBM Visual Recognition, grandfather:IBM Visual Recognition, senior citizen:IBM Visual Recognition, cadaver:IBM Visual Recognition, reddish brown color:IBM Visual Recognition, dark red color:IBM Visual Recognition, a man and a woman sitting on a couch:Microsoft Computer Vision, person:Microsoft Computer Vision, sitting:Microsoft Computer Vision, man:Microsoft Computer Vision, holding:Microsoft Computer Vision, woman:Microsoft Computer Vision, old:Microsoft Computer Vision, older:Microsoft Computer Vision, people:Microsoft Computer Vision, table:Microsoft Computer Vision, young:Microsoft Computer Vision, white:Microsoft Computer Vision, group:Microsoft Computer Vision",
		"painting:Clarifai, wall:Clarifai, art:Clarifai, desktop:Clarifai, abstract:Clarifai, texture:Clarifai, pattern:Clarifai, color:Clarifai, design:Clarifai, old:Clarifai, vintage:Clarifai, paper:Clarifai, rock:Clarifai, canvas:Clarifai, image:Clarifai, illustration:Clarifai, wallpaper:Clarifai, gold:Clarifai, retro:Clarifai, background:Clarifai, brown and green abstract painting:CloudSight, trees under sun painting:CloudSight Hybrid, painting:Google Vision, art:Google Vision, modern art:Google Vision, tapestry:Google Vision, visual arts:Google Vision, organism:Google Vision, textile:Google Vision, mythology:Google Vision, illustration:Google Vision, history:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, tile:Amazon Rekognition, mosaic:Amazon Rekognition, mural:Amazon Rekognition, modern art:Amazon Rekognition, tapestry:IBM Visual Recognition, fabric:IBM Visual Recognition, artwork:IBM Visual Recognition, map:IBM Visual Recognition, multi panel pictures/art:IBM Visual Recognition, game equipment:IBM Visual Recognition, indoors:IBM Visual Recognition, paint:IBM Visual Recognition, olive green color:IBM Visual Recognition, a close up of some leaves:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, statue:Clarifai, museum:Clarifai, no person:Clarifai, metalwork:Clarifai, religion:Clarifai, visual arts sculpture:Clarifai, bronze:Clarifai, exhibition:Clarifai, people:Clarifai, ancient:Clarifai, marble:Clarifai, stone:Clarifai, architecture:Clarifai, artistic:Clarifai, travel:Clarifai, one:Clarifai, nude:Clarifai, wood:Clarifai, brown wooden elephant table decor:CloudSight, brown stone miniature:CloudSight Hybrid, sculpture:Google Vision, art:Google Vision, statue:Google Vision, museum:Google Vision, classical sculpture:Google Vision, bronze sculpture:Google Vision, bronze:Google Vision, nonbuilding structure:Google Vision, sculptor:Google Vision, visual arts:Google Vision, art:Amazon Rekognition, sculpture:Amazon Rekognition, statue:Amazon Rekognition, flooring:Amazon Rekognition, floor:Amazon Rekognition, wood:Amazon Rekognition, torso:Amazon Rekognition, figurine:Amazon Rekognition, bronze:Amazon Rekognition, kneeling:Amazon Rekognition, toy:Amazon Rekognition, socle:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, art gallery:IBM Visual Recognition, indoors:IBM Visual Recognition, museum (indoor):IBM Visual Recognition, bookend:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a statue of a bear sitting on top of a wooden table:Microsoft Computer Vision, indoor:Microsoft Computer Vision, statue:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, bear:Microsoft Computer Vision, chair:Microsoft Computer Vision, wooden:Microsoft Computer Vision, box:Microsoft Computer Vision, vase:Microsoft Computer Vision, brown:Microsoft Computer Vision, teddy:Microsoft Computer Vision, display:Microsoft Computer Vision, black:Microsoft Computer Vision, large:Microsoft Computer Vision, giant:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, desk:Microsoft Computer Vision, room:Microsoft Computer Vision, living:Microsoft Computer Vision, perched:Microsoft Computer Vision",
		"art:Clarifai, religion:Clarifai, people:Clarifai, painting:Clarifai, illustration:Clarifai, god:Clarifai, saint:Clarifai, man:Clarifai, sword:Clarifai, aura:Clarifai, adult:Clarifai, book:Clarifai, culture:Clarifai, group:Clarifai, church:Clarifai, woman:Clarifai, cross:Clarifai, print:Clarifai, gothic:Clarifai, holy:Clarifai, marvel comics the amazing spider-man comic book:CloudSight, human themed paintings:CloudSight Hybrid, art:Google Vision, modern art:Google Vision, painting:Google Vision, visual arts:Google Vision, mural:Google Vision, illustration:Google Vision, person:Amazon Rekognition, human:Amazon Rekognition, art:Amazon Rekognition, painting:Amazon Rekognition, leisure activities:Amazon Rekognition, skin:Amazon Rekognition, mural:Amazon Rekognition, comics:Amazon Rekognition, book:Amazon Rekognition, multi panel pictures/art:IBM Visual Recognition, bottle green color:IBM Visual Recognition, maroon color:IBM Visual Recognition, a group of people posing for a photo:Microsoft Computer Vision, photo:Microsoft Computer Vision, posing:Microsoft Computer Vision, covered:Microsoft Computer Vision, various:Microsoft Computer Vision, many:Microsoft Computer Vision, different:Microsoft Computer Vision, bunch:Microsoft Computer Vision, group:Microsoft Computer Vision, colorful:Microsoft Computer Vision, young:Microsoft Computer Vision, large:Microsoft Computer Vision, man:Microsoft Computer Vision, painted:Microsoft Computer Vision, people:Microsoft Computer Vision, air:Microsoft Computer Vision, night:Microsoft Computer Vision",
		"religion:Clarifai, people:Clarifai, art:Clarifai, wear:Clarifai, painting:Clarifai, adult:Clarifai, group:Clarifai, woman:Clarifai, man:Clarifai, son:Clarifai, gown (clothing):Clarifai, baby:Clarifai, monk:Clarifai, illustration:Clarifai, child:Clarifai, god:Clarifai, saint:Clarifai, monastery:Clarifai, renaissance:Clarifai, prayer:Clarifai, offensive:CloudSight, group of soldier painting:CloudSight Hybrid, visual arts:Google Vision, painting:Google Vision, art:Google Vision, temple:Google Vision, mythology:Google Vision, painting:Amazon Rekognition, art:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, creche:IBM Visual Recognition, dance:IBM Visual Recognition, person:IBM Visual Recognition, people:IBM Visual Recognition, altarpiece:IBM Visual Recognition, screen:IBM Visual Recognition, indoors:IBM Visual Recognition, sport:IBM Visual Recognition, indian red color:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, a group of people in a room:Microsoft Computer Vision, group:Microsoft Computer Vision, people:Microsoft Computer Vision, standing:Microsoft Computer Vision, cow:Microsoft Computer Vision, man:Microsoft Computer Vision, night:Microsoft Computer Vision, woman:Microsoft Computer Vision, skiing:Microsoft Computer Vision, holding:Microsoft Computer Vision, room:Microsoft Computer Vision, snow:Microsoft Computer Vision, playing:Microsoft Computer Vision, white:Microsoft Computer Vision",
		"sculpture:Clarifai, statue:Clarifai, art:Clarifai, marble:Clarifai, no person:Clarifai, nude:Clarifai, woman:Clarifai, ancient:Clarifai, classic:Clarifai, travel:Clarifai, two:Clarifai, sit:Clarifai, religion:Clarifai, renaissance:Clarifai, one:Clarifai, cupid:Clarifai, museum:Clarifai, figure:Clarifai, bird:Clarifai, people:Clarifai, white ceramic elephant figurine with box:CloudSight, white ceramic bird figurine:CloudSight Hybrid, sculpture:Google Vision, statue:Google Vision, stone carving:Google Vision, classical sculpture:Google Vision, figurine:Google Vision, art:Google Vision, carving:Google Vision, marble:Google Vision, sculptor:Google Vision, monument:Google Vision, art:Amazon Rekognition, sculpture:Amazon Rekognition, statue:Amazon Rekognition, figurine:Amazon Rekognition, animal:Amazon Rekognition, bird:Amazon Rekognition, food:Amazon Rekognition, cake:Amazon Rekognition, dessert:Amazon Rekognition, wedding cake:Amazon Rekognition, nature:Amazon Rekognition, snowman:Amazon Rekognition, winter:Amazon Rekognition, snow:Amazon Rekognition, outdoors:Amazon Rekognition, ivory:Amazon Rekognition, alabaster color:IBM Visual Recognition, socle:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, sculpture:IBM Visual Recognition, a bird sitting on a white background:Microsoft Computer Vision, sitting:Microsoft Computer Vision, white:Microsoft Computer Vision, bird:Microsoft Computer Vision, standing:Microsoft Computer Vision, black:Microsoft Computer Vision, front:Microsoft Computer Vision, table:Microsoft Computer Vision, parrot:Microsoft Computer Vision, wedding:Microsoft Computer Vision",
		"art:Clarifai, cavalry:Clarifai, illustration:Clarifai, sculpture:Clarifai, no person:Clarifai, mammal:Clarifai, animal:Clarifai, horse:Clarifai, one:Clarifai, equestrian:Clarifai, figure:Clarifai, two:Clarifai, statue:Clarifai, figurine:Clarifai, seated:Clarifai, bronze:Clarifai, show:Clarifai, retro:Clarifai, artistic:Clarifai, man:Clarifai, green and black ceramic figurine:CloudSight, green horse figurine:CloudSight Hybrid, sculpture:Google Vision, green:Google Vision, horse:Google Vision, statue:Google Vision, animal figure:Google Vision, figurine:Google Vision, art:Google Vision, metal:Google Vision, bronze sculpture:Google Vision, bronze:Google Vision, figurine:Amazon Rekognition, toy:Amazon Rekognition, pottery:Amazon Rekognition, art:Amazon Rekognition, porcelain:Amazon Rekognition, mammal:Amazon Rekognition, horse:Amazon Rekognition, animal:Amazon Rekognition, sculpture:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, cockhorse (toy horse):IBM Visual Recognition, verdigris (green coating):IBM Visual Recognition, coating:IBM Visual Recognition, reptile:IBM Visual Recognition, greenish blue color:IBM Visual Recognition, jade green color:IBM Visual Recognition, a person riding a horse:Microsoft Computer Vision, green:Microsoft Computer Vision, building:Microsoft Computer Vision, water:Microsoft Computer Vision, walking:Microsoft Computer Vision, standing:Microsoft Computer Vision, riding:Microsoft Computer Vision, horse:Microsoft Computer Vision, black:Microsoft Computer Vision, field:Microsoft Computer Vision, large:Microsoft Computer Vision, white:Microsoft Computer Vision, holding:Microsoft Computer Vision, hill:Microsoft Computer Vision, snow:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"people:Clarifai, art:Clarifai, group:Clarifai, many:Clarifai, religion:Clarifai, man:Clarifai, woman:Clarifai, painting:Clarifai, adult:Clarifai, saint:Clarifai, renaissance:Clarifai, travel:Clarifai, church:Clarifai, child:Clarifai, cavalry:Clarifai, mary:Clarifai, sword:Clarifai, pain:Clarifai, baroque:Clarifai, kneeling:Clarifai, offensive:CloudSight, painting close-up photography:CloudSight Hybrid, painting:Google Vision, art:Google Vision, mythology:Google Vision, visual arts:Google Vision, mural:Google Vision, middle ages:Google Vision, conquistador:Google Vision, pilgrims:Google Vision, history:Google Vision, stock photography:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, apparel:Amazon Rekognition, clothing:Amazon Rekognition, sari:Amazon Rekognition, silk:Amazon Rekognition, crypt:Amazon Rekognition, architecture:Amazon Rekognition, building:Amazon Rekognition, sculpture:Amazon Rekognition, mural:Amazon Rekognition, lcd screen:Amazon Rekognition, screen:Amazon Rekognition, monitor:Amazon Rekognition, electronics:Amazon Rekognition, display:Amazon Rekognition, person:IBM Visual Recognition, loggia (roofed arcade of building):IBM Visual Recognition, painting of people:IBM Visual Recognition, meal:IBM Visual Recognition, nutrition:IBM Visual Recognition, food:IBM Visual Recognition, altarpiece:IBM Visual Recognition, screen:IBM Visual Recognition, indoors:IBM Visual Recognition, pieta (statue):IBM Visual Recognition, building:IBM Visual Recognition, indian red color:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a group of stuffed animals sitting on top of a building:Microsoft Computer Vision, building:Microsoft Computer Vision, window:Microsoft Computer Vision, sitting:Microsoft Computer Vision, group:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, people:Microsoft Computer Vision, table:Microsoft Computer Vision, large:Microsoft Computer Vision, many:Microsoft Computer Vision, bunch:Microsoft Computer Vision, bench:Microsoft Computer Vision, room:Microsoft Computer Vision, man:Microsoft Computer Vision, standing:Microsoft Computer Vision, wooden:Microsoft Computer Vision, bear:Microsoft Computer Vision, woman:Microsoft Computer Vision, display:Microsoft Computer Vision, street:Microsoft Computer Vision, city:Microsoft Computer Vision, riding:Microsoft Computer Vision",
		"people:Clarifai, portrait:Clarifai, man:Clarifai, one:Clarifai, art:Clarifai, adult:Clarifai, illustration:Clarifai, painting:Clarifai, street:Clarifai, urban:Clarifai, vintage:Clarifai, face:Clarifai, smoke:Clarifai, wear:Clarifai, retro:Clarifai, dark:Clarifai, person:Clarifai, sit:Clarifai, print:Clarifai, music:Clarifai, man in black suit jacket photo:CloudSight, black:CloudSight Hybrid, blue:CloudSight Hybrid, and yellow abstract painting:CloudSight Hybrid, art:Google Vision, portrait:Google Vision, self-portrait:Google Vision, visual arts:Google Vision, painting:Google Vision, human:Amazon Rekognition, person:Amazon Rekognition, blackboard:Amazon Rekognition, person:IBM Visual Recognition, goalpost:IBM Visual Recognition, support:IBM Visual Recognition, penalty box:IBM Visual Recognition, bench:IBM Visual Recognition, seat:IBM Visual Recognition, furniture:IBM Visual Recognition, sport:IBM Visual Recognition, black color:IBM Visual Recognition, coal black color:IBM Visual Recognition, yellow:Microsoft Computer Vision, man:Microsoft Computer Vision, photo:Microsoft Computer Vision, sitting:Microsoft Computer Vision, wearing:Microsoft Computer Vision, sign:Microsoft Computer Vision, black:Microsoft Computer Vision, holding:Microsoft Computer Vision, standing:Microsoft Computer Vision, table:Microsoft Computer Vision, horse:Microsoft Computer Vision, phone:Microsoft Computer Vision, riding:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, statue:Clarifai, ancient:Clarifai, buddha:Clarifai, religion:Clarifai, old:Clarifai, god:Clarifai, temple:Clarifai, traditional:Clarifai, culture:Clarifai, zen:Clarifai, spirituality:Clarifai, meditation:Clarifai, man:Clarifai, figure:Clarifai, people:Clarifai, figurine:Clarifai, travel:Clarifai, veil:Clarifai, man in brown suit figurine:CloudSight, hindu deity statue:CloudSight Hybrid, sculpture:Google Vision, statue:Google Vision, art:Google Vision, stone carving:Google Vision, classical sculpture:Google Vision, sitting:Google Vision, figurine:Google Vision, artifact:Google Vision, meditation:Google Vision, monument:Google Vision, worship:Amazon Rekognition, building:Amazon Rekognition, architecture:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, art:Amazon Rekognition, buddha:Amazon Rekognition, temple:Amazon Rekognition, shrine:Amazon Rekognition, pieta (statue):IBM Visual Recognition, person:IBM Visual Recognition, people:IBM Visual Recognition, cadaver:IBM Visual Recognition, artifact:IBM Visual Recognition, mycenaen artifacts (greek):IBM Visual Recognition, museum (indoor):IBM Visual Recognition, toby jug:IBM Visual Recognition, drinking vessel:IBM Visual Recognition, sculpture:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a statue of a man:Microsoft Computer Vision, person:Microsoft Computer Vision, man:Microsoft Computer Vision, sitting:Microsoft Computer Vision, building:Microsoft Computer Vision, holding:Microsoft Computer Vision, standing:Microsoft Computer Vision, statue:Microsoft Computer Vision, table:Microsoft Computer Vision, old:Microsoft Computer Vision, phone:Microsoft Computer Vision, wearing:Microsoft Computer Vision, large:Microsoft Computer Vision, yellow:Microsoft Computer Vision, cake:Microsoft Computer Vision, street:Microsoft Computer Vision, zebra:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, statue:Clarifai, ancient:Clarifai, no person:Clarifai, nude:Clarifai, metalwork:Clarifai, travel:Clarifai, bronze:Clarifai, religion:Clarifai, monument:Clarifai, museum:Clarifai, figure:Clarifai, renaissance:Clarifai, god:Clarifai, man:Clarifai, old:Clarifai, artistic:Clarifai, figurine:Clarifai, architecture:Clarifai, man in black suit figurine:CloudSight, man riding elephant statuette:CloudSight Hybrid, sculpture:Google Vision, statue:Google Vision, classical sculpture:Google Vision, art:Google Vision, figurine:Google Vision, stone carving:Google Vision, standing:Google Vision, carving:Google Vision, monument:Google Vision, visual arts:Google Vision, toy:Amazon Rekognition, art:Amazon Rekognition, sculpture:Amazon Rekognition, statue:Amazon Rekognition, figurine:Amazon Rekognition, monument:Amazon Rekognition, bronze:Amazon Rekognition, archaeology:Amazon Rekognition, museum (indoor):IBM Visual Recognition, indoors:IBM Visual Recognition, alabaster color:IBM Visual Recognition, a statue of a person:Microsoft Computer Vision, indoor:Microsoft Computer Vision, sculpture:Microsoft Computer Vision, building:Microsoft Computer Vision, statue:Microsoft Computer Vision, sitting:Microsoft Computer Vision, chain:Microsoft Computer Vision, table:Microsoft Computer Vision, metal:Microsoft Computer Vision, wooden:Microsoft Computer Vision, elephant:Microsoft Computer Vision, large:Microsoft Computer Vision, water:Microsoft Computer Vision, standing:Microsoft Computer Vision, holding:Microsoft Computer Vision, display:Microsoft Computer Vision, room:Microsoft Computer Vision, man:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, statue:Clarifai, ancient:Clarifai, religion:Clarifai, culture:Clarifai, stone:Clarifai, grave:Clarifai, god:Clarifai, archaeology:Clarifai, old:Clarifai, buddha:Clarifai, monument:Clarifai, symbol:Clarifai, temple:Clarifai, figure:Clarifai, religious belief:Clarifai, carve:Clarifai, face:Clarifai, spirituality:Clarifai, pair of gray suede slip on shoes:CloudSight, gray concrete buddhai statue:CloudSight Hybrid, stone carving:Google Vision, sculpture:Google Vision, statue:Google Vision, classical sculpture:Google Vision, carving:Google Vision, artifact:Google Vision, head:Google Vision, art:Google Vision, relief:Google Vision, ancient history:Google Vision, archaeology:Amazon Rekognition, figurine:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, art:Amazon Rekognition, sculpture:Amazon Rekognition, photo:Amazon Rekognition, photography:Amazon Rekognition, painting:Amazon Rekognition, portrait:Amazon Rekognition, face:Amazon Rekognition, worship:Amazon Rekognition, buddha:Amazon Rekognition, stele (stone slab with markings):IBM Visual Recognition, alabaster color:IBM Visual Recognition, a stone statue of a man:Microsoft Computer Vision, building:Microsoft Computer Vision, stone:Microsoft Computer Vision, artifact:Microsoft Computer Vision, man:Microsoft Computer Vision, sitting:Microsoft Computer Vision, feet:Microsoft Computer Vision, statue:Microsoft Computer Vision, bear:Microsoft Computer Vision, holding:Microsoft Computer Vision, large:Microsoft Computer Vision, standing:Microsoft Computer Vision, bird:Microsoft Computer Vision, white:Microsoft Computer Vision, stuffed:Microsoft Computer Vision, laying:Microsoft Computer Vision",
		"art:Clarifai, ancient:Clarifai, no person:Clarifai, antique:Clarifai, old:Clarifai, sculpture:Clarifai, marble:Clarifai, classic:Clarifai, architecture:Clarifai, ornate:Clarifai, chess:Clarifai, bronze:Clarifai, statue:Clarifai, glass items:Clarifai, luxury:Clarifai, artistic:Clarifai, pedestal:Clarifai, gold:Clarifai, traditional:Clarifai, design:Clarifai, silver and clear glass candle holder:CloudSight, grey statue:CloudSight Hybrid, trophy:Google Vision, still life photography:Google Vision, water feature:Google Vision, sculpture:Google Vision, fountain:Google Vision, glass:Google Vision, statue:Google Vision, metal:Google Vision, silver:Google Vision, glass:Amazon Rekognition, goblet:Amazon Rekognition, symbol:Amazon Rekognition, cross:Amazon Rekognition, tabletop:Amazon Rekognition, furniture:Amazon Rekognition, bronze:Amazon Rekognition, crystal:Amazon Rekognition, socle:IBM Visual Recognition, support:IBM Visual Recognition, supporting structure:IBM Visual Recognition, fountain:IBM Visual Recognition, censer container:IBM Visual Recognition, pedestal:IBM Visual Recognition, holding device:IBM Visual Recognition, building:IBM Visual Recognition, alabaster color:IBM Visual Recognition, sitting:Microsoft Computer Vision, standing:Microsoft Computer Vision, building:Microsoft Computer Vision, clock:Microsoft Computer Vision, dark:Microsoft Computer Vision, vase:Microsoft Computer Vision, front:Microsoft Computer Vision, black:Microsoft Computer Vision, middle:Microsoft Computer Vision, tall:Microsoft Computer Vision, holding:Microsoft Computer Vision, lamp:Microsoft Computer Vision, table:Microsoft Computer Vision, light:Microsoft Computer Vision, large:Microsoft Computer Vision, tower:Microsoft Computer Vision, white:Microsoft Computer Vision, man:Microsoft Computer Vision, cup:Microsoft Computer Vision, gold:Microsoft Computer Vision, display:Microsoft Computer Vision, street:Microsoft Computer Vision, room:Microsoft Computer Vision",
		"no person:Clarifai, furniture:Clarifai, wood:Clarifai, carpentry:Clarifai, antique:Clarifai, old:Clarifai, art:Clarifai, design:Clarifai, retro:Clarifai, architecture:Clarifai, classic:Clarifai, interior design:Clarifai, ornate:Clarifai, seat:Clarifai, leather:Clarifai, style:Clarifai, sculpture:Clarifai, empty:Clarifai, carve:Clarifai, ancient:Clarifai, brown wooden cabinet with drawer:CloudSight, brown wooden cabinet:CloudSight Hybrid, furniture:Google Vision, carving:Google Vision, chair:Google Vision, antique:Google Vision, table:Google Vision, cupboard:Google Vision, wood stain:Google Vision, wood:Google Vision, hardwood:Google Vision, furniture:Amazon Rekognition, cupboard:Amazon Rekognition, closet:Amazon Rekognition, cabinet:Amazon Rekognition, mailbox:Amazon Rekognition, letterbox:Amazon Rekognition, table:Amazon Rekognition, sideboard:Amazon Rekognition, marquetry (veneers):IBM Visual Recognition, sideboard:IBM Visual Recognition, coffer (chest):IBM Visual Recognition, box:IBM Visual Recognition, reddish brown color:IBM Visual Recognition, a wooden clock with furniture:Microsoft Computer Vision, wooden:Microsoft Computer Vision, furniture:Microsoft Computer Vision, indoor:Microsoft Computer Vision, clock:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, wood:Microsoft Computer Vision, small:Microsoft Computer Vision, room:Microsoft Computer Vision, brown:Microsoft Computer Vision, old:Microsoft Computer Vision, bed:Microsoft Computer Vision, large:Microsoft Computer Vision, statue:Microsoft Computer Vision, desk:Microsoft Computer Vision, standing:Microsoft Computer Vision, cat:Microsoft Computer Vision",
		"furniture:Clarifai, luxury:Clarifai, baroque:Clarifai, no person:Clarifai, antique:Clarifai, art:Clarifai, classic:Clarifai, ornate:Clarifai, museum:Clarifai, bronze:Clarifai, elegant:Clarifai, victorian:Clarifai, painting:Clarifai, retro:Clarifai, ancient:Clarifai, interior design:Clarifai, vintage:Clarifai, indoors:Clarifai, gold:Clarifai, old:Clarifai, brown wooden frame wall decor:CloudSight, gold side table:CloudSight Hybrid, furniture:Google Vision, table:Google Vision, sofa tables:Google Vision, napoleon iii style:Google Vision, antique:Google Vision, end table:Google Vision, brass:Google Vision, metal:Google Vision, furniture:Amazon Rekognition, sideboard:Amazon Rekognition, tabletop:Amazon Rekognition, table:Amazon Rekognition, indoors:Amazon Rekognition, dining table:Amazon Rekognition, desk:Amazon Rekognition, console table:IBM Visual Recognition, table:IBM Visual Recognition, furniture:IBM Visual Recognition, pier table:IBM Visual Recognition, light brown color:IBM Visual Recognition, beige color:IBM Visual Recognition, a gold clock sitting on top of a wooden table:Microsoft Computer Vision, indoor:Microsoft Computer Vision, table:Microsoft Computer Vision, furniture:Microsoft Computer Vision, sitting:Microsoft Computer Vision, hanging:Microsoft Computer Vision, wooden:Microsoft Computer Vision, room:Microsoft Computer Vision, gold:Microsoft Computer Vision, bed:Microsoft Computer Vision, clock:Microsoft Computer Vision, water:Microsoft Computer Vision, standing:Microsoft Computer Vision, laying:Microsoft Computer Vision, white:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, statue:Clarifai, figurine:Clarifai, ancient:Clarifai, nude:Clarifai, travel:Clarifai, god:Clarifai, no person:Clarifai, old:Clarifai, religion:Clarifai, decoration:Clarifai, museum:Clarifai, goddess:Clarifai, carve:Clarifai, bronze:Clarifai, antique:Clarifai, figure:Clarifai, gold:Clarifai, metalwork:Clarifai, brown wooden horse figurine screenshot:CloudSight, brown deity statuette:CloudSight Hybrid, sculpture:Google Vision, statue:Google Vision, stone carving:Google Vision, art:Google Vision, classical sculpture:Google Vision, monument:Google Vision, carving:Google Vision, metal:Google Vision, bronze:Google Vision, mythology:Google Vision, figurine:Amazon Rekognition, wood:Amazon Rekognition, building:Amazon Rekognition, architecture:Amazon Rekognition, temple:Amazon Rekognition, worship:Amazon Rekognition, bronze:Amazon Rekognition, symbol:Amazon Rekognition, cross:Amazon Rekognition, shrine:Amazon Rekognition, art:Amazon Rekognition, hardwood:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, flooring:Amazon Rekognition, sculpture:Amazon Rekognition, buddha:Amazon Rekognition, urban:Amazon Rekognition, metropolis:Amazon Rekognition, city:Amazon Rekognition, town:Amazon Rekognition, archaeology:Amazon Rekognition, person:IBM Visual Recognition, artifact:IBM Visual Recognition, woodcarving:IBM Visual Recognition, sculpture:IBM Visual Recognition, figure:IBM Visual Recognition, reliquary container:IBM Visual Recognition, kachina dolls:IBM Visual Recognition, censer container:IBM Visual Recognition, alabaster color:IBM Visual Recognition, sitting:Microsoft Computer Vision, table:Microsoft Computer Vision, standing:Microsoft Computer Vision, wooden:Microsoft Computer Vision, different:Microsoft Computer Vision, display:Microsoft Computer Vision, old:Microsoft Computer Vision, group:Microsoft Computer Vision, laying:Microsoft Computer Vision, cat:Microsoft Computer Vision, clock:Microsoft Computer Vision, room:Microsoft Computer Vision",
		"carpentry:Clarifai, leather:Clarifai, no person:Clarifai, sculpture:Clarifai, furniture:Clarifai, steel:Clarifai, wood:Clarifai, art:Clarifai, iron:Clarifai, museum:Clarifai, retro:Clarifai, design:Clarifai, people:Clarifai, vintage:Clarifai, old:Clarifai, fashion:Clarifai, ancient:Clarifai, exert:Clarifai, decoration:Clarifai, chrome:Clarifai, gray and black leather handbag:CloudSight, gray robe decor:CloudSight Hybrid, bar stool:Google Vision, stool:Google Vision, sculpture:Google Vision, furniture:Google Vision, table:Google Vision, metal:Google Vision, silver:Google Vision, art:Google Vision, sink faucet:Amazon Rekognition, wood:Amazon Rekognition, bronze:Amazon Rekognition, pedestal table:IBM Visual Recognition, table:IBM Visual Recognition, furniture:IBM Visual Recognition, candlestick:IBM Visual Recognition, holder:IBM Visual Recognition, propeller:IBM Visual Recognition, mechanical device:IBM Visual Recognition, stool:IBM Visual Recognition, seat:IBM Visual Recognition, ax handle:IBM Visual Recognition, ax:IBM Visual Recognition, cutlery:IBM Visual Recognition, tool:IBM Visual Recognition, footwear:IBM Visual Recognition, headdress:IBM Visual Recognition, ash grey color:IBM Visual Recognition, indoor:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, gray:Microsoft Computer Vision, elephant:Microsoft Computer Vision, grey:Microsoft Computer Vision, chair:Microsoft Computer Vision, desk:Microsoft Computer Vision, wooden:Microsoft Computer Vision, mouse:Microsoft Computer Vision, computer:Microsoft Computer Vision, cat:Microsoft Computer Vision, brown:Microsoft Computer Vision, made:Microsoft Computer Vision, keyboard:Microsoft Computer Vision, large:Microsoft Computer Vision, apple:Microsoft Computer Vision, room:Microsoft Computer Vision, standing:Microsoft Computer Vision, white:Microsoft Computer Vision",
		"sculpture:Clarifai, art:Clarifai, traditional:Clarifai, veil:Clarifai, travel:Clarifai, temple:Clarifai, religion:Clarifai, ancient:Clarifai, people:Clarifai, statue:Clarifai, wear:Clarifai, no person:Clarifai, culture:Clarifai, buddha:Clarifai, tribal:Clarifai, adult:Clarifai, woman:Clarifai, figure:Clarifai, god:Clarifai, spirituality:Clarifai, brown and black ceramic figurine:CloudSight, multicolored samurai armor:CloudSight Hybrid, samurai:Google Vision, armour:Google Vision, armor:Amazon Rekognition, person:Amazon Rekognition, human:Amazon Rekognition, samurai:Amazon Rekognition, robot:IBM Visual Recognition, kachina:IBM Visual Recognition, mechanism:IBM Visual Recognition, ultramarine color:IBM Visual Recognition, indian red color:IBM Visual Recognition, a close up of a toy:Microsoft Computer Vision, toy:Microsoft Computer Vision, doll:Microsoft Computer Vision, table:Microsoft Computer Vision, sitting:Microsoft Computer Vision, cellphone:Microsoft Computer Vision, phone:Microsoft Computer Vision, wearing:Microsoft Computer Vision, yellow:Microsoft Computer Vision, hat:Microsoft Computer Vision, holding:Microsoft Computer Vision, display:Microsoft Computer Vision, covered:Microsoft Computer Vision, white:Microsoft Computer Vision, gold:Microsoft Computer Vision, man:Microsoft Computer Vision, woman:Microsoft Computer Vision, standing:Microsoft Computer Vision, stacked:Microsoft Computer Vision, bed:Microsoft Computer Vision",
		"painting:Clarifai, graffiti:Clarifai, art:Clarifai, illustration:Clarifai, mural:Clarifai, wall:Clarifai, artistic:Clarifai, man:Clarifai, vandalism:Clarifai, caricature:Clarifai, people:Clarifai, visuals:Clarifai, color:Clarifai, woman:Clarifai, hip:Clarifai, culture:Clarifai, street:Clarifai, adult:Clarifai, religion:Clarifai, spray:Clarifai, brown and blue wooden painting:CloudSight, three women painting:CloudSight Hybrid, painting:Google Vision, modern art:Google Vision, art:Google Vision, visual arts:Google Vision, illustration:Google Vision, acrylic paint:Google Vision, watercolor paint:Google Vision, artwork:Google Vision, art:Amazon Rekognition, painting:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, mural:Amazon Rekognition, animal:Amazon Rekognition, bird:Amazon Rekognition, graffiti:Amazon Rekognition, modern art:Amazon Rekognition, fauve painting:IBM Visual Recognition, person:IBM Visual Recognition, oil paint:IBM Visual Recognition, paint:IBM Visual Recognition, painting:IBM Visual Recognition, tapestry:IBM Visual Recognition, fabric:IBM Visual Recognition, indoors:IBM Visual Recognition, brick red color:IBM Visual Recognition, indian red color:IBM Visual Recognition, a painting of a book:Microsoft Computer Vision, text:Microsoft Computer Vision, book:Microsoft Computer Vision, photo:Microsoft Computer Vision, grass:Microsoft Computer Vision, man:Microsoft Computer Vision, table:Microsoft Computer Vision, painted:Microsoft Computer Vision, painting:Microsoft Computer Vision, elephant:Microsoft Computer Vision, holding:Microsoft Computer Vision, old:Microsoft Computer Vision, birthday:Microsoft Computer Vision, water:Microsoft Computer Vision, board:Microsoft Computer Vision, horse:Microsoft Computer Vision, graffiti:Microsoft Computer Vision, sign:Microsoft Computer Vision, standing:Microsoft Computer Vision, riding:Microsoft Computer Vision",
		"fashion:Clarifai, dress:Clarifai, woman:Clarifai, wear:Clarifai, cotton:Clarifai, model:Clarifai, shopping:Clarifai, design:Clarifai, girl:Clarifai, elegant:Clarifai, isolated:Clarifai, no person:Clarifai, color:Clarifai, art:Clarifai, classic:Clarifai, isolate:Clarifai, textile:Clarifai, style:Clarifai, people:Clarifai, sleeve:Clarifai, womens white and pink floral shorts:CloudSight, mens brown thobe:CloudSight Hybrid, clothing:Google Vision, sleeve:Google Vision, outerwear:Google Vision, dress:Google Vision, beige:Google Vision, robe:Google Vision, pattern:Google Vision, jacket:Google Vision, lace:Google Vision, embroidery:Google Vision, apparel:Amazon Rekognition, clothing:Amazon Rekognition, long sleeve:Amazon Rekognition, sleeve:Amazon Rekognition, blouse:Amazon Rekognition, human:Amazon Rekognition, person:Amazon Rekognition, sleeve:IBM Visual Recognition, blouse:IBM Visual Recognition, clothing:IBM Visual Recognition, fabric:IBM Visual Recognition, beige color:IBM Visual Recognition, a person in a white shirt:Microsoft Computer Vision, indoor:Microsoft Computer Vision, shirt:Microsoft Computer Vision, wearing:Microsoft Computer Vision, white:Microsoft Computer Vision, head:Microsoft Computer Vision, man:Microsoft Computer Vision, holding:Microsoft Computer Vision, standing:Microsoft Computer Vision, room:Microsoft Computer Vision, night:Microsoft Computer Vision",
	]

	var art_weight = []


	// CATEGORIZED BY SERVICE

	var art_cats = []

	for (var i = 0; i < art_raw_cats.length; i++) {
		piece_cats = art_raw_cats[i]
		split_cats = piece_cats.split(", ")
		art_cats.push(split_cats)

		piece_weight = art_raw[i]
		split_weight = piece_weight.split(", ")
		art_weight.push(split_weight)
	};

	// console.log("art_weight LIST")
	// console.log(art_weight)

	console.log("cats")
	console.log(art_cats.length)
	console.log("weight")
	console.log(art_weight.length)

	count = 0
	for (var i = 0; i < art_cats.length; i++) {
		piece_cats = art_cats[i]

		piece_weight = art_weight[i]

		print_tags(count.toString(), piece_cats, piece_weight)
		count += 1
	};

	function print_tags(div, piece, piece_weighted) {

		console.log("Printing tags")

		services = ["Clarifai", "CloudSight", "CloudSight_Hybrid", "Google_Vision", "Amazon_Rekognition", "IBM_Visual_Recognition", "Microsoft_Computer_Vision"]

//		 Clarifai, CloudSight, Google_Vision, Amazon_Rekognition, IBM_Visual_Recognition, Microsoft_Computer_Vision

		master = {"Clarifai":[], "CloudSight":[], "CloudSight_Hybrid":[], "Google_Vision":[], "Amazon_Rekognition":[], "IBM_Visual_Recognition":[], "Microsoft_Computer_Vision":[]}


		weight_dict = {}

		for (var i = 0; i < piece_weighted.length; i++) {

			touple_weight = piece_weighted[i]
			singles_weight = touple_weight.split(": ")

			weight_dict[singles_weight[0]] = parseInt(singles_weight[1])
		}


		console.log("dictionary")
		console.log(weight_dict)

		graph_id = div + "_pie"

		//create_graphs(graph_id, weight_dict)
		//create_graphs_bar(graph_id, weight_dict)

		for (var i = 0; i < piece.length; i++) {

			touple = piece[i]

			singles = touple.split(":")

			// singles[0] - the tag, singles_weight[1] - the weight
			tag_and_weight = singles[0]

			// singles[1] - the service
			service = singles[1].replace(/ /g, "_")

			// current values of list
			curs = []

			// list to be copied over
			news = []

			curs = master[service]

			for (var j = 0; j < curs.length; j++) {
				news.push(curs[j])
			}

			news.push(tag_and_weight)

			master[service] = news

		}



		for (var i = 0; i < services.length; i++) {

			tags = master[services[i]]

			id = "#" + services[i] + "_" + div
			update_tags(services[i], tags, id, weight_dict)

		}		

		
	};

	function update_tags(service, tags, id, weight_dict) {


		color_dict = ["#616161", "#fab95b", "#ff502f", "#009975", "#454d66", "#7572f4", "#207dff"]

		html_output = "<p>"

		for (var j = 0; j < tags.length; j++) {

			weight = weight_dict[tags[j]]


			color = "<span style='color:" + color_dict[weight - 1] + "'>"

			//html_output += tags[j]

			html_output += color + tags[j] + "</span>"


			if (j != tags.length - 1) {
				html_output += ", "
			}
		}

		html_output += "</p>"


		$(id).html(html_output);
	}

	function create_graphs(id, weight_dict) {

		tags = []
		weights = []

		for (var key in weight_dict) {
		    // check if the property/key is defined in the object itself, not in parent
		    if (weight_dict.hasOwnProperty(key)) {           
		        console.log(key, weight_dict[key]);
		        tags.push(key)
		        weights.push(weight_dict[key])
		    }
		}




	  	var ctxP = document.getElementById(id).getContext('2d');
	  	var myPieChart = new Chart(ctxP, {
	    	type: 'pie',
	    	data: {
	      		labels: tags,
	      		datasets: [{
	        		data: weights,
	        		// backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
	        		// hoverBackgroundColor: ["#FF5A5E", "#5AD3D1", "#FFC870", "#A8B3C5", "#616774"]
	      		}]
	    	},
	    	options: {
	    		legend: {
		            display: true,
		            position: 'left'
		         },
		        plugins: {
			      	colorschemes: {
			        	scheme: 'tableau.Tableau20'
			      	}
			    },
		    	
				
	      		responsive: true
	    	},
		});

	}

	function create_graphs_bar(id, weight_dict) {

		tags = []
		weights = []

		for (var key in weight_dict) {
		    // check if the property/key is defined in the object itself, not in parent
		    if (weight_dict.hasOwnProperty(key)) {           
		        console.log(key, weight_dict[key]);
		        tags.push(key)
		        weights.push(weight_dict[key])
		    }
		}
		var ctx = document.getElementById(id).getContext('2d');

		var myBarChart = new Chart(ctx, {
		    type: 'horizontalBar',
	    	data: {
	      		labels: tags,
	      		datasets: [{
	        		data: weights,
	        		// backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
	        		// hoverBackgroundColor: ["#FF5A5E", "#5AD3D1", "#FFC870", "#A8B3C5", "#616774"]
	      		}]
	    	},
		});
	}
});


